"""optionsmenu çevirilerini tr.json'a uygular."""
import json
from pathlib import Path

TRANSLATIONS = {
  "optionsmenu_accessibility_audiodescription": "Sesli Açıklama",
  "optionsmenu_accessibility_audiodescription_desc": "Sesli açıklamayı açar veya kapatır.",
  "optionsmenu_accessibility_audiodescription_title": "Sesli Açıklama",
  "optionsmenu_accessibility_colourpalette": "Renk Paleti",
  "optionsmenu_accessibility_colourpalette_desc": "Okunabilirliği artırmak için farklı renk körlüğü dostu paletler arasından seçim yapın.",
  "optionsmenu_accessibility_colourpalette_title": "Renk Paleti",
  "optionsmenu_accessibility_desc": "Ekran, altyazı ve sesli açıklama gibi erişilebilirlik ayarlarını buradan düzenleyin.",
  "optionsmenu_accessibility_gamepadmode": "Denetleyici Modu",
  "optionsmenu_accessibility_gamepadmode_desc": "Hazır denetleyici modu önayarları arasından seçim yapın.",
  "optionsmenu_accessibility_gamepadmode_title": "Denetleyici Modu",
  "optionsmenu_accessibility_header": "Erişilebilirlik Ayarları",
  "optionsmenu_accessibility_interfacescale_desc": "Metin ve görseller gibi arayüz öğelerinin boyutunu kaydırıcıyla ayarlayın.",
  "optionsmenu_accessibility_interfacescale_title": "Arayüz Ölçeği",
  "optionsmenu_accessibility_screenflash_desc": "Fırtına sırasında ekran flaş efektlerinin gösterilip gösterilmeyeceğini ayarlayın.",
  "optionsmenu_accessibility_screenflash_label": "Yıldırım Flaş Efektlerini Devre Dışı Bırak",
  "optionsmenu_accessibility_screenflash_title": "Yıldırım Flaş Efektlerini Devre Dışı Bırak",
  "optionsmenu_accessibility_screensetup_desc": "Parlaklık ve görüntü alanını ayarlayarak ekranınızı yapılandırın.",
  "optionsmenu_accessibility_screensetup_title": "Ekran Kurulumu",
  "optionsmenu_accessibility_showsubtitles": "Altyazıları Göster",
  "optionsmenu_accessibility_subtitles_desc": "Altyazıları açar veya kapatır.",
  "optionsmenu_accessibility_subtitles_title": "Altyazıları Göster",
  "optionsmenu_accessibility_textsize_desc": "Ekrandaki metnin boyutunu büyütün veya küçültün.",
  "optionsmenu_accessibility_textsize_title": "Metin Boyutu",
  "optionsmenu_accessibility_title": "Erişilebilirlik",
  "optionsmenu_accessibility_vibrate_desc": "Denetleyici titreşimini açar veya kapatır.",
  "optionsmenu_accessibility_vibrate_title": "Titreşim",
  "optionsmenu_adapter_desc": "Oyunun grafik işleme için hangi grafik bağdaştırıcısını (ekran kartını) kullanacağını seçin.",
  "optionsmenu_advancedmovealignmentaverage": "Gelişmiş Taşıma'da Ortalanmış Yön",
  "optionsmenu_ao_desc": "Ambient occlusion, ortam ışığının oluşturduğu yumuşak gölgeleri simüle eden bir tekniktir.",
  "optionsmenu_apply": "Uygula",
  "optionsmenu_applyprompt_description": "Ayarlar panelini kapatmadan önce bu değişiklikleri uygulamak istiyor musunuz?",
  "optionsmenu_applyprompt_no": "Hayır",
  "optionsmenu_applyprompt_title": "Ayarlar uygulanacak mı?",
  "optionsmenu_applyprompt_yes": "Evet",
  "optionsmenu_audio": "Ses",
  "optionsmenu_audio_accessibility": "Ses Erişilebilirliği",
  "optionsmenu_audio_adjustridessoundeffectvolume": "Eğlence Ses Efektleri Seviyesi",
  "optionsmenu_audio_adjustridessoundeffectvolume_desc": "Eğlence Ses Efektleri Seviyesi",
  "optionsmenu_audio_adjustridessoundeffectvolume_title": "Eğlence Ses Efektleri Seviyesi",
  "optionsmenu_audio_adjustsoundeffectambience_desc": "Parklarınızdaki çevre ve hava durumu seslerinin seviyesini kaydırıcıyla ayarlayın.",
  "optionsmenu_audio_adjustsoundeffectambience_title": "Ses Efektleri - Ortam Sesleri",
  "optionsmenu_audio_adjustsoundeffectcoasters_desc": "Parklarınızdaki hız trenlerinin ses seviyesini kaydırıcıyla ayarlayın.",
  "optionsmenu_audio_adjustsoundeffectcoasters_title": "Ses Efektleri - Hız Trenleri",
  "optionsmenu_audio_adjustsoundeffectflatrides_desc": "Parklarınızdaki düz eğlencelerin ses seviyesini kaydırıcıyla ayarlayın.",
  "optionsmenu_audio_adjustsoundeffectflatrides_title": "Ses Efektleri - Düz Eğlenceler",
  "optionsmenu_audio_adjustsoundeffectvolume_desc": "Ses efektlerinin seviyesini kaydırıcıyla ayarlayın.",
  "optionsmenu_audio_adjustsoundeffectvolume_title": "Ses Efektleri",
  "optionsmenu_audio_adjustsoundeffectwaterparks_desc": "Parklarınızdaki akarsu yollarının ve havuzların ses seviyesini kaydırıcıyla ayarlayın.",
  "optionsmenu_audio_adjustsoundeffectwaterparks_title": "Ses Efektleri - Su Parkları",
  "optionsmenu_audio_adjustsoundtrackvolume_desc": "Müzik parçasının seviyesini kaydırıcıyla artırın veya azaltın.",
  "optionsmenu_audio_adjustsoundtrackvolume_title": "Müzik Parçası Seviyesini Ayarla",
  "optionsmenu_audio_desc": "Ses seviyesi ayarlarını yapın ve farklı ses öğelerinin seviyelerini düzenleyin.",
  "optionsmenu_audio_header": "Ses Ayarları",
  "optionsmenu_audio_mastering": "Mastering",
  "optionsmenu_audio_mastervolume_desc": "Ana ses seviyesini kaydırıcıyla artırın veya azaltın.",
  "optionsmenu_audio_mastervolume_title": "Ana Ses Seviyesini Ayarla",
  "optionsmenu_audio_mute": "Sessiz",
  "optionsmenu_audio_muteallentry": "Tümünü Sessize Al",
  "optionsmenu_audio_mutegamesoundtrack_desc": "Oyun müziğini sessize alır veya açar.",
  "optionsmenu_audio_mutegamesoundtrack_title": "Oyun Müziğini Sessize Al",
  "optionsmenu_audio_muteguientry": "Arayüz Seslerini Sessize Al",
  "optionsmenu_audio_muteguientryinfo": "Arayüz Seslerini Sessize Al Bilgisi",
  "optionsmenu_audio_mutelicencedentry": "Lisanslı Müziği Sessize Al",
  "optionsmenu_audio_mutemenumusicentry": "Menü Müziğini Sessize Al",
  "optionsmenu_audio_mutemenusoundtrack_desc": "Menü müziğini sessize alır veya açar.",
  "optionsmenu_audio_mutemenusoundtrack_title": "Menü Müziğini Sessize Al",
  "optionsmenu_audio_muteparkmusic_desc": "Parkınızda çalan müziği sessize alır veya açar.",
  "optionsmenu_audio_muteparkmusic_title": "Park Müziğini Sessize Al",
  "optionsmenu_audio_muteridemusicentry": "Park Müziğini Sessize Al",
  "optionsmenu_audio_mutesfxentry": "Ses Efektlerini Sessize Al",
  "optionsmenu_audio_muteshopradio_desc": "Parkınızdaki dükkânlardan gelen radyo seslerini sessize alır veya açar.",
  "optionsmenu_audio_muteshopradio_title": "Dükkan Radyosunu Sessize Al",
  "optionsmenu_audio_muteshopradioentry": "Dükkan Radyosunu Sessize Al",
  "optionsmenu_audio_mutesoundeffects_desc": "Ses efektlerini sessize alır veya açar.",
  "optionsmenu_audio_mutesoundeffects_title": "Ses Efektlerini Sessize Al",
  "optionsmenu_audio_mutesoundtrackentry": "Oyun Müziğini Sessize Al",
  "optionsmenu_audio_muteuisounds_desc": "Oyun arayüzünün tetiklediği sesleri sessize alır veya açar.",
  "optionsmenu_audio_muteuisounds_title": "Arayüz Seslerini Sessize Al",
  "optionsmenu_audio_mutevoentry": "Sesi Sessize Al",
  "optionsmenu_audio_mutevoice_desc": "Seslendirmeyi sessize alır veya açar.",
  "optionsmenu_audio_mutevoice_title": "Seslendirmeyi Sessize Al",
  "optionsmenu_audio_parkmusic": "Park Müziği",
  "optionsmenu_audio_parkmusicvolume_desc": "Parkınızda çalan müziğin sesini kaydırıcıyla artırın veya azaltın.",
  "optionsmenu_audio_parkmusicvolume_title": "Park Müziği Seviyesini Ayarla",
  "optionsmenu_audio_playsoundtrackpause_desc": "Duraklatma modunda müzik parçasının çalınıp çalınmayacağını seçin.",
  "optionsmenu_audio_playsoundtrackpause_title": "Müziği Yalnızca Duraklatma Modunda Çal",
  "optionsmenu_audio_sfx": "Ses Efektleri Seviyesi",
  "optionsmenu_audio_soundtrack": "Müzik Parçası",
  "optionsmenu_audio_soundtrackinpause": "Müziği Yalnızca Duraklatma Modunda Çal",
  "optionsmenu_audio_title": "Ses Ayarları",
  "optionsmenu_audio_vo": "Ses Seviyesi",
  "optionsmenu_audio_voicevolume_desc": "Seslendirme sesini kaydırıcıyla artırın veya azaltın.",
  "optionsmenu_audio_voicevolume_title": "Seslendirme Seviyesini Ayarla",
  "optionsmenu_audio_volume": "Ana Ses",
  "optionsmenu_audio_volume_entry": "Sesi Ayarla",
  "optionsmenu_autosaveinterval": "Otomatik Kayıt Sıklığı",
  "optionsmenu_autosaveinterval_description": "Otomatik kaydın ne sıklıkla oluşturulacağı.",
  "optionsmenu_autosaveinterval_disabled": "Devre Dışı",
  "optionsmenu_autosaveinterval_header": "Otomatik Kayıt Sıklığı",
  "optionsmenu_back": "Geri",
  "optionsmenu_backgroundatmos_desc": "Arka planın ne kadar ayrıntılı görüneceğini seçin.",
  "optionsmenu_bloom_desc": "Bloom efektini açar veya kapatır. Bloom, gerçek hayattaki ışık yayılımını ve dağılımını taklit eden bir efekttir.",
  "optionsmenu_brightness": "Parlaklık",
  "optionsmenu_brightness_details": "Ekranınızın parlaklığını ayarlamak için kaydırıcıyı en soldaki logonun zar zor görüneceği konuma getirin.",
  "optionsmenu_buildingsettings": "Yapı Ayarları",
  "optionsmenu_buynow": "Mağazaya Git",
  "optionsmenu_buynow_alt": "Microsoft Store",
  "optionsmenu_buyunowneddlc": "DLC'yi şimdi satın al",
  "optionsmenu_camera": "Kamera",
  "optionsmenu_camera_fieldofview": "Görüş Alanı",
  "optionsmenu_camera_fixedtilt": "Sabit Eğim",
  "optionsmenu_camera_focusoncursor": "İmlece Odaklan",
  "optionsmenu_camera_forward": "Kamera ileri",
  "optionsmenu_camera_invertpan": "Kaydırmayı ters çevir",
  "optionsmenu_camera_invertswivelpitch": "Döndürme açısını ters çevir",
  "optionsmenu_camera_keysensitivity": "Tuş Hassasiyeti",
  "optionsmenu_camera_left": "Kamera sol",
  "optionsmenu_camera_mousesensitivity": "Fare Hassasiyeti",
  "optionsmenu_camera_pan": "Kamera kaydırma",
  "optionsmenu_camera_right": "Kamera sağ",
  "optionsmenu_camera_speed": "Kamera hızı",
  "optionsmenu_camera_speed_fast": "Hızlı",
  "optionsmenu_camera_speed_medium": "Orta",
  "optionsmenu_camera_speed_slow": "Yavaş",
  "optionsmenu_camera_up": "Kamera yukarı",
  "optionsmenu_camera_wheelsensitivity": "Tekerlek Hassasiyeti",
  "optionsmenu_cameratype": "Tür",
  "optionsmenu_cameratype_advanced": "Gelişmiş",
  "optionsmenu_cameratype_debug": "Debug",
  "optionsmenu_cameratype_freelock": "Freelook",
  "optionsmenu_cameratype_normal": "Normal",
  "optionsmenu_cancel": "İptal",
  "optionsmenu_cannotchangesettingbecauseofscenarioparameter": "Bu senaryoda değiştirilemez",
  "optionsmenu_challengedifficulty_desc": "Meydan okuma parkınızın zorluğunu ayarlayın.",
  "optionsmenu_challengesettings": "Meydan Okuma Ayarları",
  "optionsmenu_coastersettings": "Hız Treni Ayarları",
  "optionsmenu_collaborate": "İş Birliği Yap",
  "optionsmenu_collisions": "Çarpışmaları Devre Dışı Bırak",
  "optionsmenu_color_blue": "Mavi",
  "optionsmenu_color_darkblue": "Koyu mavi",
  "optionsmenu_color_darkgreen": "Koyu yeşil",
  "optionsmenu_color_green": "Yeşil",
  "optionsmenu_color_lightblue": "Açık mavi",
  "optionsmenu_color_orange": "Turuncu",
  "optionsmenu_color_pink": "Pembe",
  "optionsmenu_color_purple": "Mor",
  "optionsmenu_color_red": "Kırmızı",
  "optionsmenu_colorpickerpreview": "Önizleme",
  "optionsmenu_colorpickertitle": "Arayüz Rengi",
  "optionsmenu_colourblindtheme_default": "Varsayılan",
  "optionsmenu_colourblindtheme_deuteranopia": "Deuteranopia",
  "optionsmenu_colourblindtheme_protanopia": "Protanopia",
  "optionsmenu_colourblindtheme_tritanopia": "Tritanopia",
  "optionsmenu_complexityafterfirstalert": "İlk uyarıdan sonra",
  "optionsmenu_complexityalways": "Her zaman",
  "optionsmenu_complexityfirstappearat": "İlk görünme zamanı",
  "optionsmenu_complexitynever": "Hiçbir zaman",
  "optionsmenu_complexityreappearevery": "Her şu aralıkta yeniden göster",
  "optionsmenu_complexityremainonscreen": "Ekranda kalsın",
  "optionsmenu_controls": "Kontroller",
  "optionsmenu_controls_building_edit": "Yapı Düzenleme Modu",
  "optionsmenu_controls_building_edit_command_01": "Parça Yerleştir\nParça Seç\nBaşka Bir Yapı Seç",
  "optionsmenu_controls_building_edit_command_02": "Yerleştirmeyi İptal Et\nİmleç altındaki Parçayı Sil",
  "optionsmenu_controls_building_edit_command_03": "Birden Fazla Parça Seç",
  "optionsmenu_controls_building_edit_command_04": "Döndür (Ekler ve Dekorlar)",
  "optionsmenu_controls_building_edit_command_05": "90 Derece Döndür",
  "optionsmenu_controls_building_edit_command_06": "Gelişmiş Taşı / Döndür / Ölçekle'yi Aç/Kapat\n(Ekler ve Dekorlar)",
  "optionsmenu_controls_building_edit_command_07": "Dikey Yüksekliği Ayarla",
  "optionsmenu_controls_building_edit_command_08": "Dikey Yüksekliği Sıfırla",
  "optionsmenu_controls_building_edit_command_09": "Yüzey Eksenlerine Kilitle",
  "optionsmenu_controls_building_edit_command_10": "Eki / Dekoru Duvar Parçası Ortasına Yapıştır",
  "optionsmenu_controls_building_edit_command_11": "Açı Yapışmasını Aç / Kapat",
  "optionsmenu_controls_building_edit_command_12": "Yüzeye Hizalamayı Aç / Kapat",
  "optionsmenu_controls_building_edit_command_13": "Araziyi Düzleştirmeyi Aç / Kapat",
  "optionsmenu_controls_building_edit_command_deselect": "Parça Seçimini Kaldır",
  "optionsmenu_controls_camera_fastmovementfreelook": "Hızlı Hareket (Freelook Kamera)",
  "optionsmenu_controls_camera_reset": "Kamerayı Sıfırla",
  "optionsmenu_controls_cameramisc": "Diğer Kamera Kontrolleri",
  "optionsmenu_controls_cameramisc_command_01": "Eğlence Kamerası Önceki",
  "optionsmenu_controls_cameramisc_command_02": "Eğlence Kamerası Sonraki",
  "optionsmenu_controls_cameramisc_command_03": "Güvenlik Kamerası Önceki",
  "optionsmenu_controls_cameramisc_command_04": "Güvenlik Kamerası Sonraki",
  "optionsmenu_controls_cameramisc_command_05": "Güvenlik Kamerası Görüntüsünü Aç/Kapat",
  "optionsmenu_controls_camerapan": "Kamera Kaydırma",
  "optionsmenu_controls_cameraviews": "Kamera Görünüm Modları",
  "optionsmenu_controls_coaster_edit": "Hız Treni / Akarsu Yolu Düzenleme Modu",
  "optionsmenu_controls_coaster_edit_additivetrackselection": "Ek Ray Seçimi",
  "optionsmenu_controls_coaster_edit_command_01": "Tutamaçları kullan",
  "optionsmenu_controls_coaster_edit_command_02": "Ray Parçası Yerleştir",
  "optionsmenu_controls_coaster_edit_command_03": "Ray Parçasını Sil",
  "optionsmenu_controls_coaster_edit_command_04": "Ray Parçası Seç",
  "optionsmenu_controls_coaster_edit_command_05": "İptal / Kapat",
  "optionsmenu_controls_coaster_edit_command_06": "Açı Yapışmasını Aç / Kapat",
  "optionsmenu_controls_coaster_edit_command_07": "Araziyi Düzleştirmeyi Aç / Kapat",
  "optionsmenu_controls_coaster_edit_command_08": "Testi Başlat/Durdur",
  "optionsmenu_controls_coaster_edit_command_09": "Ray Parçasını Döndür",
  "optionsmenu_controls_coaster_edit_command_10": "Ray Parçasını Ölçekle",
  "optionsmenu_controls_coaster_edit_command_11": "Yumuşat",
  "optionsmenu_controls_coaster_edit_input_04": "[MouseLeft] Yerleştirilmiş Parça üzerinde",
  "optionsmenu_controls_coaster_edit_toggleentrancetype": "Kapı / Merdiven Girişini Aç/Kapat (Yalnızca Akarsu Yolları)",
  "optionsmenu_controls_coaster_edit_togglefalloff": "Merkez / Eşit Azalmayı Aç/Kapat",
  "optionsmenu_controls_coaster_edit_togglemovement": "Dünya / Göreli Hareketi Aç/Kapat",
  "optionsmenu_controls_collapse": "Bölümü daralt",
  "optionsmenu_controls_controllercamera": "Denetleyici Tabanlı Kamera",
  "optionsmenu_controls_controllercamera_command_01": "Kamera Sola",
  "optionsmenu_controls_controllercamera_command_02": "Kamera Sağa",
  "optionsmenu_controls_controllercamera_command_03": "Kamera İleri",
  "optionsmenu_controls_controllercamera_command_04": "Kamera Geri",
  "optionsmenu_controls_controllercamera_command_05": "Kamerayı Yukarı Kaldır",
  "optionsmenu_controls_controllercamera_command_06": "Kamerayı Aşağı İndir",
  "optionsmenu_controls_controllercamera_command_07": "Sola Döndür",
  "optionsmenu_controls_controllercamera_command_08": "Sağa Döndür",
  "optionsmenu_controls_controllercamera_command_09": "Yukarı Bak",
  "optionsmenu_controls_controllercamera_command_10": "Aşağı Bak",
  "optionsmenu_controls_demolishbrush": "Yıkım Modu",
  "optionsmenu_controls_demolishbrush_demolish": "Yık",
  "optionsmenu_controls_demolishbrush_raiselower": "Fırçayı Yükselt / Alçalt",
  "optionsmenu_controls_demolishbrush_resetheight": "Fırça Yüksekliğini Sıfırla",
  "optionsmenu_controls_demolishbrush_toggleallfilters": "Tüm Filtreleri Aç/Kapat",
  "optionsmenu_controls_demolishbrush_togglepaths": "Yolları Aç/Kapat",
  "optionsmenu_controls_demolishbrush_togglescenery": "Dekorları Aç/Kapat",
  "optionsmenu_controls_expand": "Bölümü genişlet",
  "optionsmenu_controls_gamecamera_down": "Kamerayı Aşağı Kaydır (Yalnızca Freelook)",
  "optionsmenu_controls_gamecamera_up": "Kamerayı Yukarı Kaydır (Yalnızca Freelook)",
  "optionsmenu_controls_gamepad": "Kontroller",
  "optionsmenu_controls_gamepad_cameraheader": "Kamera ayarları",
  "optionsmenu_controls_gamepad_header": "Denetleyici Ayarları",
  "optionsmenu_controls_gamepad_leftsticksensitivity": "Sol Çubuk Hassasiyeti",
  "optionsmenu_controls_gamepad_rightsticksensitivity": "Sağ Çubuk Hassasiyeti",
  "optionsmenu_controls_gamepad_screen": "Kontroller",
  "optionsmenu_controls_gamepad_vibrate": "Titreşim",
  "optionsmenu_controls_gamepad_vibrateheader": "Titreşim ayarları",
  "optionsmenu_controls_gamepad_view": "Görünüm",
  "optionsmenu_controls_gamepad_view_desc": "Görünüm Kontrolleri",
  "optionsmenu_controls_general": "Genel Kısayollar",
  "optionsmenu_controls_general_advancedmove": "Gelişmiş Taşı / Döndür / Ölçekle Seçimi",
  "optionsmenu_controls_general_command_01": "Kontrol Yardımı (Göster / Gizle)",
  "optionsmenu_controls_general_command_02a": "Kamerayı İleri Kaydır",
  "optionsmenu_controls_general_command_02b": "Kamerayı Geri Kaydır",
  "optionsmenu_controls_general_command_02c": "Kamerayı Sola Kaydır",
  "optionsmenu_controls_general_command_02d": "Kamerayı Sağa Kaydır",
  "optionsmenu_controls_general_command_03a": "Kamerayı Sola Döndür",
  "optionsmenu_controls_general_command_03b": "Kamerayı Sağa Döndür",
  "optionsmenu_controls_general_command_04a": "Kamerayı Yakınlaştır",
  "optionsmenu_controls_general_command_04b": "Kamerayı Uzaklaştır",
  "optionsmenu_controls_general_command_05": "Freelook Kamerayı Açık / Kapalı",
  "optionsmenu_controls_general_command_06": "Freelook Kamera Hızını Artır",
  "optionsmenu_controls_general_command_07": "Yerleştirmeyi İptal Et, Tarayıcıyı Kapat, Nesne Seçimini Kaldır, Seçenekler Menüsünü Aç",
  "optionsmenu_controls_general_command_08": "Seçili Nesneyi Sil",
  "optionsmenu_controls_general_command_09": "Simülasyon Hızını Değiştir",
  "optionsmenu_controls_general_command_10": "Simülasyonu Duraklat",
  "optionsmenu_controls_general_command_11": "Geri Al",
  "optionsmenu_controls_general_command_12": "Yeniden Yap",
  "optionsmenu_controls_general_command_13": "Nesneyi / Binayı Çoğalt",
  "optionsmenu_controls_general_command_13b": "Çoğalt ve Gelişmiş Taşı / Döndür",
  "optionsmenu_controls_general_command_14": "Seçimi Taşı",
  "optionsmenu_controls_general_command_15": "Binayı Düzenle",
  "optionsmenu_controls_general_command_16": "Kamerayı Odakla",
  "optionsmenu_controls_general_command_17": "Kamera Feneri",
  "optionsmenu_controls_general_command_quickload": "Yükleme Menüsünü Aç",
  "optionsmenu_controls_general_command_quicksave": "Kaydetme Menüsünü Aç",
  "optionsmenu_controls_general_heatmaps": "Isı Haritalarını Göster",
  "optionsmenu_controls_general_radialmenu": "Radyal Menüyü Göster",
  "optionsmenu_controls_general_timeofday": "Günün Saati Penceresini Göster",
  "optionsmenu_controls_general_weatherreport": "Hava Durumu Raporunu Göster",
  "optionsmenu_controls_hudnavigation": "HUD Navigasyonu",
  "optionsmenu_controls_hudnavigation_toggleheatmaps": "Isı Haritalarını Aç/Kapat",
  "optionsmenu_controls_hudnavigation_togglemanagement": "Yönetimi Aç/Kapat",
  "optionsmenu_controls_hudnavigation_togglenotifications": "Bildirimleri Aç/Kapat",
  "optionsmenu_controls_hudnavigation_toggleobjectives": "Hedefler Panelini Aç/Kapat",
  "optionsmenu_controls_hudnavigation_toggleparkexpansion": "Park Genişletmeyi Aç/Kapat",
  "optionsmenu_controls_menu": "Menü Kısayolları",
  "optionsmenu_controls_menu_command_blueprints": "Taslaklarımı Aç",
  "optionsmenu_controls_menu_command_building": "Binaları Aç",
  "optionsmenu_controls_menu_command_coasters": "Hız Trenlerini Aç",
  "optionsmenu_controls_menu_command_multiselect": "Çoklu Seçimi Aç",
  "optionsmenu_controls_menu_command_parkmanagement": "Park Yönetimini Aç",
  "optionsmenu_controls_menu_command_paths": "Yolları Aç",
  "optionsmenu_controls_menu_command_rides": "Eğlenceleri Aç",
  "optionsmenu_controls_menu_command_scenery": "Dekoru Aç",
  "optionsmenu_controls_menu_command_shops": "Dükkanları ve Tesisleri Aç",
  "optionsmenu_controls_menu_command_terrain": "Araziyi Aç",
  "optionsmenu_controls_menu_command_trackrides": "Ray Eğlencelerini Aç",
  "optionsmenu_controls_menunavigation": "Menü Navigasyonu",
  "optionsmenu_controls_menunavigation_copystaffschedule": "Kopyala (Personel Programı)",
  "optionsmenu_controls_menunavigation_down": "Aşağı",
  "optionsmenu_controls_menunavigation_left": "Sol",
  "optionsmenu_controls_menunavigation_pastestaffschedule": "Yapıştır (Personel Programı)",
  "optionsmenu_controls_menunavigation_right": "Sağ",
  "optionsmenu_controls_menunavigation_up": "Yukarı",
  "optionsmenu_controls_menunavigation_uploadblueprintbrowser": "Taslak Yükle (Tarayıcı)",
  "optionsmenu_controls_mouse": "Fare Kontrolleri",
  "optionsmenu_controls_mouse_command_01": "İmleci Hareket Ettir",
  "optionsmenu_controls_mouse_command_02": "Nesne Seç\nNesne Yerleştir",
  "optionsmenu_controls_mouse_command_03": "Kamerayı Kaydır\nİptal Et / Kapat",
  "optionsmenu_controls_mouse_command_04": "Kamerayı Eğ / Döndür",
  "optionsmenu_controls_mouse_command_05": "Kamerayı Yakınlaştır",
  "optionsmenu_controls_mouse_input_05": "[MouseMiddle](Scroll)",
  "optionsmenu_controls_mouse_uicontextmenu": "Bağlam Menüsünü Aç",
  "optionsmenu_controls_mouse_uiselect": "Düğmeyi Etkinleştir",
  "optionsmenu_controls_mouseandkeyboard": "Fare ve klavye kontrolleri",
  "optionsmenu_controls_mouseandkeyboard_cameraheader": "Fare ve klavye ayarları - kamera",
  "optionsmenu_controls_mouseandkeyboard_header": "Fare ve Klavye Ayarları",
  "optionsmenu_controls_mouseandkeyboard_screen": "Fare ve Klavye Kontrolleri",
  "optionsmenu_controls_mouseandkeyboard_view": "Görüntüle",
  "optionsmenu_controls_mouseandkeyboard_view_desc": "Fare ve Klavye Kontrollerini Görüntüle",
  "optionsmenu_controls_multiselect_confirm": "Seçimi Onayla",
  "optionsmenu_controls_multiselect_select": "Parçaları Seç",
  "optionsmenu_controls_multiselectmode": "Çoklu Seçim Modu",
  "optionsmenu_controls_noclip": "No Clip",
  "optionsmenu_controls_object_placement": "Nesne Yerleştirme Kontrolleri",
  "optionsmenu_controls_object_placement_command_01": "Nesne Yerleştir",
  "optionsmenu_controls_object_placement_command_02": "Yerleştirmeyi İptal Et",
  "optionsmenu_controls_object_placement_command_03": "Döndür",
  "optionsmenu_controls_object_placement_command_04": "90 Derece Döndür",
  "optionsmenu_controls_object_placement_command_05": "Dikey Yüksekliği Ayarla",
  "optionsmenu_controls_object_placement_command_06": "Dikey Yüksekliği Sıfırla",
  "optionsmenu_controls_object_placement_command_07": "Yüzey Eksenlerine Kilitle",
  "optionsmenu_controls_object_placement_command_08": "Açı Yakalamayı Açık / Kapalı",
  "optionsmenu_controls_object_placement_command_09": "Yüzeye Hizalamayı Açık / Kapalı",
  "optionsmenu_controls_object_placement_command_10": "Araziyi Düzleştir Açık / Kapalı",
  "optionsmenu_controls_object_placement_command_11": "Yüzeye Yapışmayı Açık / Kapalı",
  "optionsmenu_controls_object_placement_command_12": "Simetri Türünü Değiştir",
  "optionsmenu_controls_object_placement_command_13": "Simetri Sayısını Artır",
  "optionsmenu_controls_object_placement_command_14": "Simetri Sayısını Azalt",
  "optionsmenu_controls_object_placement_command_15": "İkizlemeyi Değiştir",
  "optionsmenu_controls_object_placement_cyclenextoption": "Sonraki Seçeneğe Geç",
  "optionsmenu_controls_object_placement_cycleprevoption": "Önceki Seçeneğe Geç",
  "optionsmenu_controls_object_placement_toggleboundingboxplacement": "Sınır Kutusu Yerleştirmeyi Aç/Kapat",
  "optionsmenu_controls_path_edit": "Yol / Havuz Düzenleme Modu",
  "optionsmenu_controls_path_edit_command_01": "Yol Yerleştir",
  "optionsmenu_controls_path_edit_command_02": "Yolu Sil",
  "optionsmenu_controls_path_edit_command_03": "Yolu Yükselt / Alçalt",
  "optionsmenu_controls_path_edit_command_04": "Yolu Yükselt (yerleştirmeden)",
  "optionsmenu_controls_path_edit_command_05": "Yolu Alçalt (yerleştirmeden)",
  "optionsmenu_controls_path_edit_command_06": "Kavşak Açısını Döndür",
  "optionsmenu_controls_path_edit_command_07": "Dar Açılı Birleştirme",
  "optionsmenu_controls_path_edit_command_08": "Dikey Yüksekliği Ayarla",
  "optionsmenu_controls_path_edit_command_09": "Dikey Yüksekliği Sıfırla",
  "optionsmenu_controls_path_edit_command_10": "Yol Birleştirmeyi Devre Dışı Bırak",
  "optionsmenu_controls_path_edit_command_11": "Açı Yakalamayı Açık / Kapalı",
  "optionsmenu_controls_path_edit_command_12": "Yol Uzunluğunu Azalt",
  "optionsmenu_controls_path_edit_command_13": "Yol Uzunluğunu Artır",
  "optionsmenu_controls_path_edit_command_14": "Yol Genişliğini Azalt",
  "optionsmenu_controls_path_edit_command_15": "Yol Genişliğini Artır",
  "optionsmenu_controls_path_edit_command_16": "Araziyi Düzleştir",
  "optionsmenu_controls_path_edit_command_17": "Yol Silmeyi Açık / Kapalı",
  "optionsmenu_controls_path_edit_command_18": "Havuz Derinliğini Değiştir",
  "optionsmenu_controls_path_edit_command_19": "Döndürme Yakalamayı Aç/Kapat",
  "optionsmenu_controls_path_edit_command_20": "Açı Yakalamayı Aç/Kapat",
  "optionsmenu_controls_path_edit_command_21": "Çizgi Genişliğini Azalt",
  "optionsmenu_controls_path_edit_command_22": "Çizgi Genişliğini Artır",
  "optionsmenu_controls_path_edit_command_23": "Arazi Stilini Değiştir",
  "optionsmenu_controls_path_edit_command_24": "Kenar Türünü Değiştir",
  "optionsmenu_controls_path_edit_command_25": "Çizgi Stilini Değiştir",
  "optionsmenu_controls_path_edit_input_03": "{#LogicalButton.MouseLeft#} on Path preview, then [MouseMoveV]",
  "optionsmenu_controls_path_edit_input_06": "{#LogicalButton.Editors_PathYJunctionModifier#} on Junction preview, then [MouseMove]",
  "optionsmenu_controls_path_edit_input_07": "{#LogicalButton.Editors_PathYJunctionModifier#}, when path preview joins to a path.",
  "optionsmenu_controls_path_edit_input_10": "{#LogicalButton.Editors_NoJoinModifier#} during Path placement",
  "optionsmenu_controls_path_edit_input_17": "{#LogicalButton.Editors_PathDeleteModifier#} hold while over path.",
  "optionsmenu_controls_rebind_button": "Yeniden Ata",
  "optionsmenu_controls_rebind_inprogress": "Tuş Yeniden Atama Devam Ediyor",
  "optionsmenu_controls_rebind_inprogress_label": "Atamak istediğiniz tuşa basıp bırakın.\n{Value:int} saniye içinde geri dönülüyor...",
  "optionsmenu_controls_rebind_resetall": "Atamaları varsayılana sıfırla",
  "optionsmenu_controls_rebind_value": "Eksene yeniden ata",
  "optionsmenu_controls_scenerybrush": "Dekor Fırçası Modu",
  "optionsmenu_controls_scenerybrush_changetype": "Fırça Türünü Değiştir",
  "optionsmenu_controls_scenerybrush_delete": "Dekoru Sil",
  "optionsmenu_controls_scenerybrush_freeze": "Fırçayı Yerinde Kilitle",
  "optionsmenu_controls_scenerybrush_place": "Dekor Yerleştir",
  "optionsmenu_controls_showhidegui": "Arayüzü Göster / Gizle",
  "optionsmenu_controls_terrain_edit": "Arazi Düzenleme Modu",
  "optionsmenu_controls_terrain_edit_command_01": "Fırçayı Uygula",
  "optionsmenu_controls_terrain_edit_command_02": "Ters Fırçayı Uygula (İt / Çek Fırçaları)",
  "optionsmenu_controls_terrain_edit_command_03": "Fırça Yoğunluğunu Azalt",
  "optionsmenu_controls_terrain_edit_command_04": "Fırça Yoğunluğunu Artır",
  "optionsmenu_controls_terrain_edit_command_05": "Fırça Boyutunu Azalt",
  "optionsmenu_controls_terrain_edit_command_06": "Fırça Boyutunu Artır",
  "optionsmenu_controls_terrain_edit_command_07": "Fırça Sertliğini Azalt",
  "optionsmenu_controls_terrain_edit_command_08": "Fırça Sertliğini Artır",
  "optionsmenu_controls_text": "{ControlText}",
  "optionsmenu_controls_unbind_button": "Sıfırla",
  "optionsmenu_controls_unbind_value": "Sıfırla",
  "optionsmenu_controls_valuerebind_inprogress": "Eksen Yeniden Atama Devam Ediyor",
  "optionsmenu_controls_valuerebind_inprogress_label": "Atamak istediğiniz yönde Sol veya Sağ Çubuğa ya da tetikleyiciye basın.\n{Value:int} saniye içinde geri dönülüyor...",
  "optionsmenu_controls_visitor": "Ziyaretçi Kamera Modu",
  "optionsmenu_controls_visitor_choosestart": "Başlangıç Konumunu Seç",
  "optionsmenu_controls_visitor_crouch": "Çömeleyi Aç/Kapat",
  "optionsmenu_controls_visitor_enterplacement": "Ziyaretçi Kamera Yerleştirme Moduna Gir",
  "optionsmenu_controls_visitor_interact": "Etkileş",
  "optionsmenu_controls_visitor_jump": "Zıpla",
  "optionsmenu_controls_visitor_walk": "Yürüyüşü Aç/Kapat",
  "optionsmenu_controlsglobalsettings": "Genel Ayarlar",
  "optionsmenu_controlsglobalverticalgrid": "Genel Dikey Yakalama",
  "optionsmenu_controlsglobalverticalgridhint": "Binalar ve eğlenceler, dikey yükseklikte 1 metrelik artışlarla hareket etmekle sınırlıdır. Bu özellik, bina, yol ve hız treni istasyonlarını hizalamayı kolaylaştırır.",
  "optionsmenu_controlsheading": "Kontroller",
  "optionsmenu_depthoffield_desc": "Alan derinliğini açın veya kapatın. Alan derinliği açıkken arka planlar daha keskin görünür. Kapalıyken arka planlar bulanıklaşır; bu, bir kameranın ön plan odağını simüle eder.",
  "optionsmenu_device_firstappear_desc": "Park Karmaşıklık Ölçer bildiriminin, karmaşıklık sınırına yaklaşırken ilk kez ne zaman görüneceğini ayarlayın.",
  "optionsmenu_device_firstappear_title": "Park Karmaşıklık Ölçer İlk Bildirim",
  "optionsmenu_device_reappear_desc": "Park Karmaşıklık Ölçer bildirimlerinin ne sıklıkta görüneceğini ayarlayın.",
  "optionsmenu_device_reappear_title": "Park Karmaşıklık Ölçer Bildirim Sıklığı",
  "optionsmenu_device_remain_desc": "Park Karmaşıklık Ölçer'in kalıcı olarak nasıl gösterileceğini ayarlayın.",
  "optionsmenu_device_remain_title": "Park Karmaşıklık Ölçer Görünümü",
  "optionsmenu_deviceperformance_desc": "Park Karmaşıklık Ölçer'i ne zaman ve nasıl göreceğinizi ayarlayın.",
  "optionsmenu_deviceperformance_title": "Park Karmaşıklık Ölçer",
  "optionsmenu_difficultysettings": "Zorluk Ayarları",
  "optionsmenu_disablehints": "Tüm İpuçlarını Devre Dışı Bırak",
  "optionsmenu_display_desc": "Oyunun hangi ekran ya da monitörde görüntüleneceğini seçin.",
  "optionsmenu_display_header": "Görsel Ayarlar",
  "optionsmenu_displaycomplexity_header": "Park Karmaşıklık Ölçer",
  "optionsmenu_displaycomplexityalertsettings": "Uyarı Ayarları",
  "optionsmenu_displaycomplexitydescr": "Park Karmaşıklık Ölçer, parkınıza yeni şeyler ekledikçe artar. Karmaşıklık sınırına ulaştığınızda artık hiçbir şey ekleyemezsiniz.",
  "optionsmenu_displaycomplexitydescr_nextgen": "Sayaç \"geriye dönük uyumsuz bölüm\"e ulaştığında, parkınız yalnızca yeni nesil konsollar üzerinde açılabilecek ve önceki nesil konsollar artık desteklenmeyecek.",
  "optionsmenu_displaycomplexityhighcomplexity": "Yüksek Kapasite",
  "optionsmenu_displaycomplexitynotbackwardscompatible": "Geriye dönük uyumsuz",
  "optionsmenu_displaycomplexitytitle": "Park Karmaşıklık Ölçer",
  "optionsmenu_displaysettingsdescription": "Görüntü Seçenekleri",
  "optionsmenu_displaysettingstitle": "Görüntü Ayarları",
  "optionsmenu_effect_desc": "Bazı yüzeylerdeki malzemelerin kalitesini seçin. Daha yüksek ayarlar bazı efektlerin kalitesini artırır, ancak performans maliyeti de yükselir.",
  "optionsmenu_effectpreset_desc": "Uygulanacak bir grafik ön ayarı seçin.",
  "optionsmenu_enablenewsfeed": "Oyun Açılışında Haberleri Göster",
  "optionsmenu_envcapture_desc": "Dinamik ortam haritasını açın veya kapatın. Dinamik ortam haritalama, ışık kırılımı yanılsaması oluşturur.",
  "optionsmenu_exit": "Ana Menüye Çık",
  "optionsmenu_exit_career": "Kariyer Menüsüne Çık",
  "optionsmenu_exit_franchise": "Franchise Menüsüne Çık",
  "optionsmenu_exitdetails": "Oyundan çıkın ve ana menüye dönün.",
  "optionsmenu_facilitycleanliness": "Tesis Temizliği",
  "optionsmenu_facilitycleanliness_desc": "Tesis Temizliğini etkinleştirin. Oteller ve restoranlar, kullanım sonrasında periyodik temizlik gerektirecektir.",
  "optionsmenu_facilitycleanliness_title": "Tesis Temizliği",
  "optionsmenu_firsttimeguidancedesc": "Öğretici sırasında ek Yardım Ekranlarının tetiklenip tetiklenmeyeceğini değiştirir.",
  "optionsmenu_firsttimeguidancelabel": "İlk Kullanım Rehberi",
  "optionsmenu_game": "Oyun",
  "optionsmenu_game_advancedmoveaverage_desc": "Gelişmiş Taşı/Döndür aracının, seçili parçaların ortalama yönelim ve konumunu kullanmasını sağlar. Tüm nesneler aynı yön ve açıda hizalandığında bu özellik işe yarar.",
  "optionsmenu_game_advancedmoveaverage_title": "Gelişmiş Taşıma'da Ortalama Yönelim",
  "optionsmenu_game_coastercollision_desc": "Hız trenlerinin mevcut dekor veya arazinin içine yerleştirilmesini engellemek için Açık yapın.",
  "optionsmenu_game_coastercollision_title": "Hız Treni Çarpışması",
  "optionsmenu_game_coasterfrictioncontrols_desc": "Bilgi panelinde Hız Treni Sürtünme kontrolünü gösterin.",
  "optionsmenu_game_coasterfrictioncontrols_title": "Hız Treni Sürtünme Kontrolleri",
  "optionsmenu_game_coastergoingofftrack": "Düzenleme Sırasında Hız Treninin Raydan Çıkması",
  "optionsmenu_game_coastergoingofftrack_desc": "Düzenleme sırasında hız trenlerinin raydan çıkmasına izin verir.",
  "optionsmenu_game_coastergoingofftrack_title": "Düzenleme Sırasında Hız Treninin Raydan Çıkması",
  "optionsmenu_game_coastersupportsonpaths_desc": "Varsayılan olarak, hız treni destekleri yollarda görünmez.\n\nBu ayar etkinleştirilirse, hız treni destekleri yollarda görünür. Bu ayardan bağımsız olarak destekler, Ray Düzenleme modunda tek tek ray parçaları için hâlâ açılıp kapatılabilir. \n\nZiyaretçiler, yol üzerindeki desteklerden geçerek yürür.",
  "optionsmenu_game_coastersupportsonpaths_title": "Yollarda Hız Treni Desteğine İzin Ver",
  "optionsmenu_game_crashtestdummies_desc": "Test edilmekte olan eğlencelerde çarpışma testi mankenlerini tercihinize göre etkinleştirin veya devre dışı bırakın. Bu, test sonuçlarını etkilemez.",
  "optionsmenu_game_crashtestdummies_title": "Çarpışma Testi Mankenleri",
  "optionsmenu_game_distanceunit_desc": "Mesafeler gösterilirken hangi birimlerin kullanılacağını seçin.",
  "optionsmenu_game_distanceunit_title": "Mesafe Birimi",
  "optionsmenu_game_interchangeablecoastercars_desc": "Bazı hız treni arabalarının, farklı bir ray kullansalar bile değiştirilmesine izin verir. Görsel çakışmalara, araba ağırlığındaki değişikliklere ve ray sesinin özgünlüğünün azalmasına yol açabilir.",
  "optionsmenu_game_interchangeablecoastercars_title": "Değiştirilebilir Hız Treni Arabalarına İzin Ver",
  "optionsmenu_game_reputation_desc": "İtibar, eğlencelerinizin Prestijini zamanla etkiler. Bir eğlencenin itibarı ne kadar yüksekse, o kadar fazla Prestij kazanır.",
  "optionsmenu_game_reputation_title": "İtibarı Etkinleştir",
  "optionsmenu_game_ridecollision_desc": "Eğlencelerin mevcut dekor veya arazinin içine yerleştirilmesini engellemek için Açık yapın.",
  "optionsmenu_game_ridecollision_title": "Eğlence Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_game_scenerycollision_desc": "Eğlencelerin dekor yerleştirmeyi engellemesi için Açık yapın.",
  "optionsmenu_game_scenerycollision_title": "Dekor Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_game_speedunit_desc": "Hızlar gösterilirken hangi birimlerin kullanılacağını seçin.",
  "optionsmenu_game_speedunit_title": "Hız Birimi",
  "optionsmenu_game_temperatureunit_desc": "Sıcaklıklar gösterilirken hangi birimlerin kullanılacağını seçin.",
  "optionsmenu_game_temperatureunit_title": "Sıcaklık Birimi",
  "optionsmenu_game_terraincollision_desc": "Mevcut dekor veya raylar üzerinden arazi düzenlemeyi engellemek için Açık yapın.",
  "optionsmenu_game_terraincollision_title": "Arazi Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_game_toggleboundingbox_desc": "Birden fazla öğe yerleştirirken varsayılan hizalama stili olarak Sınır Kutusu kullanın.",
  "optionsmenu_game_toggleboundingbox_title": "Varsayılan Olarak Sınır Kutusu Hizalaması",
  "optionsmenu_gameglobalsettings": "Genel Oyun Ayarları",
  "optionsmenu_gamelocalparksettings": "Yerel Park Ayarları",
  "optionsmenu_gamemodes_careermode": "Kariyer Modu",
  "optionsmenu_gamemodes_defaultmode": "Varsayılan Mod",
  "optionsmenu_gamemodes_franchisemode": "Franchise Modu",
  "optionsmenu_gamemodes_hardmode": "Zor Mod",
  "optionsmenu_gamemodes_header": "Oyun Modu Ayarları",
  "optionsmenu_gamemodes_sandboxmode": "Sandbox Modu",
  "optionsmenu_gamemodes_selectdifficulty": "Zorluk Seç",
  "optionsmenu_gameoptions_desc": "Park oluşturma deneyiminizi geliştirmek için çeşitli seçenekleri ayarlayın.",
  "optionsmenu_gameoptions_header": "Oyun Seçenekleri",
  "optionsmenu_gameoptions_title": "Oyun Seçenekleri",
  "optionsmenu_gamepad_acceleration": "Hızlanma Rampası",
  "optionsmenu_gamepad_customgamepadremap": "Kontrolleri Değiştir",
  "optionsmenu_gamepad_customgamepadremap_desc": "Kontrolleri kendinize göre ayarlayın.",
  "optionsmenu_gamepad_customgamepadremap_title": "Kontrolleri Değiştir",
  "optionsmenu_gamepad_desc": "Oyun kumandası ayarlarınızı düzenleyin.",
  "optionsmenu_gamepad_invertxfree": "X Eksenini Tersine Çevir (Free Look)",
  "optionsmenu_gamepad_invertxfreelook_desc": "Free Look tarzı kameralarda X eksenini tersine çevirin.",
  "optionsmenu_gamepad_invertxfreelook_title": "X Eksenini Tersine Çevir (Free Look)",
  "optionsmenu_gamepad_invertxorbit": "X Eksenini Tersine Çevir (Yörünge)",
  "optionsmenu_gamepad_invertxorbit_desc": "Yörünge tarzı kameralarda X eksenini tersine çevirin.",
  "optionsmenu_gamepad_invertxorbit_title": "X Eksenini Tersine Çevir (Yörünge)",
  "optionsmenu_gamepad_invertyfree": "Y Eksenini Tersine Çevir (Free Look)",
  "optionsmenu_gamepad_invertyfreelook_desc": "Free Look tarzı kameralarda Y eksenini tersine çevirin.",
  "optionsmenu_gamepad_invertyfreelook_title": "Y Eksenini Tersine Çevir (Free Look)",
  "optionsmenu_gamepad_invertyorbit": "Y Eksenini Tersine Çevir (Yörünge)",
  "optionsmenu_gamepad_invertyorbit_desc": "Yörünge kameralarında Y eksenini ters çevirir.",
  "optionsmenu_gamepad_invertyorbit_title": "Y eksenini ters çevir (Yörünge)",
  "optionsmenu_gamepad_leftsticksensitivity_desc": "Sol çubuğun harekete ne kadar duyarlı olacağını ayarlamak için kaydırıcıyı kullanın.",
  "optionsmenu_gamepad_leftsticksensitivity_title": "Sol Çubuk Hassasiyeti",
  "optionsmenu_gamepad_noclip": "No Clip",
  "optionsmenu_gamepad_noclip_desc": "Parkta dolaşırken katı nesnelerden geçmek için No Clip'i açın.",
  "optionsmenu_gamepad_noclip_title": "No Clip",
  "optionsmenu_gamepad_remapbutton": "Değiştir",
  "optionsmenu_gamepad_rightsticksensitivity_desc": "Sağ çubuğun harekete ne kadar duyarlı olacağını ayarlamak için kaydırıcıyı kullanın.",
  "optionsmenu_gamepad_rightsticksensitivity_title": "Sağ Çubuk Hassasiyeti",
  "optionsmenu_gamepad_title": "Kumanda Ayarları",
  "optionsmenu_gamepad_zoomsensitivity_desc": "Kameranın yakınlaştırma ve uzaklaştırma hızını ayarlamak için kaydırıcıyı kullanın.",
  "optionsmenu_gamepad_zoomsensitivity_title": "Yakınlaştırma Hassasiyeti",
  "optionsmenu_gamepadmode_advanced": "Gelişmiş",
  "optionsmenu_gamepadmode_default": "Varsayılan",
  "optionsmenu_gamepadmode_simple": "Basit",
  "optionsmenu_gameplay": "Oynanış",
  "optionsmenu_gameplaysettings": "Oynanış Ayarları",
  "optionsmenu_geometric_desc": "Dünya ve nesneler üzerindeki geometrik detayların kalitesini seçin.",
  "optionsmenu_globalcrashtestdummiesenabled": "Çarpışma Testi Mankenleri",
  "optionsmenu_globaldisablecoasterobstruction": "Hız Treni Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_globaldisablerideobstruction": "Eğlence Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_globaldisablesceneryobstruction": "Dekor Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_globaldisableterrainobstruction": "Arazi Çarpışmasını Devre Dışı Bırak",
  "optionsmenu_globalenablecoastersupportsonpaths": "Yollarda Hız Treni Desteğine İzin Ver",
  "optionsmenu_globalframeratelock": "Kare Hızını Kilitle",
  "optionsmenu_globalframeratelockhint": "Kare hızını 30 fps'de sabitlemek için etkinleştirin",
  "optionsmenu_globalremovetracklimits": "Ray Sınırları",
  "optionsmenu_globalremovetracklimits_desc": "Çoğu hız treninde yatış ve eğim açısı sınırlarının kaldırılıp kaldırılmayacağını seçin.",
  "optionsmenu_globalremovetracklimits_title": "Ray Sınırları",
  "optionsmenu_globalridedecline": "İtibar",
  "optionsmenu_globalsecurityfeatures": "Güvenlik Özellikleri",
  "optionsmenu_globalsecurityfeatureshint": "Güvenlik özelliklerini etkinleştirin. Bazı senaryolar güvenlik gerektirir ve bu ayarı geçersiz kılar.",
  "optionsmenu_globalshowcoasterfrictionslider": "Hız Treni Sürtünme Kontrolleri",
  "optionsmenu_globalshowextrainterchangeabletrains": "Değiştirilebilir Hız Treni Vagonlarına İzin Ver",
  "optionsmenu_gotodisplaysetup": "Ekran Kurulumuna Git",
  "optionsmenu_graphics": "Grafik",
  "optionsmenu_guestlitter": "Ziyaretçi Çöpü",
  "optionsmenu_guestlitter_desc": "Ziyaretçilerin çöp bırakıp bırakamayacağını seçin.",
  "optionsmenu_guestlitter_title": "Ziyaretçi Çöpü",
  "optionsmenu_guestvomit": "Ziyaretçi Kusması",
  "optionsmenu_guestvomit_desc": "Bulantı hisseden ziyaretçilerin kusup kusmayacağını seçin.",
  "optionsmenu_guestvomit_title": "Ziyaretçi Kusması",
  "optionsmenu_hdr_brightness_details": "Logo artık görünmeyene kadar HDR parlaklığını ayarlayın.",
  "optionsmenu_hdrbrightness": "HDR Parlaklığı",
  "optionsmenu_heatmapcolourblind": "Renk Körlüğü - Isı Haritası Kontrastı",
  "optionsmenu_help": "Yardım",
  "optionsmenu_helpdetails": "Oynamayla ilgili ipuçlarını ve püf noktalarını görüntüleyin.",
  "optionsmenu_hideplayername": "Oyuncu adını gizle (yeniden başlatma gerektirir)",
  "optionsmenu_hints": "Ekran Kontrollerini Göster",
  "optionsmenu_interface": "Arayüz",
  "optionsmenu_interfaceautoscale": "Arayüz Otomatik Ölçekleme",
  "optionsmenu_interfaceautoscale_tooltip": "Arayüzün ne kadar ölçekleneceğini kendiniz belirlemek için otomatik ölçeklemeyi kapatın.",
  "optionsmenu_interfacedistancefeet": "Feet (ft)",
  "optionsmenu_interfacedistancekilometres": "Kilometre (km)",
  "optionsmenu_interfacedistancemetres": "Metre (m)",
  "optionsmenu_interfacedistancemiles": "Mil (mi)",
  "optionsmenu_interfacedistanceunit": "Mesafe Birimi",
  "optionsmenu_interfacedistanceyards": "Yarda (yd)",
  "optionsmenu_interfacehighlightobjectsonhover": "Üzerine gelindiğinde nesneleri vurgula",
  "optionsmenu_interfacescale_tooltip": "Yüzde 100'ün üzerinde ölçekleme yalnızca yüksek çözünürlüklü ekranlar (1440p / 4K) için önerilir. Düşük çözünürlüklerde arayüz sorunlarına yol açabilir.",
  "optionsmenu_interfacescaletitle": "Arayüz Ölçeği",
  "optionsmenu_interfacespeedfs": "Feet/saniye (ft/s)",
  "optionsmenu_interfacespeedkph": "Kilometre/saat (km/s)",
  "optionsmenu_interfacespeedmph": "Mil/saat (mph)",
  "optionsmenu_interfacespeedms": "Metre/saniye (m/s)",
  "optionsmenu_interfacespeedunit": "Hız Birimi",
  "optionsmenu_interfacetemperaturecelsius": "Celsius (°C)",
  "optionsmenu_interfacetemperaturefahrenheit": "Fahrenheit (°F)",
  "optionsmenu_interfacetemperatureunit": "Sıcaklık Birimi",
  "optionsmenu_interfaceunitslabel": "Birimler",
  "optionsmenu_keybindings": "Tuş Atamaları",
  "optionsmenu_lensflare_desc": "Ne kadar lens parlaması göreceğinizi seçin. Lens parlaması, ışığın kamera merceği içinde kırılma etkisini simüle eder.",
  "optionsmenu_load": "Park Yükle",
  "optionsmenu_loaddetails": "Kaydedilmiş bir park yükleyin.",
  "optionsmenu_loadmenu_autosavename": "{Name} (Otomatik Kayıt {Count:int})",
  "optionsmenu_loadmenu_autosavenumber": "Otomatik Kayıt {Count:int}",
  "optionsmenu_loadmenu_loaddate": "{TimeString} - {DateString}",
  "optionsmenu_loadmenu_savename": "{Name}",
  "optionsmenu_loadprompt_confirmcancel": "İptal",
  "optionsmenu_loadprompt_confirmheader": "Kaydedilmiş Parkı Yükle",
  "optionsmenu_loadprompt_confirmlabel": "'{Name}' kaydı yüklensin mi?\nMevcut parkınızdaki kaydedilmemiş değişiklikler kaybolacak.",
  "optionsmenu_loadprompt_confirmok": "Tamam",
  "optionsmenu_localparksettingsnotinpark": "Bu ayar yalnızca park içinde geçerlidir",
  "optionsmenu_localparkstaffenergyfeatures": "Personel Yönetimi Özellikleri",
  "optionsmenu_localparkstaffenergyfeatures_desc": "Personel yönetimi özelliklerini etkinleştirin. Bazı senaryolar bu özellikleri zorunlu kılar ve bu ayarı geçersiz kılar.\nBu ayarı değiştirmek yalnızca personel enerji sistemini etkinleştirmez/devre dışı bırakmaz, aynı zamanda personel işe alım maliyetlerini ve maaş gereksinimlerini de değiştirir.",
  "optionsmenu_localparkstaffenergyfeatures_title": "Personel Yönetimi Özellikleri",
  "optionsmenu_lockcursortofullscreen": "Tam ekranda imleci kilitle",
  "optionsmenu_lockcursortowindow": "Pencere modunda imleci kilitle",
  "optionsmenu_lpv_desc": "Global aydınlatmayı açın veya kapatın. Global aydınlatma, ışığın nesnelerden yansımasını sağlayan bir efekttir.",
  "optionsmenu_missingdlctosavetooltip": "<div class=\"negative\">DLC GEREKLİ<br>Bu parkı kaydetmek için gerekli olan şu DLC eksik:</div>",
  "optionsmenu_mouseandkeyboard_custommouseremap_desc": "Fare ve klavye kontrollerini kendinize göre ayarlayın.",
  "optionsmenu_mouseandkeyboard_custommouseremap_title": "Fare ve Klavye Kontrollerini Değiştir",
  "optionsmenu_mouseandkeyboard_desc": "Fare ve klavye ayarlarınızı düzenleyin.",
  "optionsmenu_mouseandkeyboard_keysensitivity_desc": "Kameranın klavye girişlerine ne kadar duyarlı olacağını ayarlamak için kaydırıcıyı kullanın.",
  "optionsmenu_mouseandkeyboard_keysensitivity_title": "Tuş Hassasiyeti",
  "optionsmenu_mouseandkeyboard_mousesensitivity_desc": "Kameranın fare hareketine ne kadar duyarlı olacağını ayarlamak için kaydırıcıyı kullanın.",
  "optionsmenu_mouseandkeyboard_mousesensitivity_title": "Fare Hassasiyeti",
  "optionsmenu_mouseandkeyboard_remapbutton": "Değiştir",
  "optionsmenu_mouseandkeyboard_remapcontrols": "Kontrolleri Değiştir",
  "optionsmenu_mouseandkeyboard_title": "Fare ve Klavye Ayarları",
  "optionsmenu_multisample_desc": "Kenar yumuşatma, genel görüntüyü daha pürüzsüz hale getirir ve nesnelerin kenarlarındaki titreşimi azaltır.",
  "optionsmenu_mycreations": "Yaratımlarım",
  "optionsmenu_nohelpavailable": "Yardım mevcut değil",
  "optionsmenu_notifications": "Bildirimler",
  "optionsmenu_notifications_buildingsnotifications": "Bina Bildirimleri",
  "optionsmenu_notifications_coasternotifications": "Hız Treni Bildirimleri",
  "optionsmenu_notifications_disablealerts": "Önemli Uyarıları Devre Dışı Bırak",
  "optionsmenu_notifications_disableall": "Tümünü Devre Dışı Bırak",
  "optionsmenu_notifications_disablelowpriority": "Düşük Öncelikli Bildirimleri Devre Dışı Bırak",
  "optionsmenu_notifications_disablewarnings": "Uyarıları Devre Dışı Bırak",
  "optionsmenu_notifications_facilitiesandutilitiesnotifications": "Tesis ve Altyapı Bildirimleri",
  "optionsmenu_notifications_facilitiesnotifications": "Tesis Bildirimleri",
  "optionsmenu_notifications_financesnotifications": "Finans Bildirimleri",
  "optionsmenu_notifications_guestnotifications": "Ziyaretçi Bildirimleri",
  "optionsmenu_notifications_header": "Bildirim Ayarları",
  "optionsmenu_notifications_mutealerts": "Önemli Uyarıları Sessize Al",
  "optionsmenu_notifications_muteall": "Tümünü Sessize Al",
  "optionsmenu_notifications_mutelowpriority": "Düşük Öncelikli Bildirimleri Sessize Al",
  "optionsmenu_notifications_mutewarnings": "Uyarıları Sessize Al",
  "optionsmenu_notifications_parkmanagementnotifications": "Park Yönetimi Bildirimleri",
  "optionsmenu_notifications_pathsnotifications": "Yol Bildirimleri",
  "optionsmenu_notifications_ridesnotifications": "Eğlence Bildirimleri",
  "optionsmenu_notifications_shopsnotifications": "Dükkan Bildirimleri",
  "optionsmenu_notifications_staffnotifications": "Personel Bildirimleri",
  "optionsmenu_notifications_waterparksnotifications": "Su Parkı Bildirimleri",
  "optionsmenu_notificationsgameplay": "Oynanış Açılır Bildirimleri",
  "optionsmenu_notificationsguests": "Ziyaretçi Açılır Bildirimleri",
  "optionsmenu_notificationspark": "Park Açılır Bildirimleri",
  "optionsmenu_notificationsrides": "Eğlence Açılır Bildirimleri",
  "optionsmenu_notificationsstaff": "Personel Açılır Bildirimleri",
  "optionsmenu_notificationsstalls": "Tezgah Açılır Bildirimleri",
  "optionsmenu_notificationstitle": "Açılır Bildirimler",
  "optionsmenu_off": "Kapalı",
  "optionsmenu_ok": "Tamam",
  "optionsmenu_on": "Açık",
  "optionsmenu_onlyinsandboxmode": "Yalnızca sandbox modunda düzenlenebilir",
  "optionsmenu_options": "Seçenekler",
  "optionsmenu_otherinterfaceoptions": "Diğer Arayüz Seçenekleri",
  "optionsmenu_pausedheader": "Duraklatıldı",
  "optionsmenu_plancopedia": "Plancopedia",
  "optionsmenu_preview": "Önizleme",
  "optionsmenu_quit": "Planet Coaster 2'den Çık",
  "optionsmenu_refreshrate_desc": "Saniyedeki maksimum kare sayısını seçin.",
  "optionsmenu_remove": "DLC'yi Kaldır",
  "optionsmenu_resolution_desc": "Kaç piksel görüntüleneceğini seçin.",
  "optionsmenu_restartcareer": "Senaryoyu Yeniden Başlat",
  "optionsmenu_resume": "Devam Et",
  "optionsmenu_resumedetails": "Parkınıza geri dönün.",
  "optionsmenu_ridebreakdowns": "Eğlence Arızaları",
  "optionsmenu_ridebreakdowns_desc": "Eğlence arızalarını etkinleştirin. Eğlenceler bakım gerektirecek ya da arızalanacaktır.",
  "optionsmenu_ridebreakdowns_title": "Eğlence Arızaları",
  "optionsmenu_rumble": "Kumanda Titreşimini Etkinleştir",
  "optionsmenu_safeframe": "Güvenli Çerçeve",
  "optionsmenu_safeframe_adjustmentlocation": "HUD öğelerinin görüneceği alanı ayarlayın.",
  "optionsmenu_safeframe_details": "İşaretçiler ekranın kenarlarıyla hizalanana kadar kaydırıcıyı ayarlayın.",
  "optionsmenu_sandboxsettings": "Sandbox Ayarları",
  "optionsmenu_save": "Parkı Kaydet",
  "optionsmenu_saveas": "Parkı Farklı Kaydet...",
  "optionsmenu_savedetails": "İlerlemenizi kaydedin.",
  "optionsmenu_savedisabledtooltip": "Şu anda kaydedilemez",
  "optionsmenu_savemenu_loaddate": "{TimeString} - {DateString}",
  "optionsmenu_savemenu_loaddate_am": "ÖÖ",
  "optionsmenu_savemenu_loaddate_pm": "ÖS",
  "optionsmenu_savemenu_newsavegame": "Yeni Park Kaydı",
  "optionsmenu_savemenu_nosavedparks": "Kaydedilmiş park yok",
  "optionsmenu_savemenu_parkname": "Kayıt adı:",
  "optionsmenu_savemenu_savesdateheader": "Son Değiştirilme",
  "optionsmenu_savemenu_savesnameheader": "Park Kayıtlarım",
  "optionsmenu_savemenu_savestypeheader": "Park Türü",
  "optionsmenu_savemenu_savetoken": "{Name}",
  "optionsmenu_savemenu_saving": "Kaydediliyor...",
  "optionsmenu_savemenu_spawnpointwarning": "<font color='#FF0000'>Uyarı: Ziyaretçi çıkış noktası bulunamadı</font>",
  "optionsmenu_savemenu_typechallenge": "Meydan Okuma",
  "optionsmenu_savemenu_typesandbox": "Sandbox",
  "optionsmenu_savemenu_typescenariocareer": "Kariyer",
  "optionsmenu_savemenu_typescenarioedit": "Senaryo Editörü",
  "optionsmenu_savemenu_typescenarioother": "Özel Senaryo",
  "optionsmenu_savemenu_typestory": "Hikaye",
  "optionsmenu_savemenu_unknowntype": "-",
  "optionsmenu_saveprompt_eraseautosavelabel": "'{Name}' otomatik kaydı silinsin mi?",
  "optionsmenu_saveprompt_erasecancel": "İptal",
  "optionsmenu_saveprompt_eraseheader": "Kaydı Sil",
  "optionsmenu_saveprompt_eraselabel": "'{Name}' kaydı silinsin mi?",
  "optionsmenu_saveprompt_eraseok": "Tamam",
  "optionsmenu_saveprompt_overwritecancel": "İptal",
  "optionsmenu_saveprompt_overwriteheader": "Mevcut Kaydın Üzerine Yaz",
  "optionsmenu_saveprompt_overwritelabel": "'{Name}' kaydının üzerine yazılsın mı?",
  "optionsmenu_saveprompt_overwriteok": "Tamam",
  "optionsmenu_saveprompt_savefailedheader": "Kaydetme Başarısız",
  "optionsmenu_saveprompt_savefailedlabel": "'{Name}' kaydedilemedi",
  "optionsmenu_saveprompt_savefailedok": "Tamam",
  "optionsmenu_savescenario": "Senaryoyu Kaydet",
  "optionsmenu_savescenarioandplay": "Senaryoyu Kaydet ve Oyna",
  "optionsmenu_scaleinfo": "Metin Boyutu",
  "optionsmenu_scaleinfo_description": "Arayüz ölçekleme yalnızca oyun sırasında geçerlidir, ana menüde değil.",
  "optionsmenu_scaleinterface": "Arayüzü Ölçekle",
  "optionsmenu_scalemenuentry": "Arayüz Ölçeğini Ayarla",
  "optionsmenu_screenmode_desc": "Hangi pencere türünü kullanacağınızı seçin.",
  "optionsmenu_screensetup": "Ekran Kurulumu",
  "optionsmenu_sdr_details": "Ekranınızın parlaklığını ayarlamak için en sağdaki logo beyaz görünene kadar kaydırıcıyı hareket ettirin.",
  "optionsmenu_search_desc": "Belirli bir ayarı hızlıca bulmak için bu arama aracını kullanın.",
  "optionsmenu_search_header": "Ara",
  "optionsmenu_search_inputfieldprompt": "Metin girin...",
  "optionsmenu_search_results": "Sonuçlar",
  "optionsmenu_search_title": "Arama İşlevini Kullanma",
  "optionsmenu_settings": "Ayarlar",
  "optionsmenu_settingsdetails": "Ses, görüntü ve oyun arayüzüne ilişkin ayarları düzenleyin.",
  "optionsmenu_shadows_desc": "Gölgelerin detay seviyesini ve çizim mesafesini seçin.",
  "optionsmenu_showadditionalprompts": "Ek Düğme İpuçları",
  "optionsmenu_showadditionalprompts_desc": "Menü gezintisine yardımcı olmak için fare ve klavye kullanırken ek düğme ipuçlarını gösterin.",
  "optionsmenu_showparkboundary": "Park Sınırını Göster",
  "optionsmenu_ssr_desc": "Ekran uzayı yansımaları, yansıtıcı yüzeylerin gerçekçiliğini artırır.",
  "optionsmenu_staffhappiness": "Personel Morali",
  "optionsmenu_staffhappiness_desc": "Personel moralinin etkin olup olmayacağını seçin.",
  "optionsmenu_staffhappiness_title": "Personel Morali",
  "optionsmenu_subtitles_header": "Altyazı Ayarları",
  "optionsmenu_testdummies": "Test Mankeni Mutluluğu",
  "optionsmenu_texture_desc": "Dokular için bir detay seviyesi seçin.",
  "optionsmenu_toggleboundingboxplacement": "Varsayılan Olarak Sınır Kutusu Hizalaması",
  "optionsmenu_toiletcleanliness": "Tuvalet Temizliği",
  "optionsmenu_toiletcleanliness_desc": "Tuvalet temizliğini etkinleştirin. Oteller ve restoranlar kullanım sonrası periyodik temizlik gerektirecektir.",
  "optionsmenu_toiletcleanliness_title": "Tuvalet Temizliği",
  "optionsmenu_tutorialheader": "Öğretici",
  "optionsmenu_uihdr_brightness_details": "Arayüz HDR parlaklığını ayarlayın.",
  "optionsmenu_uihdrbrightness": "HDR Arayüz Parlaklığı",
  "optionsmenu_uploadchanges": "Değişiklikleri Yükle",
  "optionsmenu_uploadchanges_addnotes": "Not ekle...",
  "optionsmenu_uploadchanges_changenotesdesc": "Bu parka yaptığınız değişiklikler hakkında diğer üyeleri bilgilendirin.",
  "optionsmenu_uploadchanges_changenotestitle": "Değişiklik Notları",
  "optionsmenu_visual_heatmapcontrast_desc": "Hız trenleri ve ray eğlencelerindeki ısı haritası renklerini değiştirerek kontrastı artırın. Bu ayar ray üzerindeki renkler ile Canlı Veri panelini ve Isı Haritaları panelini etkiler.",
  "optionsmenu_visual_heatmapcontrast_title": "Isı Haritası Kontrastı",
  "optionsmenu_visual_interfacecolour_actual_tooltip": "Arayüz şu anda {Colour} renkte",
  "optionsmenu_visual_interfacecolour_desc": "Oyun arayüzünün ana rengini seçin.",
  "optionsmenu_visual_interfacecolour_title": "Arayüz Rengi",
  "optionsmenu_visual_interfacecolour_tooltip": "<p>{Colour} renge değiştir</p>",
  "optionsmenu_visual_onscreencontrols_desc": "Oynarken ekranda kontrollerin gösterilip gösterilmeyeceğini seçin.",
  "optionsmenu_visual_onscreencontrols_title": "Ekran Kontrollerini Göster",
  "optionsmenu_visual_showparkboundary_desc": "Park sınırının gösterilip gösterilmeyeceğini seçin.",
  "optionsmenu_visual_showparkboundary_title": "Park Sınırını Göster",
  "optionsmenu_volumeatmos_desc": "Ön planın ne kadar ayrıntılı olacağını seçin.",
  "optionsmenu_water_desc": "Su renderlamasının kalitesini seçin.",
  "optionsmenu_windowtitle": "Seçenekler",
  "optionsmenu_workshop": "Frontier Workshop",
  "optionsmenu_workshopdetails": "Diğer yaratıcıların eserlerini indirin ya da kendi eserlerinizi yükleyin.",
}

tr_json_path = Path("../translations/Content0/tr.json")
data = json.loads(tr_json_path.read_text(encoding="utf-8"))
strings = data["strings"]

updated = 0
for key, translation in TRANSLATIONS.items():
    if key in strings:
        strings[key]["translation"] = translation
        strings[key]["status"] = "translated"
        strings[key]["category"] = "optionsmenu"
        updated += 1

tr_json_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"{updated} string guncellendi.")
