"""frontendmenu çevirilerini Content0/tr.json'a uygular."""
import json
from pathlib import Path

TRANSLATIONS = {
  "frontendmenu_acceptinvite": "Daveti Kabul Et",
  "frontendmenu_all": "Tümü",
  "frontendmenu_alluploads": "Tüm Yüklemeleri Gör",
  "frontendmenu_alterchallenge": "Meydan Okuma Yükle",
  "frontendmenu_alterchallengecustom": "Meydan Okuma Yükle - Özel Ortam",
  "frontendmenu_altersandbox": "Serbest Mod Yükle",
  "frontendmenu_altersandboxcustom": "Serbest Mod Yükle - Özel Ortam",
  "frontendmenu_alterscenario": "Senaryo Yükle",
  "frontendmenu_alterscenariocustom": "Senaryo Yükle - Özel Ortam",
  "frontendmenu_autosave": "Otomatik Kayıtları Gizle",
  "frontendmenu_autosavenumber": "[Otomatik Kayıt] {Number:int:minDigits=1}",
  "frontendmenu_avatareditor_infolabel": "Artık Planet Coaster evreninin bir parçası olabilirsin! Avatarın, Steam arkadaşların ve diğer Planet Coaster oyuncuları tarafından görüntülenecek.\n\nAvatar görünümünü daha sonra düzenleyebilirsin.",
  "frontendmenu_avatareditor_infotitle": "Avatarını Oluştur!",
  "frontendmenu_avatargroup_reqs_family": "Aile grubu en az bir, en fazla iki yetişkin ve bir ile dört çocuk içermelidir.",
  "frontendmenu_avatargroupinvalid_title": "Geçersiz Aile Grubu",
  "frontendmenu_avatarmoderationfailed": "{AvatarType} gönderiniz reddedildi.\nDüzenleyiciyi açmak ister misiniz?",
  "frontendmenu_avatarmoderationfailedheader": "Avatar Denetimi Başarısız",
  "frontendmenu_avatarmoderationsent": "Avatarın denetim için sunucularımıza gönderilecek.\nGörünmesi biraz zaman alabilir.",
  "frontendmenu_avatarmoderationsentheader": "Avatar Oluşturma Tamamlandı",
  "frontendmenu_avatarnameneeded": "Lütfen avatarına bir isim ver.",
  "frontendmenu_avatarnameneededgroup": "Lütfen gruptaki her üyenin adının girildiğinden emin ol.",
  "frontendmenu_avatarnameneededheader": "Avatar Adı Eksik",
  "frontendmenu_avatarokbutton": "Tamam",
  "frontendmenu_avataroptions": "Avatar Seçenekleri",
  "frontendmenu_avatartype_group": "VIP Grup Bileti",
  "frontendmenu_avatartype_staff": "VIP Personel Kartı",
  "frontendmenu_avatartype_vip": "VIP Tekli Bilet",
  "frontendmenu_back": "Geri",
  "frontendmenu_biomelistview": "Biyom liste görünümü",
  "frontendmenu_biomes": "Biyomlar",
  "frontendmenu_biomesparks": "Parklar",
  "frontendmenu_blueprints": "Planlar",
  "frontendmenu_career": "Kariyer",
  "frontendmenu_career_amounttounlock": "Açmak için {Value:int} daha",
  "frontendmenu_career_careerprogress": "Kariyer İlerlemesi",
  "frontendmenu_career_careerrating": "Kariyer Puanı",
  "frontendmenu_career_chaptermedals": "Bölüm Madalyaları",
  "frontendmenu_career_facilities": "Tesisler",
  "frontendmenu_career_facilitiesdesc": "Tesis inşa etmek ilerlemenizi hızlandırır.",
  "frontendmenu_career_locked": "Kilitli",
  "frontendmenu_career_medalscount": "{Value:int}/{Max:int}",
  "frontendmenu_career_medalsdesc": "Kazandığın madalyalar bunlar.",
  "frontendmenu_career_medalsprogress": "Madalya İlerlemesi",
  "frontendmenu_career_nextmedalgoals": "Sonraki Madalya Hedefleri",
  "frontendmenu_career_parkdetails": "Park Detayları",
  "frontendmenu_career_playepilogueaudio": "Hikaye Sonsözü",
  "frontendmenu_career_playerprofile": "Profilin",
  "frontendmenu_career_playerprofiledescription": "Planet Coaster 2 profil detaylarını görüntüle.",
  "frontendmenu_career_progressdesc": "İlerledikçe Kariyer Puanın yükselir.",
  "frontendmenu_career_progressintro": "Böyle devam et!",
  "frontendmenu_career_replaychapteraudio": "Bölüm Girişi",
  "frontendmenu_career_restartchapter": "Bölümü Yeniden Başlat",
  "frontendmenu_career_restartlevel": "Senaryoyu Yeniden Başlat",
  "frontendmenu_career_restartlevel_desc": "Yeniden başlatırsan bu senaryodaki tüm ilerlemeyi kaybedersin. Devam etmek istediğinden emin misin?",
  "frontendmenu_career_rival": "Rakip",
  "frontendmenu_career_selectachapter": "Bir Bölüm Seç",
  "frontendmenu_career_selectactdescription": "Her Bölümde eşsiz parklar keşfet ve onları başarıya taşı! Yolculuğun boyunca madalyalar kazan, yeni dostlar edin ve yeni deneyimlerin kilidini aç.",
  "frontendmenu_career_selectacttitle": "Kariyer Moduna Hoş Geldin!",
  "frontendmenu_career_selectafacility": "Bir Tesis Seç",
  "frontendmenu_career_selectapark": "Bir Park Seç",
  "frontendmenu_career_selectchapter": "Bölüm Seç",
  "frontendmenu_career_selectpark": "Park Seç",
  "frontendmenu_career_selectpark_description": "Gezegeni döndür ve bir park seç.",
  "frontendmenu_career_techtree": "Teknoloji Ağacı",
  "frontendmenu_careercurrent": "{Value:int}",
  "frontendmenu_careerdescription": "Giderek zorlaşan senaryolarda birbirinden özel tema parklarını ve su parklarını yönet!",
  "frontendmenu_careerlastplayed": "Son Oynanan",
  "frontendmenu_careernewset": "YENİ!",
  "frontendmenu_careerprevious": "Parklar",
  "frontendmenu_careerprevioustooltips": "Önceki kayıtlı parkları yükle",
  "frontendmenu_careerresume": "Devam Et",
  "frontendmenu_careerscenariodetails": "Senaryo Detayları",
  "frontendmenu_careerscenarioselection": "Senaryo Seçimi",
  "frontendmenu_careersets": "Setler",
  "frontendmenu_careerstartnew": "Yeni Senaryo Başlat",
  "frontendmenu_careertemplates": "Kariyer Şablonları",
  "frontendmenu_careertemplates_desc": "Yeni parkın için boş bir Kariyer senaryo şablonu seç!",
  "frontendmenu_careertemplates_header": "Kariyer Parkları",
  "frontendmenu_careertotal": "/{Value:int}",
  "frontendmenu_celebrity": "Öne Çıkan İçerik Üreticisi",
  "frontendmenu_challenge": "Meydan Okuma",
  "frontendmenu_challengemode": "Meydan Okuma",
  "frontendmenu_challengemode_endgoal": "Meydan Okuma Modunu tamamlamak için 5 yıldıza ulaş.",
  "frontendmenu_challengemodedescription": "Harika bir park inşa ederken bütçeni gözden kaçırma ve zorlu meydan okumaların üstesinden gel!",
  "frontendmenu_challengemodeheader": "Meydan Okuma Modu",
  "frontendmenu_challengemodelabel": "Meydan Okuma",
  "frontendmenu_challengemodenewparkheader": "Yeni Park",
  "frontendmenu_challengemodenewparklabel": "Yeni Park",
  "frontendmenu_challengemodeparkviewheader": "Meydan Okuma",
  "frontendmenu_challengemodeparkviewlabel": "Meydan Okuma Parkları",
  "frontendmenu_challengemodeselectparkheader": "Park Seçimi",
  "frontendmenu_challengemodeselectparklabel": "Park Seç",
  "frontendmenu_challengeparkview": "Meydan Okuma Parkları",
  "frontendmenu_changepicture": "Resmi Değiştir",
  "frontendmenu_community": "Topluluk",
  "frontendmenu_connecting": "Bağlanıyor...",
  "frontendmenu_controllerdisconnect_quit": "Ana Menüye Dön",
  "frontendmenu_createdby": "Oluşturan: {Name}",
  "frontendmenu_credits": "Yapımcılar",
  "frontendmenu_creditsbutton": "Yapımcılar",
  "frontendmenu_custom": "Özel",
  "frontendmenu_custom_swappaint": "Boya Stilini Değiştir",
  "frontendmenu_customambiencedescription": "Bu yeni ortam için çevresel ses atmosferini seç.",
  "frontendmenu_customambienceheader": "Özel Atmosfer",
  "frontendmenu_custombiome_resetchangesdescription": "Bu ön ayarı seçmek, özel arazide yaptığın tüm değişiklikleri sıfırlayacak.",
  "frontendmenu_custombiome_resetchangesheader": "Değişiklikleri Sıfırla",
  "frontendmenu_custombiomedescription": "Bu özel ortamın temelini oluşturacak araziyi seç.",
  "frontendmenu_custombiomeheader": "Başlangıç Ortamı",
  "frontendmenu_customdescription": "Sınırsız parayla parkını kur ve özel bir ortamda inşa et!",
  "frontendmenu_custompaint_confirmcancel": "İptal",
  "frontendmenu_custompaint_confirmok": "Tamam",
  "frontendmenu_custompaint_reset": "Sıfırla",
  "frontendmenu_custompaint_title": "Renk Seçici",
  "frontendmenu_customsandbox_terrain": "Başlangıç Arazisi",
  "frontendmenu_customscenario": "Özel",
  "frontendmenu_customscenariodescription": "Özel bir ortamda yeni bir özel senaryo başlat!",
  "frontendmenu_customsimulation": "Özel",
  "frontendmenu_customsimulationdescription": "Sınırlı parayla parkını kur ve özel bir ortamda inşa et",
  "frontendmenu_customterrainpaintfilter": "Filtre",
  "frontendmenu_defaultchallengeparkname": "Meydan Okuma Parkı",
  "frontendmenu_defaultsandboxparkname": "Serbest Mod Parkı",
  "frontendmenu_defaultscenarioparkdescription": "Oyuncu Tarafından Oluşturulan Senaryo",
  "frontendmenu_defaultscenarioparkname": "Özel Senaryo",
  "frontendmenu_deletebutton": "Sil",
  "frontendmenu_demo": "Demo",
  "frontendmenu_desert": "Çöl",
  "frontendmenu_desertdescription": "Sınırsız parayla bu sert ve kurak ekosistemde parkını kur.",
  "frontendmenu_details": "Detaylar",
  "frontendmenu_difficulty": "Zorluk",
  "frontendmenu_difficulty_beginner": "Başlangıç",
  "frontendmenu_difficulty_custom": "Özel",
  "frontendmenu_difficulty_easy": "Kolay",
  "frontendmenu_difficulty_hard": "Zor",
  "frontendmenu_difficulty_harder": "Çok Zor",
  "frontendmenu_difficulty_medium": "Orta",
  "frontendmenu_difficulty_tutorial": "Hikaye",
  "frontendmenu_difficultyeasy": "Kolay",
  "frontendmenu_difficultyeasy_description": "Başlangıç Parası: Yüksek\nBiniş Bileti Fiyatları: Yüksek\nKredi Geri Ödemeleri: Düşük\nİadeler: Tam\nPark İtibarı Hızlı Yükselir\nPark İtibarı Yavaş Düşer\nArazi Maliyetleri: Düşük",
  "frontendmenu_difficultyhard": "Zor",
  "frontendmenu_difficultyhard_description": "Başlangıç Parası: Düşük\nBiniş Bileti Fiyatları: Düşük\nKredi Geri Ödemeleri: Yüksek\nİadeler: Azaltılmış\nPark İtibarı Yavaş Yükselir\nPark İtibarı Hızlı Düşer\nArazi Maliyetleri: Yüksek",
  "frontendmenu_difficultyharder": "Çok Zor",
  "frontendmenu_difficultyharder_description": "Başlangıç Parası: En Düşük\nBiniş Bileti Fiyatları: En Düşük\nKredi Geri Ödemeleri: En Yüksek\nİadeler: Yok\nPark İtibarı Çok Yavaş Yükselir\nPark İtibarı Çok Hızlı Düşer\nArazi Maliyetleri: En Yüksek",
  "frontendmenu_difficultyharder_descriptionalt": "",
  "frontendmenu_difficultymedium": "Orta",
  "frontendmenu_difficultymedium_description": "Başlangıç Parası: Standart\nBiniş Bileti Fiyatları: Standart\nKredi Geri Ödemeleri: Standart\nİadeler: Tam\nPark İtibarı: Standart\nArazi Maliyetleri: Standart",
  "frontendmenu_disconnected": "Sunucuyla bağlantın kesildi! Yapı {Version}",
  "frontendmenu_dlcs": "DLC'ler",
  "frontendmenu_downloads": "İndirilenler",
  "frontendmenu_downloadsdescription": "İndirilen Parkları ve Planları görüntüle",
  "frontendmenu_editasnewscenario": "Yeni Senaryo Olarak Düzenle",
  "frontendmenu_editavatar": "Avatarı Düzenle",
  "frontendmenu_editavatardescription": "Avatar görünümünü özelleştir.",
  "frontendmenu_editavatargroup": "VIP Grup Biletini Düzenle",
  "frontendmenu_editavatarstaff": "VIP Personel Kartını Düzenle",
  "frontendmenu_editavatarvip": "VIP Tekli Bileti Düzenle",
  "frontendmenu_editscenario": "Senaryoyu Düzenle",
  "frontendmenu_enterparkname": "Lütfen bir park adı girin...",
  "frontendmenu_exit": "Planet Coaster 2'den Çık",
  "frontendmenu_exitbutton": "Planet Coaster 2'den Çık",
  "frontendmenu_exitprompt_confirmcancel": "İptal",
  "frontendmenu_exitprompt_confirmok": "Tamam",
  "frontendmenu_exitprompt_header": "Çıkış",
  "frontendmenu_exitprompt_label": "Planet Coaster 2'den çıkmak istiyor musun?",
  "frontendmenu_exportsave_inprogress_content": "Kayıt serbest moda aktarılıyor, lütfen bekleyin...",
  "frontendmenu_exportsave_inprogress_title": "Kayıt Aktarılıyor",
  "frontendmenu_favourites": "Favoriler",
  "frontendmenu_follow": "Takip Et",
  "frontendmenu_followers": "Takipçiler",
  "frontendmenu_franchise": "Franchise",
  "frontendmenu_franchise_explore": "Keşfet",
  "frontendmenu_franchise_invitations": "Davetler",
  "frontendmenu_franchise_yourfranchises": "Franchise'larım",
  "frontendmenu_franchisedescription": "Küresel park Franchise'ınla sıralamalarda zirveye tır ve dünyanın dört bir yanından arkadaşlarınla birlikte parklar inşa et!",
  "frontendmenu_friend": "Arkadaş",
  "frontendmenu_friendshub": "Arkadaş Merkezi",
  "frontendmenu_friendshubdescription": "Arkadaşlarını görüntüle.",
  "frontendmenu_frontierdeveloper": "Frontier Geliştiricisi",
  "frontendmenu_frontierparks": "Frontier Parkları",
  "frontendmenu_globefilter_all": "Tümü",
  "frontendmenu_globefilter_celebs": "Öne Çıkan İçerik Üreticileri",
  "frontendmenu_globefilter_friends": "Arkadaşlar",
  "frontendmenu_globepin_new": "Yeni",
  "frontendmenu_groupeditor_infolabel": "Grubunu Planet Coaster evreninin parklarına uğurla!",
  "frontendmenu_groupeditor_infotitle": "VIP Grup Bileti Oluştur!",
  "frontendmenu_hqplacement_infolabel": "Merkez, diğer oyuncuların avatarını göreceği ve paylaştığın parklara ya da planlara erişebileceği yerdir.\n\nMerkezini küre üzerinde istediğin yere yerleştir. Merak etme, dilersen bu konumu sonradan değiştirebilirsin.",
  "frontendmenu_hqplacement_infotitle": "Avatar Merkezini Yerleştir!",
  "frontendmenu_hqplacement_promptcancel": "Hayır",
  "frontendmenu_hqplacement_promptconfrim": "Evet",
  "frontendmenu_hqplacement_promptlabel": "Emin misin?\n\nBunu daha sonra düzenleyebilirsin.",
  "frontendmenu_hqplacement_prompttitle": "Merkez Yerleştirme",
  "frontendmenu_lastupdated": "Son güncelleme: {Date}",
  "frontendmenu_levelunlock": "Bu seviyeyi açmak için en az {Value:int}. seviyede olman gerekiyor.",
  "frontendmenu_load": "Yükle",
  "frontendmenu_load_disabledtooltip_corrupted": "Bozuk bir kayıt yüklenemez",
  "frontendmenu_load_disabledtooltip_incompatiblewithconsole": "Park bu konsolla uyumsuz",
  "frontendmenu_loaddate": "{TimeString} - {DateString}",
  "frontendmenu_loadfailed_desc": "Seçilen kayıt dosyası yüklenemedi",
  "frontendmenu_loadfailed_ok": "Tamam",
  "frontendmenu_loadfailed_title": "Yükleme Başarısız",
  "frontendmenu_loaditems": "Frontier Workshop'a bağlanılıyor...",
  "frontendmenu_loadsaveaschallenge": "Meydan Okuma Olarak Aç",
  "frontendmenu_loadsaveassandbox": "Serbest Mod Olarak Aç",
  "frontendmenu_loadsaves": "Kayıtları Yükle",
  "frontendmenu_mainmenu": "Ana Menü",
  "frontendmenu_mediterranean": "Akdeniz",
  "frontendmenu_mediterraneandescription": "Sınırsız parayla hayalindeki parkı Akdeniz'in büyüleyici kıyılarında inşa et.",
  "frontendmenu_modificationsdialog_continue": "Devam Et",
  "frontendmenu_modificationsdialog_dontshowagain": "Bir Daha Gösterme",
  "frontendmenu_modificationsdialog_label": "Bazı yerel oyun dosyaların değiştirilmiş. Bu durum oyun sırasında çökmeler veya başka sorunlara yol açabilir.",
  "frontendmenu_modificationsdialog_title": "Değişiklikler Tespit Edildi",
  "frontendmenu_modifiedbiomeenvironment": "{EnvironmentName} (özelleştirilmiş)",
  "frontendmenu_morefeaturedcreators": "Öne Çıkan İçerik Üreticileri",
  "frontendmenu_morefeaturedcreatorsdescription": "Şu an öne çıkan içerik üreticilerine göz at!",
  "frontendmenu_morehotcontent": "Öne Çıkan İçerikler",
  "frontendmenu_morehotcontentdescription": "Şu an öne çıkan içeriklere göz at!",
  "frontendmenu_mostsubscribed": "En Çok Abone Olunan İçerikler",
  "frontendmenu_mostsubscribeddescription": "Atölye'deki şu anki en popüler içerikler!",
  "frontendmenu_moveglobe": "Küreyi Döndür",
  "frontendmenu_moveglobedescription": "Gezegeni döndürmek ve bir park seçmek için {#LogicalButton.FrontEnd_RotateGlobe#} kullan.",
  "frontendmenu_mydownloads": "İndirdiklerim",
  "frontendmenu_myparks": "Parklarım",
  "frontendmenu_myparks_currentfile": "Mevcut Dosya",
  "frontendmenu_myparks_deletesave": "Kaydı sil",
  "frontendmenu_myparks_deletesavedescription": "'{Name}' adlı kaydı silmek istediğinden emin misin?",
  "frontendmenu_myparks_exporttosandbox": "Serbest Moda Aktar",
  "frontendmenu_myparks_gotoworkshop": "Frontier Workshop'a Git",
  "frontendmenu_myparks_loadpark": "Parkı Yükle",
  "frontendmenu_myparks_new": "Yeni",
  "frontendmenu_myparks_newsave": "Yeni Kayıt Olarak Kaydet",
  "frontendmenu_myparks_newsavenamedesc": "Yeni oluşturulan parka bir isim ver.",
  "frontendmenu_myparks_newsavetitle": "Yeni kayıt dosyası oluştur",
  "frontendmenu_myparks_popupheader": "Bir Park Seç",
  "frontendmenu_myparks_savename": "Kayıt adı:",
  "frontendmenu_myparks_saveoptions": "Seçenekler",
  "frontendmenu_myparks_savepark": "Parkı Kaydet",
  "frontendmenu_myparks_slotsavailable": "{Value:int} alan mevcut",
  "frontendmenu_myparks_slotsavailable_single": "1 alan mevcut",
  "frontendmenu_myparks_sort": "Sırala",
  "frontendmenu_myparks_viewincareer": "Kariyerde Görüntüle",
  "frontendmenu_myparks_viewinchallenge": "Meydan Okumada Görüntüle",
  "frontendmenu_myparks_viewinsandbox": "Serbest Modda Görüntüle",
  "frontendmenu_myparks_workshopbtninfo": "Frontier Workshop'tan diğer oyuncuların yaptığı parkları indirebilirsin",
  "frontendmenu_myparkschallenge": "Mevcut bir Meydan Okuma Parkı yükle",
  "frontendmenu_myparksdescription": "Kayıtlı Parklar. Frontier Workshop Parkları.",
  "frontendmenu_myparkssandbox": "Mevcut bir Serbest Mod Parkı yükle",
  "frontendmenu_myparksscenarioedit": "Mevcut bir Özel Senaryo yükle",
  "frontendmenu_myparkssimulation": "Mevcut bir Meydan Okuma Parkı yükle",
  "frontendmenu_myparkstab_all": "Tümü",
  "frontendmenu_myparkstab_career": "Kariyer",
  "frontendmenu_myparkstab_challenge": "Meydan Okuma",
  "frontendmenu_myparkstab_description": "Kayıtlı parklarından herhangi birini yükle ve oyna.",
  "frontendmenu_myparkstab_franchise": "Franchise",
  "frontendmenu_myparkstab_sandbox": "Serbest",
  "frontendmenu_myparkstab_sortall": "Tümü",
  "frontendmenu_myparkstab_title": "Bir Park Seç",
  "frontendmenu_myparkstab_viewsandboxcollaborations": "Serbest Mod İş Birliklerini Görüntüle",
  "frontendmenu_myparkstab_workshop": "Frontier Workshop",
  "frontendmenu_myparksworkshop": "Frontier Workshop'a Git",
  "frontendmenu_mysubscriptionsdescription": "Abone olduğun atölye içeriklerini görüntüle.",
  "frontendmenu_mywegameparksworkshop": "WeGame Workshop'a Git",
  "frontendmenu_nameprompt_invalidvalue": "Geçersiz Ad",
  "frontendmenu_nameprompt_validating": "Doğrulanıyor",
  "frontendmenu_newchallenge": "Yeni Meydan Okuma",
  "frontendmenu_newchallengecustom": "Yeni Meydan Okuma - Özel Ortam",
  "frontendmenu_newcustomsandbox": "Yeni Meydan Okuma",
  "frontendmenu_newsandbox": "Yeni Serbest",
  "frontendmenu_newsandboxcustom": "Yeni Serbest - Özel Ortam",
  "frontendmenu_newsbuynow": "Steam Mağazasını Aç...",
  "frontendmenu_newscenariocustom": "Yeni Senaryo - Özel Ortam",
  "frontendmenu_newsopenurl": "Aç...",
  "frontendmenu_nouploads": "{Name} henüz hiçbir şey yüklememiş :(",
  "frontendmenu_openas": "Farklı Aç...",
  "frontendmenu_openastooltipenabled": "Parkı başka bir oyun modunda aç",
  "frontendmenu_owned": "Sahip Olunan",
  "frontendmenu_parkname": "Park Adı",
  "frontendmenu_pindate": "{DateString}",
  "frontendmenu_planetcoasterworkshop": "Frontier Workshop",
  "frontendmenu_planetcoasterworkshop_disabledtooltip": "Şu an Frontier Workshop'a erişilemiyor",
  "frontendmenu_planetcoasterworkshop_disabledtooltip_corrupted": "Bozuk bir kayıt yüklenemiyor",
  "frontendmenu_play": "Oyna",
  "frontendmenu_playbutton": "Parkı Yükle",
  "frontendmenu_playdetails": "Kariyer, Serbest veya Meydan Okuma modunda yeni bir oyun başlat ya da Senaryo Düzenleyici'de kendi senaryonu oluştur!",
  "frontendmenu_playdownloadaschallenge": "Meydan Okuma Olarak Oyna",
  "frontendmenu_playdownloadassandbox": "Serbest Mod Olarak Oyna",
  "frontendmenu_player": "Bu sensin!",
  "frontendmenu_playerprofile": "Oyuncu Profili",
  "frontendmenu_playscenario": "Senaryoyu Oyna",
  "frontendmenu_playtime": "Toplam oynama süresi: {Value:float:decimalPlaces=1} saat",
  "frontendmenu_profile": "Profil",
  "frontendmenu_promptno": "Hayır",
  "frontendmenu_promptyes": "Evet",
  "frontendmenu_rating": "Puan",
  "frontendmenu_repositionhq": "Avatar Merkezini Yeniden Konumlandır",
  "frontendmenu_resume": "Devam Et",
  "frontendmenu_returntotitle_header": "Başlık Ekranına Dön",
  "frontendmenu_returntotitle_label": "Başlık ekranına dönmek istediğinden emin misin?",
  "frontendmenu_sandbox": "Serbest",
  "frontendmenu_sandbox_newpark": "Yeni Park",
  "frontendmenu_sandboxdescription": "Hayal gücünü serbest bırak!",
  "frontendmenu_sandboxparkview": "Serbest Mod Parkları",
  "frontendmenu_sandboxselection": "Park Seçimi",
  "frontendmenu_saveauthor": "{Name}",
  "frontendmenu_saveauthorgamemode": "{Name}, {GameMode}",
  "frontendmenu_saveparkname": "{Name}",
  "frontendmenu_saveparknameanddifficulty": "{Name} ({Difficulty})",
  "frontendmenu_savetoken": "{Name}",
  "frontendmenu_scenario": "Senaryo Düzenleyici",
  "frontendmenu_scenariodetails_arch": "Zamanın acımasız akışına yenik düşmüş, terkedilmiş eski bir park. Gulpee maskotlarının neşeyle koştuğu yollar şimdi bomboş, gazoz akan şelalelerin yerine sel suları geçmiş. Yürek burkan bir manzara; ama gözyaşı dökmek sadece seli büyütür! Bu parkı çöküşünden kurtarabilecek misin?",
  "frontendmenu_scenariodetails_buil": "Vakıf bu muhteşem tepeye bir Viking diyarı inşa etmeye başladı; ancak Adriana bu yeri gerçek anlamda Asgard'a dönüştürmek için senin yardımına ihtiyaç duyuyor! Bifröst'ü tamamlamak için gökkuşağı kaydırakları inşa et ve parkını Viking hazineleriyle süsleyerek ziyaretçilerini büyüle!",
  "frontendmenu_scenariodetails_cany": "Brad, bu uçurumlar üzerine kurulu parkın ve heyecan arayan kitlesiyle sağlam bir yatırım olduğuna inanıyor; üstelik önceki sahiplerin bıraktığı borcu da üstleniyor. Ama bu, Eugene'e bir coaster mühendisi olarak ne kadar ilerlediğini kanıtlama fırsatı. Parkı büyüt, bu iki kardeşi bir araya getir!",
  "frontendmenu_scenariodetails_coas": "Bu idillik plaj tehlikeli sularda. Önceki sahip parkı ayakta tutmak için her şeyi denedi; ama sonunda borç seli altında kaldı. Neyse ki Brad, bu parkın gidişatını değiştirmek için net bir vizyona sahip: su kaydıraklarıyla tam anlamıyla büyük bir gürültü kopar. Haydi, dalmaya hazır ol!",
  "frontendmenu_scenariodetails_duel": "Coaster Coast, gizemli bir müşteri tarafından ikiye bölünmüş bir park için tutuldu. Tuhaf olan şu: müşteri bir yarıda özgürce inşa etmeni istiyor, diğer yarıda ise ağır koşullar öne sürüyor. Titiz müşteriyi idare et ve bu çift parkı çifte başarıya taşı!",
  "frontendmenu_scenariodetails_ecop": "Parkını yemyeşil bir doğa cennetine dönüştürerek ziyaretçilerine unutulmaz bir deneyim sun. Güneş enerjisinin gücünden faydalan ve ekolojik sürdürülebilirliğin atraksiyonlardan çok daha fazlasını canlandırabileceğini herkese göster. Yemyeşil, bereketli bir doğa seni bekliyor!",
  "frontendmenu_scenariodetails_gard": "Edith, büyük servetini kullanarak bahçesini torunları için efsanevi bir harikalar diyarına dönüştürmek istiyor. Kasa üzerinde sıkı bir denetim kurduğundan, ailesinin rüya tema parkını inşa etmek için her kuruşu iyi değerlendirmen gerekecek.",
  "frontendmenu_scenariodetails_gcd": "Planet Coaster 2'ye hoş geldiniz; nihai hız treni ve su parkı yaratıcı yönetim simülasyonu.\n15 dakikalık özel oynanışın tadını çıkarmak üzeresiniz; bir parkın inşaatına devam edip misafirleriniz için hayata geçireceksiniz. Yolculuğun tadını çıkar!\n\nSonbahar 2024'te geliyor - şimdi ön sipariş ver!",
  "frontendmenu_scenariodetails_laby": "Bu özgün kazı alanının yer altı tünellerine ve dalgalı arazisine kendini kaptır! Yüksek maliyetler ve zorlu inşaat kısıtlamalarıyla boğuşurken Adriana'yı etkileyecek ve ziyaretçileri büyüleyecek mitolojik bir labirent yarat.",
  "frontendmenu_scenariodetails_lazy": "Bu kavurucu sıcakta serinliğini koruyarak kaydırak ve flüm dolu muhteşem bir su parkı kur. Adriana, Eugene ve Brad'in desteğiyle muazzam tembel nehir hattından en iyi şekilde faydalan ve ziyaretçilerini yakıcı güneşten koru.",
  "frontendmenu_scenariodetails_lost": "Vakıf, çökmekte olan bir anıtın kalıntıları arasında dört antik roller coaster keşfetti; bunları restore etmek için senin yardımına ihtiyaçları var! Ziyaretçi çekerek ve coasterları tamamlayarak parkın potansiyelini gün yüzüne çıkar ve Planconia halkına atalarının zamanına çığır açan bir yolculuk yaşat!",
  "frontendmenu_scenariodetails_natu": "Bu gizemli İskandinav manzarasının ezici ihtişamına adım at! Eh, yeterince iyi bakılsaydı 'ezici ihtişam' olurdu zaten... Yapılacak tek bir şey var: bu toprakları eski Viking görkemiyle yeniden buluştur ve Doğa Ana'nın da gurur duyacağı bir park inşa et!",
  "frontendmenu_scenariodetails_plan": "Bu eski çiftlik arazisi, verimsizlikten verimliliğe geçmek için biraz ilgiye muhtaç. Önce temelleri sağlam at; o kısımları halledince çiftliğin geri kalanı senin elinde.",
  "frontendmenu_scenariodetails_spli": "Yan yana duran bu iki park, birbirinden çok farklı iki kardeşe aitmiş: biri aileler için bir park kurmak istemiş, diğeri ise en uç heyecanları hedeflemiş. Aralarındaki çekişme onları birbirinden kopardı; şimdi sahneye Newton kardeşler geliyor. Yanlış gidebilecek ne var ki?",
  "frontendmenu_scenariodetails_tiny": "Hank, üç cephesi suya bakan bu araziyi gözden kaçırmamak için satın aldı. Yatırımın karşılığını verebilmek için bu küçük alandan en verimli şekilde yararlanman gerekecek; ama unutma... Genişleyemiyorsan, yükselebilirsin.",
  "frontendmenu_scenariodetails_tutb": "Dışarıda potansiyel parklarla dolu kocaman bir dünya var; ama önce Coaster Coast'un oryantasyonundan geçmen gerekiyor. Lütfen kollarını ve bacaklarını bu coaster yolculuğu boyunca içeride tut ve park yönetimi derslerine hazırlan!",
  "frontendmenu_scenariodetails_tutw": "Tema parklarının dünyası son yıllarda epeyce değişti. Tek kelimeyle söylemek gerekirse: çok daha ıslandı... Ama seni can simidisiz derin sulara bırakmıyoruz. Coaster Coast'un su parkı mühendisliği uzmanı, ayaklarını suya alıştırmana yardımcı olmak için sabırsızlanıyor.",
  "frontendmenu_scenariodetails_twin": "Birbirine bağlı olmayan iki tepe, bir park için ideal bir konum gibi görünmeyebilir; çünkü değil. Ama Hank bu yerin gözde bir taşınmaz olduğundan emin. Belki muhteşem manzaralar, heyecan verici coasterlar ya da dik bir meydan okumanın verdiği heyecandir... Muhtemelen sadece acentenin verdiği ücretsiz kalemdir. Her ne olursa olsun, mühendislik zekanı konuştur ve bu dağları zirve bir tatil noktasına dönüştür!",
  "frontendmenu_scenariodetails_vomi": "Talih garip bir şekilde gülümsedi ve Hank inanılmaz güzel bir arazi kazandı. Sayısız yasal masraf ve 'teslimat ücreti' sonrasında bu adrenalin başkenti artık Coaster Coast'un elinde. Ziyaretçiler sınırlarının zorlanmasını bekliyor; demek ki tüm kozu oynamanın (ve temizlikçilerin!) tam zamanı!",
  "frontendmenu_scenarioname_arch": "Kayıp Cennet",
  "frontendmenu_scenarioname_buil": "Bifröst'ü İnşa Etmek",
  "frontendmenu_scenarioname_cany": "Hız Yarığı",
  "frontendmenu_scenarioname_coas": "Kıyı Meselesi",
  "frontendmenu_scenarioname_duel": "Çifte Dert",
  "frontendmenu_scenarioname_ecop": "Tam Orman",
  "frontendmenu_scenarioname_gard": "Edith'in Bahçesi",
  "frontendmenu_scenarioname_gcd": "Gamescom Demo",
  "frontendmenu_scenarioname_laby": "Labirent Sırları",
  "frontendmenu_scenarioname_lazy": "Tembel Styx Nehri",
  "frontendmenu_scenarioname_lost": "Parklar ve Restorasyon",
  "frontendmenu_scenarioname_natu": "Efsanevi Fiyort",
  "frontendmenu_scenarioname_plan": "Çiftlik Çılgınlığı",
  "frontendmenu_scenarioname_spli": "Swimm Kardeşler",
  "frontendmenu_scenarioname_tiny": "Sınır Tanımaz",
  "frontendmenu_scenarioname_tutb": "Hız Treninin Anahtarları",
  "frontendmenu_scenarioname_tutw": "Suyun İçinde",
  "frontendmenu_scenarioname_twin": "Zirvenin Harikası",
  "frontendmenu_scenarioname_vomi": "Heyecan Dolu",
  "frontendmenu_scenariounlock": "Bu seviyeyi açmak için {Scenario} senaryosunu tamamlamalısın.",
  "frontendmenu_search": "Ara",
  "frontendmenu_searchfollowers": "Takipçilerinde Ara",
  "frontendmenu_searchparks": "Ara",
  "frontendmenu_searchsteam": "Frontier Workshop'ta Ara",
  "frontendmenu_searchsteamworkshop": "Frontier Workshop'ta Ara",
  "frontendmenu_searchusers": "İçerik Üreticisi Ara",
  "frontendmenu_selectabiome": "Biyom Seç",
  "frontendmenu_selectabiome_desc": "Tropikal sahil şeritlerinden buzlu dağ manzaralarına kadar her Biyom, kendine özgü çevre koşullarına sahiptir ve parkın için muhteşem bir sahne sunar!",
  "frontendmenu_setdescription_act0": "Planet Coaster 2 macerana başla!",
  "frontendmenu_setdescription_act1": "Yeni lokasyonları keşfet ve heyecanı doyasıya yaşa.",
  "frontendmenu_setdescription_act2": "Coaster Coast büyüdükçe yeni zorluklar seni bekliyor.",
  "frontendmenu_setdescription_act3": "Park inşa etme ustalığını sınayan çetrefilli senaryolara hazır ol.",
  "frontendmenu_setdescription_act4": "Artık derin sulardayız! Bu son zorluklara dal ve park yapım dehanı kanıtla.",
  "frontendmenu_setdescription_act5": "Bölüm 5 Açıklaması",
  "frontendmenu_setdescription_arch": "Zamanın acımasız akışına yenik düşmüş, terkedilmiş eski bir park. Gulpee maskotlarının neşeyle koştuğu yollar şimdi bomboş, gazoz akan şelalelerin yerine sel suları geçmiş. Yürek burkan bir manzara; ama gözyaşı dökmek sadece seli büyütür! Bu parkı çöküşünden kurtarabilecek misin?",
  "frontendmenu_setdescription_buil": "Vakıf bu muhteşem tepeye bir Viking diyarı inşa etmeye başladı; ancak Adriana bu yeri gerçek anlamda Asgard'a dönüştürmek için senin yardımına ihtiyaç duyuyor! Bifröst'ü tamamlamak için gökkuşağı kaydırakları inşa et ve parkını Viking hazineleriyle süsleyerek ziyaretçilerini büyüle!",
  "frontendmenu_setdescription_cany": "Brad, bu uçurumlar üzerine kurulu parkın ve heyecan arayan kitlesiyle sağlam bir yatırım olduğuna inanıyor; üstelik önceki sahiplerin bıraktığı borcu da üstleniyor. Ama bu, Eugene'e bir coaster mühendisi olarak ne kadar ilerlediğini kanıtlama fırsatı. Parkı büyüt, bu iki kardeşi bir araya getir!",
  "frontendmenu_setdescription_coas": "Bu idillik plaj tehlikeli sularda. Önceki sahip parkı ayakta tutmak için her şeyi denedi; ama sonunda borç seli altında kaldı. Neyse ki Brad, bu parkın gidişatını değiştirmek için net bir vizyona sahip: su kaydıraklarıyla tam anlamıyla büyük bir gürültü kopar. Haydi, dalmaya hazır ol!",
  "frontendmenu_setdescription_duel": "Coaster Coast, gizemli bir müşteri tarafından ikiye bölünmüş bir park için tutuldu. Tuhaf olan şu: müşteri bir yarıda özgürce inşa etmeni istiyor, diğer yarıda ise ağır koşullar öne sürüyor. Titiz müşteriyi idare et ve bu çift parkı çifte başarıya taşı!",
  "frontendmenu_setdescription_ecop": "Parkını yemyeşil bir doğa cennetine dönüştürerek ziyaretçilerine unutulmaz bir deneyim sun. Güneş enerjisinin gücünden faydalan ve ekolojik sürdürülebilirliğin atraksiyonlardan çok daha fazlasını canlandırabileceğini herkese göster. Yemyeşil, bereketli bir doğa seni bekliyor!",
  "frontendmenu_setdescription_gard": "Edith, büyük servetini kullanarak bahçesini torunları için efsanevi bir harikalar diyarına dönüştürmek istiyor. Kasa üzerinde sıkı bir denetim kurduğundan, ailesinin rüya tema parkını inşa etmek için her kuruşu iyi değerlendirmen gerekecek.",
  "frontendmenu_setdescription_gcd": "Planet Coaster 2'ye hoş geldiniz; nihai hız treni ve su parkı yaratıcı yönetim simülasyonu.\n15 dakikalık özel oynanışın tadını çıkarmak üzeresiniz; bir parkın inşaatına devam edip misafirleriniz için hayata geçireceksiniz. Yolculuğun tadını çıkar!\n\nSonbahar 2024'te geliyor - şimdi ön sipariş ver!",
  "frontendmenu_setdescription_laby": "Bu özgün kazı alanının yer altı tünellerine ve dalgalı arazisine kendini kaptır! Yüksek maliyetler ve zorlu inşaat kısıtlamalarıyla boğuşurken Adriana'yı etkileyecek ve ziyaretçileri büyüleyecek mitolojik bir labirent yarat.",
  "frontendmenu_setdescription_lazy": "Bu kavurucu sıcakta serinliğini koruyarak kaydırak ve flüm dolu muhteşem bir su parkı kur. Adriana, Eugene ve Brad'in desteğiyle muazzam tembel nehir hattından en iyi şekilde faydalan ve ziyaretçilerini yakıcı güneşten koru.",
  "frontendmenu_setdescription_lost": "Vakıf, çökmekte olan bir anıtın kalıntıları arasında dört antik roller coaster keşfetti; bunları restore etmek için senin yardımına ihtiyaçları var! Ziyaretçi çekerek ve coasterları tamamlayarak parkın potansiyelini gün yüzüne çıkar ve Planconia halkına atalarının zamanına çığır açan bir yolculuk yaşat!",
  "frontendmenu_setdescription_natu": "Bu gizemli İskandinav manzarasının ezici ihtişamına adım at! Eh, yeterince iyi bakılsaydı 'ezici ihtişam' olurdu zaten... Yapılacak tek bir şey var: bu toprakları eski Viking görkemiyle yeniden buluştur ve Doğa Ana'nın da gurur duyacağı bir park inşa et!",
  "frontendmenu_setdescription_plan": "Bu eski çiftlik arazisi, verimsizlikten verimliliğe geçmek için biraz ilgiye muhtaç. Önce temelleri sağlam at; o kısımları halledince çiftliğin geri kalanı senin elinde.",
  "frontendmenu_setdescription_spli": "Yan yana duran bu iki park, birbirinden çok farklı iki kardeşe aitmiş: biri aileler için bir park kurmak istemiş, diğeri ise en uç heyecanları hedeflemiş. Aralarındaki çekişme onları birbirinden kopardı; şimdi sahneye Newton kardeşler geliyor. Yanlış gidebilecek ne var ki?",
  "frontendmenu_setdescription_tiny": "Hank, üç cephesi suya bakan bu araziyi gözden kaçırmamak için satın aldı. Yatırımın karşılığını verebilmek için bu küçük alandan en verimli şekilde yararlanman gerekecek; ama unutma... Genişleyemiyorsan, yükselebilirsin.",
  "frontendmenu_setdescription_tutb": "Dışarıda potansiyel parklarla dolu kocaman bir dünya var; ama önce Coaster Coast'un oryantasyonundan geçmen gerekiyor. Lütfen kollarını ve bacaklarını bu coaster yolculuğu boyunca içeride tut ve park yönetimi derslerine hazırlan!",
  "frontendmenu_setdescription_tutw": "Tema parklarının dünyası son yıllarda epeyce değişti. Tek kelimeyle söylemek gerekirse: çok daha ıslandı... Ama seni can simidisiz derin sulara bırakmıyoruz. Coaster Coast'un su parkı mühendisliği uzmanı, ayaklarını suya alıştırmana yardımcı olmak için sabırsızlanıyor.",
  "frontendmenu_setdescription_twin": "Birbirine bağlı olmayan iki tepe, bir park için ideal bir konum gibi görünmeyebilir; çünkü değil. Ama Hank bu yerin gözde bir taşınmaz olduğundan emin. Belki muhteşem manzaralar, heyecan verici coasterlar ya da dik bir meydan okumanın verdiği heyecandir... Muhtemelen sadece acentenin verdiği ücretsiz kalemdir. Her ne olursa olsun, mühendislik zekanı konuştur ve bu dağları zirve bir tatil noktasına dönüştür!",
  "frontendmenu_setdescription_vomi": "Talih garip bir şekilde gülümsedi ve Hank inanılmaz güzel bir arazi kazandı. Sayısız yasal masraf ve 'teslimat ücreti' sonrasında bu adrenalin başkenti artık Coaster Coast'un elinde. Ziyaretçiler sınırlarının zorlanmasını bekliyor; demek ki tüm kozu oynamanın (ve temizlikçilerin!) tam zamanı!",
  "frontendmenu_setname_act0": "İlk İniş",
  "frontendmenu_setname_act1": "Akışa Bırak",
  "frontendmenu_setname_act2": "Çark Döner",
  "frontendmenu_setname_act3": "Kıvrımlı Raylar",
  "frontendmenu_setname_act4": "Son Dalış",
  "frontendmenu_setname_act5": "Coaster Sonrası Adrenalin",
  "frontendmenu_setname_arch": "Kayıp Cennet",
  "frontendmenu_setname_buil": "Bifröst'ü İnşa Etmek",
  "frontendmenu_setname_cany": "Hız Yarığı",
  "frontendmenu_setname_coas": "Kıyı Meselesi",
  "frontendmenu_setname_duel": "Çifte Dert",
  "frontendmenu_setname_ecop": "Tam Orman",
  "frontendmenu_setname_gard": "Edith'in Bahçesi",
  "frontendmenu_setname_gcd": "Gamescom Demo",
  "frontendmenu_setname_laby": "Labirent Sırları",
  "frontendmenu_setname_lazy": "Tembel Styx Nehri",
  "frontendmenu_setname_lost": "Parklar ve Restorasyon",
  "frontendmenu_setname_natu": "Efsanevi Fiyort",
  "frontendmenu_setname_plan": "Çiftlik Çılgınlığı",
  "frontendmenu_setname_spli": "Swimm Kardeşler",
  "frontendmenu_setname_tiny": "Sınır Tanımaz",
  "frontendmenu_setname_tutb": "Hız Treninin Anahtarları",
  "frontendmenu_setname_tutw": "Suyun İçinde",
  "frontendmenu_setname_twin": "Zirvenin Harikası",
  "frontendmenu_setname_vomi": "Heyecan Dolu",
  "frontendmenu_setnameanddifficulty": "{Name} ({Difficulty})",
  "frontendmenu_settings": "Ayarlar",
  "frontendmenu_settingsbutton": "Seçenekler",
  "frontendmenu_settingup": "Kurulum yapılıyor",
  "frontendmenu_setunlock": "Bu seviyeyi açmak için en az {Value:int}. seviyede olman gerekiyor.",
  "frontendmenu_simulation": "Meydan Okuma",
  "frontendmenu_simulationdescription": "Başarı için kısıtlı bütçeni iyi yönet.",
  "frontendmenu_skip": "Atla",
  "frontendmenu_sortby": "Sırala",
  "frontendmenu_sortbylastplayedascending": "En Eski",
  "frontendmenu_sortbylastplayeddescending": "En Yeni",
  "frontendmenu_sortbynameascending": "Ad A-Z",
  "frontendmenu_sortbynamedescending": "Yazar Z-A",
  "frontendmenu_sortbytimeplayedascending": "En Çok Oynanan",
  "frontendmenu_sortbytimeplayeddescending": "En Az Oynanan",
  "frontendmenu_staffeditor_infolabel": "Diğer oyuncuların oyunlarında görünecek bir personel üyesi oluştur.",
  "frontendmenu_staffeditor_infotitle": "VIP Personel Kartını Oluştur!",
  "frontendmenu_startnew": "Yeni Başlat",
  "frontendmenu_story": "Kariyer",
  "frontendmenu_subscribe": "Abone Ol",
  "frontendmenu_subscribers": "Aboneler",
  "frontendmenu_taiga": "Tayga",
  "frontendmenu_taigadescription": "Sonsuz bütçeyle fiyortların görkemli vadileri ve buz gibi buzul sularının ortasında parkını kur.",
  "frontendmenu_temperate": "Ilıman",
  "frontendmenu_temperatescenario": "Ilıman",
  "frontendmenu_temperatescenariodescription": "Bu ılıman ortamda yeni bir özel senaryo başlat!",
  "frontendmenu_temperatesimulation": "Ilıman",
  "frontendmenu_temperatesimulationdescription": "Kısıtlı bütçeyle bu ılıman ortamda hayalindeki parkı inşa et!",
  "frontendmenu_terrainpaintdesc": "{Biome} - {Slot}\n{Desc}",
  "frontendmenu_terrainpaintdesc_none": "Yok",
  "frontendmenu_terrainpainttitle_detail": "Detay",
  "frontendmenu_terrainpainttitle_ground": "Zemin",
  "frontendmenu_terrainpainttitle_steep": "Eğim",
  "frontendmenu_terrainpainttitle_withnumber": "{Name} {Number:int}",
  "frontendmenu_terrainpainttooltip_detail": "Oluşturulan arazi bu dokuyu detay için kullanacak.",
  "frontendmenu_terrainpainttooltip_ground": "Oluşturulan arazi bu dokuyu düz zeminde ve Otomatik Boya kullanılırken uygulayacak.",
  "frontendmenu_terrainpainttooltip_steep": "Oluşturulan arazi bu dokuyu dik eğimlerde ve Otomatik Boya kullanılırken uygulayacak.",
  "frontendmenu_testdetails": "Planet Coaster'ın fantastik dünyasını keşfet, sonsuz olasılıkları dene ve en iyi tema parkını yarat.",
  "frontendmenu_testsavename": "Park Yükle",
  "frontendmenu_thememakerdescr": "3D model yaratımlarını Planet Coaster dekor öğelerine dönüştür!",
  "frontendmenu_thememakerupload": "Oluştur",
  "frontendmenu_themepark": "{Name}'in Coaster Parkı",
  "frontendmenu_titlepromptprefix": "Devam etmek için",
  "frontendmenu_titlepromptsuffix": "tuşuna bas",
  "frontendmenu_tooltip_offline": "Sunucuyla bağlantın kesildi!",
  "frontendmenu_tooltip_oldparksteam": "Bu park eski bir oyun sürümüne ait. Steam'e yüklemek için yeniden kaydet.",
  "frontendmenu_trendinguploads": "Trend Yüklemeler",
  "frontendmenu_tropical": "Tropikal",
  "frontendmenu_tropicaldescription": "Sonsuz bütçeyle hayalindeki tatil cenneti parkını inşa et!",
  "frontendmenu_tropicalscenario": "Tropikal",
  "frontendmenu_tropicalscenariodescription": "Hayalindeki tatil cennetinde yeni bir özel senaryo başlat!",
  "frontendmenu_tropicalsimulation": "Tropikal",
  "frontendmenu_tropicalsimulationdescription": "Kısıtlı bütçeyle hayalindeki tatil cenneti parkını inşa et!",
  "frontendmenu_tundra": "Tundra",
  "frontendmenu_tundradescription": "Sonsuz bütçeyle bu dondurucu soğuk ve sarp dağ ortamında özel bir şeyler yarat.",
  "frontendmenu_tutorial": "Eğitim Videoları",
  "frontendmenu_tutorialdescription": "Yakında!",
  "frontendmenu_unfollow": "Takibi Bırak",
  "frontendmenu_unsubscribe": "Aboneliği İptal Et",
  "frontendmenu_update2popup_desc": "Güncelleme 2 ile Sürüş Senkronizasyonu geliyor; artık sürüşlerinin zamanlamalarını senkronize edebilecek ve ilk kez hız treni arabaları maksimum yaratıcılık için rotalar arasında taşınabilecek! Ayrıca Wing - Zincirli Kaldırmalı ve Junior Coaster'ın Standart temasız versiyonlarını ve bu sürüşlerin temalı Coaster Aksesuarlarını Dekor sekmesinde bulacaksın. Güncelleme 2 aynı zamanda yeni Video Billboardlar sunuyor ve klasik düz sürüş Pathos III'ü geri getiriyor. Wippi yalapler!",
  "frontendmenu_update2popup_subtitle": "Güncelleme 2 kuruldu",
  "frontendmenu_update2popup_title": "Güncelleme 2'ye Hoş Geldin!",
  "frontendmenu_update3popup_desc": "Güncelleme 3 büyük bir sıçrama yapıyor! Flüm Davranışlarında iyileştirmeler, daha çeşitli sal hareketleri, misafir fırlatma ve şişme oyuncak deformasyonu geliyor! Kariyer Modu'nun Öğretici ve 1. Bölüm başlangıç düzenlemeleri artık Serbest Mod'da da mevcut. Hız treni meraklıları Fırlatmalı - Hidrolik ve 4 Kişilik Oturuş coaster'larının yeni Standart versiyonlarını ve geri dönen Vector Inverting Suspended coaster'ı görecek. Diğer düzeltmelerin yanı sıra Western temasının ilk dekor varlıklarını da sunmaktan heyecan duyuyoruz! Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et. Wippi yalapler!",
  "frontendmenu_update3popup_subtitle": "Güncelleme 3 kuruldu",
  "frontendmenu_update3popup_title": "Güncelleme 3'e Hoş Geldin!",
  "frontendmenu_update4popup_desc": "Güncelleme 4 Restoranlar sunuyor; yeni Restoran Mutfakları, Yemek Masaları ve temalı Piknik Masalarını kullanarak mükemmel yemek deneyimini tasarla. Ayrıca düz sürüş Scizzer geri dönüyor; havuz karoları, havuz suyu ve su şekli dekor parçaları için özel renkler de geldi! Spinning Manic Mouse ve Inverted Flying coaster'larının Standart versiyonları ile Mouse ve Manta Ray Coaster Aksesuarları da mevcut. Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et. Wippi yalapler!",
  "frontendmenu_update4popup_subtitle": "Güncelleme 4 kuruldu",
  "frontendmenu_update4popup_title": "Güncelleme 4'e Hoş Geldin!",
  "frontendmenu_update5popup_desc": "Güncelleme 5 güvenliği ele alıyor! Güvenlik Görevlileriyle Vandallara ve Yankesicilere dur de. Güvenlik Kameraları ve Güvenlik Noktaları yerleştir. Suçluları at ve vandalize edilen tesisleri onar! Ayrıca Vector Return Mk II geri dönüyor; gidiş-dönüş çifte heyecan sunan bir mekik coaster! Bilim Kurgu teması ve Standart versiyonlu yeni hız trenleri de dahil. Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et. Wippi yalapler!",
  "frontendmenu_update5popup_subtitle": "Güncelleme 5 kuruldu",
  "frontendmenu_update5popup_title": "Güncelleme 5'e Hoş Geldin!",
  "frontendmenu_update6popup_desc": "Peynir de! Güncelleme 6 Sürüş Fotoğraf Kameraları getiriyor. Bir Fotoğraf Kiosku yerleştir ve Billboard'larla büyük ekranda eğlenceyi göster! Modüler Hediyelik Eşya Dükkanları da geliyor: birkaç Raf ile küçük bir stall kur ya da Kasa ve Rafları birleştirerek görkemli bir mağaza yap, seçim senin! Peri Masalı ve Korsan Dekor paketleri ile Coriolis düz sürüşü geri dönüyor. Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et. Wippi yalapler!",
  "frontendmenu_update6popup_descalt": "Peynir de! Güncelleme 6 Sürüş Fotoğraf Kameraları getiriyor. Bir Fotoğraf Kiosku yerleştir ve Billboard'ları bağlayarak büyük ekranda eğlenceyi göster! Modüler Hediyelik Eşya Dükkanları da geliyor: birkaç Raf ile küçük bir stall kur ya da çok sayıda Raf birleştirerek görkemli bir mağaza yap, seçim senin! Peri Masalı ve Korsan Dekor paketleri ile Coriolis düz sürüşü geri dönüyor. Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et. Wippi yalapler!",
  "frontendmenu_update6popup_subtitle": "Güncelleme 6 kuruldu",
  "frontendmenu_update6popup_title": "Güncelleme 6'ya Hoş Geldin!",
  "frontendmenu_update7popup_desc": "Güncelleme 7 burada ve Meydan Okuma Modu geliyor: 5 yıldızlı Park Puanına ulaşmak için çılgın zorluklara meydan oku! Izgara tabanlı Dekor nesneleri için 3 Eksenli Döndürme de var! Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et.\n\nSihir Paketi artık mevcut ve büyülü Outamax LSM Baskın Coaster dahil üç yeni hız treni sunuyor! Büyüleyici Uçan Tiyatro dahil iki yeni düz sürüş de var. Yeni maskot Vesper'a dikkat et; Sihir dekor paketiyle kendi gizemli dünyanı oluştur. Wippi yalapler!",
  "frontendmenu_update7popup_subtitle": "Güncelleme 7 kuruldu",
  "frontendmenu_update7popup_title": "Güncelleme 7 ve Sihir Paketine Hoş Geldin!",
  "frontendmenu_update8popup_desc": "Yıldönümü Güncellemesi burada ve Planet Coaster 2'ye Wippi Baradeyo diyoruz! İnteraktif Atış Sürüşü artık mevcut! Statik ve animasyonlu hedefler kur, kitleni al ve en yüksek skoru topla! Tüm güncelleme notları için Planet Coaster web sitesini ziyaret et. Wippi yalapler!",
  "frontendmenu_update8popup_subtitle": "Yıldönümü Güncellemesi kuruldu",
  "frontendmenu_update8popup_title": "Yıldönümü Güncellemesine Hoş Geldin!",
}

tr_json_path = Path("../translations/Content0/tr.json")
data = json.loads(tr_json_path.read_text(encoding="utf-8"))
strings = data["strings"]

updated = 0
for key, translation in TRANSLATIONS.items():
    if key in strings:
        strings[key]["translation"] = translation
        strings[key]["status"] = "translated"
        strings[key]["category"] = "frontendmenu"
        updated += 1

tr_json_path.write_text(
    json.dumps(data, ensure_ascii=False, indent=2),
    encoding="utf-8"
)
print(f"{updated} string guncellendi.")
