"""popup çevirilerini tr.json'a uygular."""
import json
from pathlib import Path

TRANSLATIONS = {
  "popup_addobjecttotrigger": "Tetikleyiciye Nesne Ekle",
  "popup_addtrigger": "Tetikleyici Ekle",
  "popup_addtriggerhide": "Bağlı nesneleri gizle",
  "popup_addtriggerhideoption": "Seçenekleri gizle",
  "popup_addtriggerhint": "Tren geçtiğinde etkinleşecek bir nokta raya ekle.",
  "popup_addtriggerplay": "Bağlı nesnelerde etkinleşmeyi test et",
  "popup_addtriggershow": "Bağlı nesneleri göster",
  "popup_addtriggershowoption": "Seçenekleri göster",
  "popup_ambience_favouritestab": "Favoriler",
  "popup_ambience_planetcoastertab": "Planet Coaster Ortam Sesleri",
  "popup_cannotopen": "Eğlence test edilmedi ve kontrol listesi eksik olduğundan açılamıyor",
  "popup_cannotopen_basic": "Açılamıyor",
  "popup_cannotopen_incomplete": "Kontrol listesi eksik olduğundan açılamıyor",
  "popup_cannotopen_need2stations": "Ulaşım eğlenceleri en az 2 istasyon gerektirdiğinden açılamıyor.",
  "popup_cannotopen_nocircuit": "Ray devre oluşturmadığından açılamıyor",
  "popup_cannotopen_nostations": "Tamamlanmış istasyon olmadığından açılamıyor",
  "popup_cannotopen_racing": "Ray devre oluşturmuyor ve kontrol listesi eksik olduğundan açılamıyor",
  "popup_cannotopen_station": "İstasyon test edilmediğinden açılamıyor",
  "popup_cannotopen_testing_incomplete": "Test Tamamlanmadı",
  "popup_cannotopen_untested": "Eğlence test edilmediğinden açılamıyor",
  "popup_cannottest_noendloops": "Sürüş İstasyonu Tekerleği ve Boğa Tekerleği Kapağı eksik olduğundan test edilemiyor",
  "popup_cannottest_nostations": "Kurulu istasyon olmadığından test edilemiyor",
  "popup_checklist": "Kontrol Listesi",
  "popup_closed": "Kapat",
  "popup_coasterstats": "Hız Treni İstatistikleri",
  "popup_coastertriggerdescription": "Ray boyunca tetikleyiciler yerleştir ve bunları animasyonlu dekora bağla",
  "popup_coastertriggerId": "{VALUE:int}",
  "popup_coastertriggernamedefault": "Hız Treni Tetikleyicisi",
  "popup_coastertriggertitle": "Hız Treni Tetikleyicileri",
  "popup_customise": "Özelleştir",
  "popup_displaysequencer_removeall_tooltip": "Tümünü Kaldır",
  "popup_dropitem": "Nesneyi Bırak",
  "popup_fastpass_mergename": "Öncelikli Geçiş Çıkışı",
  "popup_fastpass_splitname": "Öncelikli Geçiş Girişi",
  "popup_finances": "Finanslar",
  "popup_focuscam": "Kamerayı Ortala",
  "popup_guests": "Ziyaretçiler",
  "popup_maintenance": "Bakım",
  "popup_multiselect_blueprinttoomanyflatrides": "Taslaklar 5'ten fazla düz eğlence içeremez.",
  "popup_multiselect_blueprinttoomanyflatrides_variable": "Taslaklar {VALUE:int}'den fazla düz eğlence içeremez.",
  "popup_multiselect_blueprinttoomanyprops": "Taslaklar 4000'den fazla dekor/yapı parçası içeremez.",
  "popup_multiselect_blueprinttoomanyprops_variable": "Taslaklar {VALUE:int}'den fazla dekor parçası içeremez.",
  "popup_multiselect_blueprinttoomanyrides": "Taslaklar 5'ten fazla eğlence içeremez.",
  "popup_multiselect_blueprinttoomanyrides_variable": "Taslaklar {VALUE:int}'den fazla eğlence içeremez.",
  "popup_multiselect_blueprinttoomanytrackedrides": "Taslaklar 5'ten fazla hız treni, raylı eğlence veya akarsu yolu içeremez.",
  "popup_multiselect_blueprinttoomanytrackedrides_variable": "Taslaklar {VALUE:int}'den fazla hız treni, raylı eğlence veya akarsu yolu içeremez.",
  "popup_multiselect_blueprinttoomanyvolumes_variable": "Taslaklar {VALUE:int}'den fazla yol/havuz bölümü içeremez.",
  "popup_multiselect_buildingmerge": "Seçili Binaya Dekor Ekle.",
  "popup_multiselect_buildingmerge_toobig": "5000'den fazla dekor/yapı parçası içeren bir bina oluşturmak için dekor eklenemiyor.",
  "popup_multiselect_buildingmerge_toobig_variable": "{VALUE:int}'den fazla dekor/yapı parçası içeren bir bina oluşturmak için dekor eklenemiyor.",
  "popup_multiselect_buildingsplit_toobig": "5000'den fazla dekor parçası seçiliyken gruplama kaldırılamıyor.",
  "popup_multiselect_buildingsplit_toobig_variable": "{VALUE:int}'den fazla dekor parçası seçiliyken gruplama kaldırılamıyor.",
  "popup_multiselect_clonenorides": "Eğlenceler kopyalanamıyor.",
  "popup_multiselect_containslockeditems": "Kilitli öğeler içeriyor",
  "popup_multiselect_countvalue": "{COUNT:separatedFloat:decimalPlaces=0}",
  "popup_multiselect_duellingcoasters_coastersinchain": "Zincirdeki Hız Trenleri",
  "popup_multiselect_duellingcoasters_coastersinselection": "Seçimdeki Hız Trenleri",
  "popup_multiselect_duellingcoasters_coasterslinkedtochain": "Zincirdeki Hız Trenleri",
  "popup_multiselect_duellingcoasters_coasterslinkedtochain_label": "En fazla 5 hız treni birbirine bağlanabilir.",
  "popup_multiselect_duellingcoasters_confirm_label": "Bir zincirde {MAX:separatedFloat:decimalPlaces=0}'den fazla hız treni olamaz.",
  "popup_multiselect_duellingcoasters_description": "Hız Trenlerini Hız Treni Zincirine eklemek için Çoklu Seçim aracını kullan.",
  "popup_multiselect_duellingcoasters_header": "Hız Treni Zinciri Oluştur",
  "popup_multiselect_duellingcoasters_numselected": "Seçilen Hız Trenleri",
  "popup_multiselect_duellingcoasters_numselected_label": "Birbirine bağlamak istediğin Hız Trenlerini seçmek için sürükle veya tıkla.",
  "popup_multiselect_duellingcoasters_title": "Hız Treni Zinciri",
  "popup_multiselect_edittoomanyflatrides": "Aynı anda 5'ten fazla düz eğlence taşınamaz/silinemez.",
  "popup_multiselect_edittoomanyflatrides_variable": "Aynı anda {VALUE:int}'den fazla düz eğlence taşınamaz/silinemez.",
  "popup_multiselect_edittoomanyprops": "Aynı anda 5000'den fazla dekor/yapı parçası taşınamaz/silinemez.",
  "popup_multiselect_edittoomanyprops_variable": "Aynı anda {VALUE:int}'den fazla dekor parçası taşınamaz/silinemez.",
  "popup_multiselect_edittoomanyrides": "Aynı anda 5'ten fazla eğlence taşınamaz/silinemez.",
  "popup_multiselect_edittoomanyrides_variable": "Aynı anda {VALUE:int}'den fazla eğlence taşınamaz/silinemez.",
  "popup_multiselect_edittoomanytrackedrides": "Aynı anda 5'ten fazla hız treni taşınamaz/silinemez.",
  "popup_multiselect_edittoomanytrackedrides_variable": "Aynı anda {VALUE:int}'den fazla hız treni, raylı eğlence veya akarsu yolu taşınamaz/silinemez.",
  "popup_multiselect_edittoomanyvolumes_variable": "Aynı anda {VALUE:int}'den fazla yol/havuz bölümü taşınamaz/silinemez.",
  "popup_multiselect_fractionvalue": "{COUNT:separatedFloat:decimalPlaces=0}/{MAX:separatedFloat:decimalPlaces=0}",
  "popup_multiselect_labelcountbuilding": "Binalar",
  "popup_multiselect_labelcountflatrides": "Düz Eğlenceler",
  "popup_multiselect_labelcountsceneryparts": "Dekor ve Yapı Parçaları",
  "popup_multiselect_labelcounttrackedrides": "Raylı Eğlenceler",
  "popup_multiselect_labelcountvolumes": "Yol/Havuz Bölümleri",
  "popup_multiselect_labelselectionstatistics": "Seçim Bilgileri",
  "popup_multiselect_patrolzones_commit": "Çalışma listesini kaydet",
  "popup_multiselect_patrolzones_defaultname": "Çalışma Listesi",
  "popup_multiselect_patrolzones_description": "Personele atanacak öncelikli çekici ve tesisleri belirlemek için Çoklu Seçim kullan.\n\nTamirciler yalnızca bu listeye atanmışlarsa seçili eğlencelerle ilgilenecek.\nSatıcılar yalnızca bu listeye atanmışlarsa seçili dükkanlarda çalışmaya çalışacak.\nTüm personel seçili personel binalarını tercih edecek ama doluysa başka yere bakacak.\nTüm personel seçilen yerleri devriye güzergahı olarak kullanacak.",
  "popup_multiselect_patrolzones_header": "Çalışma Listesi Seçimi",
  "popup_multiselect_patrolzones_labelcountbuildingelements": "Tesisler ve Dükkanlar",
  "popup_multiselect_patrolzones_labelcountflatridestations": "Düz Eğlenceler",
  "popup_multiselect_patrolzones_labelcountmeetandgreetpoints": "Eğlence Noktaları",
  "popup_multiselect_patrolzones_labelcounttrackedridestations": "Raylı Eğlence İstasyonları",
  "popup_multiselect_patrolzones_name": "Çalışma Listesi Adı",
  "popup_multiselect_patrolzones_unnamed": "Adsız liste",
  "popup_multiselect_recolourtoomanyflatrides_variable": "Aynı anda {VALUE:int}'den fazla düz eğlencenin rengi değiştirilemiyor.",
  "popup_multiselect_recolourtoomanyprops_variable": "Aynı anda {VALUE:int}'den fazla dekor parçasının rengi değiştirilemiyor.",
  "popup_multiselect_recolourtoomanyrides_variable": "Aynı anda {VALUE:int}'den fazla eğlencenin rengi değiştirilemiyor.",
  "popup_multiselect_recolourtoomanytrackedrides_variable": "Aynı anda {VALUE:int}'den fazla hız treni, raylı eğlence veya akarsu yolunun rengi değiştirilemiyor.",
  "popup_multiselect_recolourtoomanyvolumes_variable": "Aynı anda {VALUE:int}'den fazla yol/havuz bölümünün rengi değiştirilemiyor.",
  "popup_multiselect_removelockeditems": "Kilitli öğeleri seçimden kaldır",
  "popup_multiselect_scenerygroupmerge": "Dekoru Dekor Grubuna Birleştir.",
  "popup_multiselect_title_multibuilding": "Bina Seçimi ({Count:separatedFloat:decimalPlaces=0})",
  "popup_multiselect_title_multicoaster": "Hız Treni Seçimi ({Count:separatedFloat:decimalPlaces=0})",
  "popup_multiselect_title_multiflatride": "Eğlence Seçimi ({Count:separatedFloat:decimalPlaces=0})",
  "popup_multiselect_title_multimixed": "Karışık Seçim ({Count:separatedFloat:decimalPlaces=0})",
  "popup_multiselect_title_multiscenery": "Dekor Seçimi ({Count:separatedFloat:decimalPlaces=0})",
  "popup_multiselect_title_patrolzones": "Çalışma Listesi Oluştur",
  "popup_multiselect_title_singlecustomnamed": "{NAME}",
  "popup_multiselect_tooltip_multiblueprint": "Seçimi Taslak Olarak Kaydet",
  "popup_multiselect_tooltip_multidelete": "Seçimi Yık [{#LogicalButton.Editors_Delete#}]",
  "popup_multiselect_tooltip_multimove": "Seçimi Taşı [{#LogicalButton.Editors_Move#}]",
  "popup_multiselect_tooltip_multimoveadvanced": "Seçimi Gelişmiş Taşı [{#LogicalButton.Editors_AdvancedMove#}]",
  "popup_multiselect_tooltip_singleblueprint": "Öğeyi Taslak Olarak Kaydet",
  "popup_multiselect_tooltip_singledelete": "Yık [{#LogicalButton.Editors_Delete#}]",
  "popup_multiselect_tooltip_singlemove": "Taşı [{#LogicalButton.Editors_Move#}]",
  "popup_multiselect_tooltip_singlemoveadvanced": "Gelişmiş Taşı [{#LogicalButton.Editors_AdvancedMove#}]",
  "popup_multiselect_toomanybuildings": "Aynı anda birden fazla bina kopyalanamıyor.",
  "popup_music_cancel": "İptal",
  "popup_music_favouritestab": "Favoriler",
  "popup_music_music": "Müzik",
  "popup_music_ok": "Tamam",
  "popup_music_planetcoastertab": "Planet Coaster Müziği",
  "popup_music_usermusictab": "Kullanıcı Müziği",
  "popup_open": "Aç",
  "popup_operations": "Operasyonlar",
  "popup_overview": "Genel Bakış",
  "popup_parkboundary_centre": "Sınır Kaydırma",
  "popup_parkboundary_centrex": "X Yönü",
  "popup_parkboundary_centrey": "Y Yönü",
  "popup_parkboundary_centrez": "Z Yönü",
  "popup_parkboundary_opacity": "Önizleme Opaklığı",
  "popup_parkboundary_size": "Sınır Boyutu",
  "popup_parkboundary_sizex": "Genişlik",
  "popup_parkboundary_sizey": "Yükseklik",
  "popup_parkboundary_sizez": "Uzunluk",
  "popup_parkboundary_spawnpoints": "Ziyaretçi Çıkış Noktaları",
  "popup_parkboundary_spawnpoints_add": "Çıkış Noktası Ekle",
  "popup_parkboundary_spawnpoints_edit": "Çıkış Noktasını Düzenle",
  "popup_parkboundary_spawnpoints_focus": "Kamerayı Çıkış Noktasına Odakla",
  "popup_parkboundary_title": "Park Sınırını Ayarla",
  "popup_peeps_headingto": "Gidiyor: {LOCATIONNAME}",
  "popup_peeps_needs_energy": "Enerji",
  "popup_peeps_needs_happiness": "Mutluluk",
  "popup_peeps_needs_header": "{PEEPNAME}'in İhtiyaçları",
  "popup_peeps_needs_hunger": "Açlık",
  "popup_peeps_needs_nausea": "Bulantı",
  "popup_peeps_needs_tabname": "İhtiyaçlar",
  "popup_peeps_needs_thinksheader": "{PEEPNAME} düşünüyor...",
  "popup_peeps_needs_thirst": "Susuzluk",
  "popup_peeps_needs_toilet": "Tuvalet",
  "popup_peeps_peepname": "{PEEPNAME}",
  "popup_peeps_thought": "\"{THOUGHT}\"",
  "popup_placesecondstation": "İkinci İstasyonu Yerleştir",
  "popup_placetriggerontrack": "Raya Tetikleyici Yerleştir",
  "popup_prestige": "Prestij",
  "popup_ratings": "Puanlar",
  "popup_regions_regionname": "{REGIONNAME}",
  "popup_restaurant_deselectall": "Tümünün Seçimini Kaldır",
  "popup_restaurant_selectall": "Tümünü Seç",
  "popup_ride_analytics_soon": "Eğlence analitiği yakında geliyor",
  "popup_ride_blocksectionedmode": "Blok Bölümlü",
  "popup_ride_boatspeed": "Tekne Hızı",
  "popup_ride_buspertrain": "Otobüs başına araç",
  "popup_ride_busspeed": "Otobüs Hızı",
  "popup_ride_capacity": "Kapasite",
  "popup_ride_carspeed": "Araba Hızı",
  "popup_ride_carspertrain": "Tren başına vagon",
  "popup_ride_carspertrainhint": "Eğlence Açıkken tren veya vagon düzenlenemez",
  "popup_ride_carspertrainlimit": "Daha fazla vagon eklemek için tüm istasyonların uzunluğunu artır.",
  "popup_ride_chairspeed": "Sandalye Hızı",
  "popup_ride_chairspergroup": "Grup başına sandalye",
  "popup_ride_coasterfriction": "Hız Treni Sürtünmesi",
  "popup_ride_coasterfriction_hint": "Bu hız treninin varsayılan sürtünmesine bir çarpan uygula.",
  "popup_ride_coasterfriction_label": "Sürtünme Çarpanı",
  "popup_ride_count": "{COUNT:separatedint}",
  "popup_ride_count_unknown": "-",
  "popup_ride_currency": "{VALUE:currency}",
  "popup_ride_currency_unknown": "-",
  "popup_ride_cycletime": "Döngü süresi: {LAST:float}s (ortalama {AVERAGE:float}s)",
  "popup_ride_dateopened": "Açılış tarihi",
  "popup_ride_disabledwhileopentooltip": "Eğlence Açıkken tren, araba, tur sayısı veya çalışma modu düzenlenemez",
  "popup_ride_disablefastpass": "Öncelikli Geçişi Devre Dışı Bırak",
  "popup_ride_duellingcoasters_add": "Zincire Eğlence Ekle",
  "popup_ride_duellingcoasters_chain_title": "Hız Treni Zinciri",
  "popup_ride_duellingcoasters_chainstatus_cannotsetopen_tooltip": "Bu Hız Treni Zincirindeki hiçbir hız treni veya raylı eğlence açılamaz.",
  "popup_ride_duellingcoasters_chainstatus_closed": "Zincir Durumu: Kapalı",
  "popup_ride_duellingcoasters_chainstatus_header": "Zincir Durumunu Ayarla",
  "popup_ride_duellingcoasters_chainstatus_nostatus": "Zincir Durumu Yok",
  "popup_ride_duellingcoasters_chainstatus_open": "Zincir Durumu: Açık",
  "popup_ride_duellingcoasters_chainstatus_open_tooltip": "",
  "popup_ride_duellingcoasters_chainstatus_setclosed_tooltip": "Zincirdeki tüm hız trenlerini ve raylı eğlenceleri Kapalı durumuna getir.",
  "popup_ride_duellingcoasters_chainstatus_setopen_tooltip": "Zincirdeki tüm hız trenlerini ve raylı eğlenceleri, açılabiliyorlarsa Açık durumuna getir.",
  "popup_ride_duellingcoasters_chainstatus_settesting_tooltip": "Zincirdeki tüm hız trenlerini ve raylı eğlenceleri, test edilebiliyorlarsa Test durumuna getir.",
  "popup_ride_duellingcoasters_chainstatus_testing": "Zincir Durumu: Test",
  "popup_ride_duellingcoasters_chainstatus_tooltip": "Zincir Durumu ayarlandığında, mümkünse zincirdeki tüm hız trenleri ve raylı eğlenceler aynı duruma getirilir.",
  "popup_ride_duellingcoasters_coaster_locate_tooltip": "Bu hız trenini veya raylı eğlenceyi dünyada bul.",
  "popup_ride_duellingcoasters_coaster_remove_tooltip": "Bu hız trenini veya raylı eğlenceyi zincirden sil.",
  "popup_ride_duellingcoasters_description": "Yükleme Kuralları sağlandığında Hız Trenlerinin ve Raylı Eğlencelerin aynı anda hareket etmesi için bir Hız Treni Zinciri oluştur.",
  "popup_ride_duellingcoasters_link": "Hız Treni Zinciri Oluştur",
  "popup_ride_duellingcoasters_remove_tooltip": "Bu Hız Treni Zincirini tamamen sil.",
  "popup_ride_duellingcoasters_rideclosed": "Kapalı veya arızalı hız trenleri ve raylı eğlenceler görmezden gelinir.",
  "popup_ride_duellingcoasters_rideopen": "Açık hız trenleri ve raylı eğlenceler aynı anda hareket eder.",
  "popup_ride_duellingcoasters_ridetesting": "Testteki hız trenleri ve raylı eğlenceler aynı anda hareket eder.",
  "popup_ride_duellingcoasters_title": "Hız Treni Zinciri",
  "popup_ride_enablefastpass": "Öncelikli Geçişi Etkinleştir",
  "popup_ride_enablefastpassaccessible": "Eğlence erişilebilir olana kadar etkinleştirilemez.",
  "popup_ride_enablefastpasshint": "Sırada yalnızca Öncelikli Geçiş sahiplerine özel bir bölüm oluştur. Öncelikli Geçiş satmak için bir Misafir Hizmetleri gereklidir",
  "popup_ride_enablefastpasslabel": "Öncelikli Geçiş satmak için bir Misafir Hizmetleri gereklidir",
  "popup_ride_entranceandexit": "Giriş ve Çıkış",
  "popup_ride_fastpassfraction": "Sıra Önceliği",
  "popup_ride_fastpassfraction_high": "Yüksek Öncelik",
  "popup_ride_fastpassfraction_low": "Düşük Öncelik",
  "popup_ride_fastpassfraction_medium": "Eşit Öncelik",
  "popup_ride_fastpassfractionhint": "Öncelikli Geçiş sahiplerinin ana sıraya ne kadar hızlı katıldığı\n- Öncelikli Geçişlerin değerini etkiler",
  "popup_ride_fastpassqueue": "Öncelikli Geçiş Sırası",
  "popup_ride_fastpassqueuesize": "Öncelikli Geçiş sırası boyutu: {LAST:float} (ortalama {AVERAGE:float})",
  "popup_ride_fastpassqueuetime": "Öncelikli Geçiş Sırası Süresi",
  "popup_ride_fastpassqueuetime_debug": "Öncelikli Geçiş sırası süresi: {LAST:float}s (ortalama {AVERAGE:float}s)",
  "popup_ride_finances_soon": "Eğlence finansları çok yakında",
  "popup_ride_gondolapergroup": "Grup başına gondol",
  "popup_ride_gondolaspeed": "Gondol Hızı",
  "popup_ride_groupspeed": "Grup Hızı",
  "popup_ride_guests_soon": "Ziyaretçi düşünceleri çok yakında",
  "popup_ride_guestsperhour": "Saatlik ziyaretçi: {LAST:float} (ortalama {AVERAGE:float})",
  "popup_ride_haunted": "Bu eğlence perili!",
  "popup_ride_idealprice": "İdeal bilet fiyatı: {VALUE:currency}",
  "popup_ride_kartspeed": "Kart Hızı",
  "popup_ride_lapshint": "Eğlence Açıkken tur sayısı düzenlenemez",
  "popup_ride_lapshint_desc": "Bir trenin durmadan önce istasyondan kaç kez geçeceği.",
  "popup_ride_lastmonthsprofit": "Geçen Ayın Karı",
  "popup_ride_leaveifwaiting": "İstasyonu bloke etme",
  "popup_ride_leaveifwaitinghint": "Gelen trenler minimum yolcu yükünü, minimum ve maksimum bekleme sürelerini geçersiz kılar\n- Aylık ziyaretçi sayısını artırabilir\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_lifetimearrivals": "Tüm Zamanların İnişleri",
  "popup_ride_lifetimedepartures": "Tüm Zamanların Binişleri",
  "popup_ride_lifetimeguests": "Toplam Ziyaretçi",
  "popup_ride_lifetimeguests_debug": "Toplam ziyaretçi: {GUESTS:int}",
  "popup_ride_lifetimeprofit": "Toplam Kar",
  "popup_ride_loadedguestsperhour": "Saatlik ziyaretçi (tam dolu): {LAST:float} (ortalama {AVERAGE:float})",
  "popup_ride_loadfraction": "Min. yolcu yükü",
  "popup_ride_loadfraction_all": "Tam Dolu",
  "popup_ride_loadfraction_half": "1/2 Dolu",
  "popup_ride_loadfraction_none": "Herhangi Bir Yük",
  "popup_ride_loadfraction_quarter": "1/4 Dolu",
  "popup_ride_loadfraction_threequarters": "3/4 Dolu",
  "popup_ride_loadfractiontooltip": "Trenin hareket edebilmesi için minimum doluluk oranı\n- Maksimum bekleme süresi tarafından geçersiz kılınır\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_loadfractiontooltiprides": "Eğlencenin başlayabilmesi için minimum doluluk oranı\n- Maksimum bekleme süresi tarafından geçersiz kılınır\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_loadrules": "Yükleme Kuralları",
  "popup_ride_loadsize": "Yük boyutu: {LAST:float} (ortalama {AVERAGE:float})",
  "popup_ride_loadtime": "Yükleme süresi: {LAST:float}s (ortalama {AVERAGE:float}s)",
  "popup_ride_maximumgroupsize": "Maksimum grup boyutu: {VALUE:int}",
  "popup_ride_maxwaitingtime": "Maks.",
  "popup_ride_maxwaitingtimehint": "Trenin minimum yolcu yükünü karşılamak için bekleyeceği en uzun süre\n- Aylık ziyaretçi sayısını artırabilir\n- Eğlence tamamen dolduğunda geçersiz kılınır\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_maxwaitingtimeridehint": "Eğlencenin minimum yolcu yükünü karşılamak için bekleyeceği en uzun süre\n- Aylık ziyaretçi sayısını artırabilir\n- Eğlence tamamen dolduğunda geçersiz kılınır\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_minimumriderheight": "Minimum yolcu boyu",
  "popup_ride_minimumriderheight_child": "Çocuk",
  "popup_ride_minimumriderheight_teenadult": "Genç/Yetişkin",
  "popup_ride_minwaitingtime": "Min.",
  "popup_ride_minwaitingtimehint": "Minimum yolcu yükü sağlandıysa trenin bu süreden sonra hareket etmesi\n- Sıra sürelerini azaltabilir ve trenleri birbirinden ayırabilir\n- Eğlence tamamen dolduğunda geçersiz kılınır\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_minwaitingtimeridehint": "Minimum yolcu yükü sağlandıysa eğlencenin bu süreden sonra başlaması\n- Sıra sürelerini azaltabilir\n- Eğlence tamamen dolduğunda geçersiz kılınır\n- Minimum kalkış aralığı da geçmiş olmalıdır",
  "popup_ride_monthlyarrivals": "Aylık İnişler",
  "popup_ride_monthlycarrunningcost": " - araba giderleri",
  "popup_ride_monthlydepartures": "Aylık Binişler",
  "popup_ride_monthlyguests": "Aylık Ziyaretçiler",
  "popup_ride_monthlyrunningcost": "Aylık İşletme Giderleri",
  "popup_ride_monthlystationrunningcost": " - istasyon giderleri",
  "popup_ride_monthlyutilityrunningcost": " - tesisat giderleri",
  "popup_ride_moveentrance": "Girişi Taşı",
  "popup_ride_moveexit": "Çıkışı Taşı",
  "popup_ride_numberofseats": "Koltuk sayısı: {SEATS:int}",
  "popup_ride_numboat": "Tekne sayısı",
  "popup_ride_numbus": "Otobüs sayısı",
  "popup_ride_numcar": "Araba sayısı",
  "popup_ride_numchair": "Sandalye sayısı",
  "popup_ride_numgondola": "Gondol sayısı",
  "popup_ride_numgroup": "Grup sayısı",
  "popup_ride_numkart": "Kart sayısı",
  "popup_ride_numlaps": "Tur sayısı",
  "popup_ride_numpasses": "İstasyonda geçişte dur",
  "popup_ride_numraft": "Sal sayısı",
  "popup_ride_numsleigh": "Kızak sayısı",
  "popup_ride_numtrain": "Tren sayısı",
  "popup_ride_numtrainslimit": "Daha fazla tren eklemek için istasyon uzunluğunu artırmayı veya tren başına araba sayısını azaltmayı deneyin.",
  "popup_ride_numtrainslimit_blocksection": "Daha fazla tren eklemek için ek blok bölümleri eklemeyi deneyin.",
  "popup_ride_occupancy": "Doluluk: %{LAST:float} (ortalama %{AVERAGE:float})",
  "popup_ride_operationmode": "Çalışma Modu",
  "popup_ride_operations_soon": "Eğlence işlemleri çok yakında",
  "popup_ride_options": "Eğlence Seçenekleri",
  "popup_ride_overview_soon": "Eğlence özeti çok yakında",
  "popup_ride_passeshint": "Eğlence Açıkken istasyondan geçiş sayısı düzenlenemez",
  "popup_ride_passeshint_desc": "Bir trenin durmadan önce istasyondan kaç kez geçeceği.",
  "popup_ride_percentage": "%{VALUE:int}",
  "popup_ride_powered_speed_off": "Tren hızını değiştirmek için eğlencenin kapatılması gerekiyor.",
  "popup_ride_poweredbehaviourlabel": "Motorlu Yavaşlama Azaltma",
  "popup_ride_poweredbehaviourtooltip": "Bu özellik açıkken, motorlu eğlenceler yavaşlamayı azaltmak ve heyecan verici hızı korumak için güç kullanır.",
  "popup_ride_prestige": "İtibar: {LAST:float} (ortalama {AVERAGE:float})",
  "popup_ride_prestigedeteriorationmultiplier": "İtibar Düşüş Çarpanı: {VALUE:float}",
  "popup_ride_projectedmonthlyincome": "Tahmini Aylık Gelir",
  "popup_ride_projectedmonthlyprofit": "Tahmini Aylık Kar",
  "popup_ride_queuescenery": "Sıra Dekor Puanı\n\nBu faktör eğlencenin İtibarına katkıda bulunur.\nSıralarınız ne kadar güzel görünürse, ziyaretçiler tarafından o kadar değerli bulunur.",
  "popup_ride_queuesize": "Sıra boyutu: {LAST:float} (ortalama {AVERAGE:float})",
  "popup_ride_queuetime": "Sıra Süresi\n\nEğlence bilet fiyatı, ziyaretçilerin sırada beklemeye ne kadar razı olduğunu etkiler.\n\nDüşük bilet fiyatları daha uzun sıralara yol açar.",
  "popup_ride_queuetime_debug": "Sıra süresi: {LAST:float}s (ortalama {AVERAGE:float}s)",
  "popup_ride_racing": "Yarış Seçenekleri",
  "popup_ride_raftspeed": "Sal Hızı",
  "popup_ride_refresh": "Yenile",
  "popup_ride_rideoptions": "Eğlence Seçenekleri",
  "popup_ride_sleighspeed": "Kızak Hızı",
  "popup_ride_statictrainnum": "{Value}: {num:int}\nBu eğlencenin hızını veya uzunluğunu değiştirmek grup sayısını etkiler.",
  "popup_ride_time_0": "{TIME:int} Dakika",
  "popup_ride_time_1": "{TIME:int} Dakika",
  "popup_ride_time_n": "{TIME:int} Dakika",
  "popup_ride_time_unknown": "-",
  "popup_ride_timebetweendepartures": "Min. kalkış aralığı",
  "popup_ride_timebetweendepartureshint": "Trenin hareket edebilmesi için geçmesi gereken süre\n- Arabaları birbirinden ayırmak için kullanışlıdır\n- Eğlence tamamen dolu olduğunda dahi uygulanır",
  "popup_ride_trackedrideoperationmode_blocksectioned": "Blok Bölümlü",
  "popup_ride_trackedrideoperationmode_blocksectioned_desc": "Birden fazla tren kullanılabilir; trenler blok bölüm parçalarında durur. Kullanılabilir tren sayısı blok bölüm parçalarının sayısına bağlıdır.",
  "popup_ride_trackedrideoperationmode_boomerang": "Bumerang",
  "popup_ride_trackedrideoperationmode_boomerang_desc": "Tek bir tren, istasyondan birden fazla kez ileri ve geri geçer.",
  "popup_ride_trackedrideoperationmode_default": "Standart",
  "popup_ride_trackedrideoperationmode_default_desc": "Standart hız treni işlevi.",
  "popup_ride_trackedrideoperationmode_lapping": "Tur Modu",
  "popup_ride_trackedrideoperationmode_lapping_desc": "Tek bir tren istasyondan birden fazla tur atabilir.",
  "popup_ride_trackedrideoperationmode_shuttlelaunched": "Fırlatmalı Mekik",
  "popup_ride_trackedrideoperationmode_shuttlelaunched_desc": "Tek bir tren istasyonun önünden çıkar ve ardından geriye fırlatılır. Bu mod, istasyondan hemen sonra Mekik Fırlatma Güçlendiricisi kullanıldığında otomatik olarak etkinleşir.",
  "popup_ride_trackedrideoperationmode_shuttlemode": "Mekik Modu",
  "popup_ride_trackedrideoperationmode_shuttlemode_desc": "Tek bir tren istasyonlardan ileri ve geri geçer.",
  "popup_ride_trainspeed": "Tren Hızı",
  "popup_ride_transport_stationbrokendown": "İstasyon arızalıyken açılamaz",
  "popup_ride_transport_stationhaunted": "İstasyon periliyken açılamaz",
  "popup_ride_transport_stationincompletehint": "İstasyon açılmadan önce kontrol listesi tamamlanmalıdır",
  "popup_ride_transport_stationopenclosehint": "İstasyonu açmak veya kapatmak için eğlencenin açık olması gerekir",
  "popup_ride_transportridefinancehint": "Fiyatlar her istasyon için ayrı ayrı belirlenir",
  "popup_ride_triggerbreakdown": "Arıza kuyruğuna al",
  "popup_ride_waitingtime": "Bekleme Süresi",
  "popup_ride_wear": "Aşınma oranı: {LAST:float}",
  "popup_rideplacement_attachpassqueue": "Öncelikli Geçiş sırasını bağla",
  "popup_rideplacement_attachqueue": "Girişe Sıra Ekle",
  "popup_rideplacement_attachticketbooth": "Sıraya Eğlence Girişi Ekle",
  "popup_rideplacement_attachticketboothtooltip": "Eğlence Girişi, sıranı yola bağlar. Yeterli alan bırakmayı unutma.",
  "popup_rideplacement_checklistheader": "Bu eğlenceyi açmak için şunları yapman gerekiyor:",
  "popup_rideplacement_connectentrancetopath": "Girişi Yola Bağla",
  "popup_rideplacement_passchecklistheader": "Öncelikli Geçiş için şunlara ihtiyacın var:",
  "popup_rideplacement_placeentrance": "Girişi Yerleştir",
  "popup_rideplacement_placeexit": "Çıkışı Yerleştir",
  "popup_rideplacement_placepriorityqueue": "Öncelikli Sırayı Yerleştir",
  "popup_rideplacement_placequeuemerge": "Öncelikli Çıkış Yerleştir",
  "popup_rideplacement_placequeuesplit": "Öncelikli Giriş Yerleştir",
  "popup_rideplacement_stationlistheader": "İstasyon Listesi",
  "popup_rideratings": "Eğlence Puanları",
  "popup_rides_exitingridenametogotoridename": "{RIDENAME} üzerinden {RIDENAME2}'ye",
  "popup_rides_guests": "Ziyaretçiler",
  "popup_rides_guests_stat": "{STAT}",
  "popup_rides_guests_statsheader": "Ziyaretçi İstatistikleri",
  "popup_rides_guests_thoughtsping": "Ziyaretçi düşüncelerini sorgula",
  "popup_rides_gueststhoughts": "Ziyaretçiler düşünüyor... \"{THOUGHT}\"",
  "popup_rides_navigatetoridenamevianame": "{RIDENAME} üzerinden {RIDENAME2}",
  "popup_rides_onridenametogotoridename": "{RIDENAME} üzerinden {RIDENAME2}'ye",
  "popup_rides_profit": "Toplam Kâr",
  "popup_rides_queueatridenametogotoridename": "{RIDENAME} üzerinden {RIDENAME2}'ye",
  "popup_rides_ridename": "{RIDENAME}",
  "popup_rides_ridenameandstationname": "{RIDENAME} ({STATIONNAME})",
  "popup_rides_stationincomplete": "Tamamlanmamış",
  "popup_rides_stationlist": "{RIDENAME} - {STATUS}",
  "popup_rides_vianame": "{RIDENAME} üzerinden",
  "popup_ridestats": "Eğlence İstatistikleri",
  "popup_ridetesting_averagespeed": "Ortalama Hız",
  "popup_ridetesting_colourblindtooltip": "Isı Haritası gradyan kontrastını Seçenekler'den değiştirebilirsiniz",
  "popup_ridetesting_cycletime": "Süre",
  "popup_ridetesting_duration": "Süre",
  "popup_ridetesting_excitement": "Heyecan",
  "popup_ridetesting_fear": "Korku",
  "popup_ridetesting_heatmaps": "Isı Haritaları",
  "popup_ridetesting_heatmaps_lap_n": "{VALUE:int}. Tur",
  "popup_ridetesting_heatmaps_live": "Canlı Veri",
  "popup_ridetesting_heatmaps_pass": "Isı Haritası Verisi",
  "popup_ridetesting_heatmaps_pass_n": "{VALUE:int}. Geçiş",
  "popup_ridetesting_heatmaps_previousrun": "Önceki Çalışma Verisi",
  "popup_ridetesting_height": "Yükseklik",
  "popup_ridetesting_lateralg": "Yanal G-kuvveti",
  "popup_ridetesting_length": "Uzunluk",
  "popup_ridetesting_livedata": "Canlı Veri",
  "popup_ridetesting_longg": "İleri G-kuvveti",
  "popup_ridetesting_maxdrop": "En Büyük Düşüş",
  "popup_ridetesting_maxlateralg": "Maks. Yanal G-kuvveti",
  "popup_ridetesting_maxneglongg": "Min. İleri G-kuvveti",
  "popup_ridetesting_maxnegvertg": "Min. Dikey G-kuvveti",
  "popup_ridetesting_maxposlongg": "Maks. İleri G-kuvveti",
  "popup_ridetesting_maxposvertg": "Maks. Dikey G-kuvveti",
  "popup_ridetesting_maxspeed": "Maks. Hız",
  "popup_ridetesting_nausea": "Mide Bulantısı",
  "popup_ridetesting_noheatmap": "YOK",
  "popup_ridetesting_numairtime": "Havada Kalma Sayısı",
  "popup_ridetesting_numinversions": "Ters Dönüş Sayısı",
  "popup_ridetesting_numsceneryreactions": "Dekor Tepkisi Sayısı",
  "popup_ridetesting_reputation": "Dekor Puanı",
  "popup_ridetesting_results": "Sonuçlar",
  "popup_ridetesting_speed": "Hız",
  "popup_ridetesting_starttest": "Testi Başlat",
  "popup_ridetesting_stoptest": "Testi Durdur",
  "popup_ridetesting_totalairtime": "Toplam Havada Kalma Süresi",
  "popup_ridetesting_tracklength": "Ray Uzunluğu",
  "popup_ridetesting_traversallength": "Kat Edilen Mesafe",
  "popup_ridetesting_triggers": "Tetikleyiciler",
  "popup_ridetesting_unknownstatvalue": "-",
  "popup_ridetesting_verticalg": "Dikey G-kuvveti",
  "popup_ridetesting_visualize": "Görselleştir",
  "popup_rideticketbooth_name": "Eğlence Girişi",
  "popup_selectobjecttoadd": "Eklenecek Nesneyi Seç",
  "popup_sequence": "Sıralama",
  "popup_sequence_addanimation": "Animasyon Ekle",
  "popup_sequence_deletedisabled": "Sıralamada en az 1 işlem bulunmalıdır",
  "popup_sequence_editortitle": "Eğlence Sıralaması",
  "popup_sequence_reset": "Animasyonları ve Tetikleyici Sırasını varsayılana sıfırla",
  "popup_sequence_rideopen": "Eğlence açıkken sıralama değiştirilemez",
  "popup_sequence_tooltip": "Eğlence sıralamanızı değiştirmek için animasyonları tıklayıp sürükleyin",
  "popup_shooting": "Nişancı Eğlencesi ve Tetikleyiciler",
  "popup_shops_itemextras": "Ek Seçenekler",
  "popup_starttesting": "Test Et",
  "popup_stationlist": "İstasyonlar",
  "popup_statistics": "İstatistikler",
  "popup_testing": "Test",
  "popup_testratings": "Test Puanları",
  "popup_titlestatus": "Eğlence durumu: {STATUS}",
  "popup_titlestatusstation": "İstasyon durumu: {STATUS}",
  "popup_tools": "Araçlar",
  "popup_tooltip_billboards_changeimagetab": "Görseller",
  "popup_tooltip_billboards_changemusictab": "Müzik Listesi",
  "popup_tooltip_billboards_faveimagetab": "Favoriler",
  "popup_tooltip_coastertrackedit_banktrack": "Ray Eğimini Ayarla",
  "popup_tooltip_coastertrackedit_expandselection": "Seçimi Genişlet",
  "popup_tooltip_coastertrackedit_trackbanking": "Ray Yatıklığı",
  "popup_tooltip_coastertrackedit_trackhorizontal": "Rayı Yatay Taşı",
  "popup_tooltip_coastertrackedit_tracklength": "Ray Uzunluğu",
  "popup_tooltip_coastertrackedit_trackpitch": "Ray Eğimi",
  "popup_tooltip_coastertrackedit_trackvertical": "Rayı Dikey Taşı",
  "popup_tooltip_coastertrackedit_turntrack": "Rayı Döndür",
  "popup_tooltip_displaysequencer_custommusic": "Müzik",
  "popup_tooltip_displaysequencer_deletetime": "Sil",
  "popup_tooltip_displaysequencer_specificmonths": "Tetikleyiciyi etkinleştirmek için belirli ayları seçin",
  "popup_tooltip_paths_anglesnap": "Açı Yakalamayı Etkinleştir",
  "popup_tooltip_paths_curvedslopes": "Eğimler ve merdivenler kavisli olabilir",
  "popup_tooltip_paths_deletepaths": "Sekmeyi Sil",
  "popup_tooltip_paths_elevatedrailing": "Yükseltilmiş yollar yerleştirildiğinde korkuluklu inşa edilir",
  "popup_tooltip_paths_enterat90": "Bağlanan yollar dik açıyla birleşir",
  "popup_tooltip_paths_exitat90": "Bağlanan yollar dik açıyla ayrılır",
  "popup_tooltip_paths_flattenterrain": "Yollar yerleştirildiğinde araziyi düzler",
  "popup_tooltip_paths_groundrailing": "Zemin yolları yerleştirildiğinde korkuluklu inşa edilir",
  "popup_tooltip_paths_kerbonground": "Zemin yolları bordür taşıyla inşa edilir",
  "popup_tooltip_paths_pathjoining": "Yol mevcut yollara yapışır",
  "popup_tooltip_paths_pathlength": "Yol Uzunluğu",
  "popup_tooltip_paths_pathsupports": "Yükseltilmiş yollar yerleştirildiğinde destekli inşa edilir",
  "popup_tooltip_paths_pathwidth": "Yol Genişliği",
  "popup_tooltip_paths_queuerailing": "Sıra yolları yerleştirildiğinde korkuluklu inşa edilir",
  "popup_tooltip_paths_squareedge": "Izgara üzerinde yol inşa ederken köşeleri dik yapar",
  "popup_tooltip_paths_tunnelling": "Yollar yerleştirildiğinde arazi içinden tünel açar",
  "popup_tooltip_prkmgmt_adultgroupcount": "Yetişkin grupları",
  "popup_tooltip_prkmgmt_avgadultspend": "Ortalama Yetişkin Harcaması",
  "popup_tooltip_prkmgmt_avgadulttime": "Yetişkinlerin Parkta Ortalama Süresi",
  "popup_tooltip_prkmgmt_avgfamilyspend": "Ortalama Aile Harcaması",
  "popup_tooltip_prkmgmt_avgfamilytime": "Ailelerin Parkta Ortalama Süresi",
  "popup_tooltip_prkmgmt_avgstaffenergy": "Ortalama Personel Enerjisi",
  "popup_tooltip_prkmgmt_avgteenspend": "Ortalama Genç Harcaması",
  "popup_tooltip_prkmgmt_avgteentime": "Gençlerin Parkta Ortalama Süresi",
  "popup_tooltip_prkmgmt_cancelmarketingcampaign": "Pazarlama kampanyasını iptal et",
  "popup_tooltip_prkmgmt_cancelresearch": "Araştırmayı İptal Et",
  "popup_tooltip_prkmgmt_changesalary": "Maaşı Değiştir",
  "popup_tooltip_prkmgmt_choosecoasterresearch": "Araştırılacak hız trenini seçin",
  "popup_tooltip_prkmgmt_choosefacilityresearch": "Araştırılacak tesisi seçin",
  "popup_tooltip_prkmgmt_chooserideresearch": "Araştırılacak eğlenceyi seçin",
  "popup_tooltip_prkmgmt_choosesceneryresearch": "Araştırılacak dekor paketini seçin",
  "popup_tooltip_prkmgmt_facilitiesbalancebutton": "Tesis dengesi",
  "popup_tooltip_prkmgmt_familygroupcount": "Aile grupları",
  "popup_tooltip_prkmgmt_gotofacility": "Tesise Git",
  "popup_tooltip_prkmgmt_gotoride": "Eğlenceye Git",
  "popup_tooltip_prkmgmt_gotostaff": "Personele Git",
  "popup_tooltip_prkmgmt_happinessbonus": "Ziyaretçi mutluluk bonusu",
  "popup_tooltip_prkmgmt_loans": "Parkınızı geliştirmek için krediler",
  "popup_tooltip_prkmgmt_marketingavctive": "Pazarlama kampanyası aktif",
  "popup_tooltip_prkmgmt_nomarketingactive": "Aktif pazarlama kampanyası yok",
  "popup_tooltip_prkmgmt_notificationstab": "Park Bildirimleri",
  "popup_tooltip_prkmgmt_parkoptions": "Park Puanı Dökümü ve Seçenekler",
  "popup_tooltip_prkmgmt_pauseresearch": "Araştırmayı Duraklat",
  "popup_tooltip_prkmgmt_prkmgmtbalancebutton": "Park yönetimi dengesi",
  "popup_tooltip_prkmgmt_researchanddevtab": "Yeni öğeler araştırın, kredi alın veya ziyaretçi çekmek için pazarlama kampanyası başlatın",
  "popup_tooltip_prkmgmt_riderating": "Eğlencelere dayalı park kalitesi",
  "popup_tooltip_prkmgmt_ridesbalancebutton": "Eğlence dengesi",
  "popup_tooltip_prkmgmt_ridescenerybalance": "Eğlenceler ve Dekor arasındaki park dengesi",
  "popup_tooltip_prkmgmt_sceneryrating": "Dekora dayalı park kalitesi",
  "popup_tooltip_prkmgmt_shopsprice": "Fiyatı Değiştir",
  "popup_tooltip_prkmgmt_teengroupcount": "Genç grupları",
  "popup_tooltip_prkmgmt_toggleautorenew": "Otomatik yenilemeyi Açık / Kapalı yap",
  "popup_tooltip_prkmgmt_trainstaffmember": "Personeli Eğit",
  "popup_tooltip_prkmgmt_vandalisedbenches": "Vandalize edilmiş bankları görüntüle",
  "popup_tooltip_prkmgmt_vandalisedbins": "Vandalize edilmiş çöp kutularını görüntüle",
  "popup_tooltip_scenarios_careerdesc": "Kariyer Açıklamasını Göster/Gizle",
  "popup_tooltip_scenarios_careereasy": "Kolay Hedefleri Göster/Gizle",
  "popup_tooltip_scenarios_careerhard": "Zor Hedefleri Göster/Gizle",
  "popup_tooltip_scenarios_careermedium": "Orta Hedefleri Göster/Gizle",
  "popup_tooltip_terrain_brushsize": "Fırça boyutunu ayarla",
  "popup_tooltip_terrain_brushstrength": "Fırça yoğunluğunu ayarla",
  "popup_transportstats": "Ulaşım İstatistikleri",
  "popup_triggeraddscenerydescription": "Tetikleyici noktasına bağlamak için tetiklenebilir bir dekor parçası seçin",
  "popup_triggeraddscenerytitle": "Tetiklenebilir Dekor Ekle",
  "popup_triggerobject": "{VALUE:int} Nesne",
  "popup_triggerobjects": "{VALUE:int} Nesne",
  "popup_triggerpiecesavailable": "Kullanılabilir parçalar",
  "popup_triggers": "Tetikleyiciler",
  "popup_triggers_cancel": "İptal",
  "popup_triggers_favouritestab": "Favoriler",
  "popup_triggers_ok": "Tamam",
  "popup_triggers_planetcoastertab": "Planet Coaster Tetikleyicileri",
  "popup_triggers_usertriggerstab": "Kullanıcı Tetikleyicileri",
  "popup_triggertimedelay": "Zaman Gecikmesi",
  "popup_unable_to_open_incomplete_tooltip": "Tamamlanmamış eğlence açılamaz",
  "popup_unknownoperation": "Bilinmeyen İşlem",
  "popup_vendingmachine_brokendown": "Arızalıyken otomat makineleri açılamaz",
}

tr_json_path = Path("../translations/Content0/tr.json")
data = json.loads(tr_json_path.read_text(encoding="utf-8"))
strings = data["strings"]

updated = 0
for key, translation in TRANSLATIONS.items():
    if key in strings:
        strings[key]["translation"] = translation
        strings[key]["status"] = "translated"
        strings[key]["category"] = "popup"
        updated += 1

tr_json_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"{updated} string guncellendi.")
