"""HUD string'lerini Content0/tr.json dosyasına uygular."""
import json
from pathlib import Path

TRANSLATIONS = {
    "hud_adultgroupmembercount": "Yetişkin Grup Ziyaretçileri",
    "hud_alertsandwarningsnotifications": "Uyarılar ve İkazlar",
    "hud_allnotifications": "Tüm Bildirimler",
    "hud_attachscenery_addobjects": "Nesne Ekle",
    "hud_attachscenery_objectscenerytool": "Nesne Dekor Aracı",
    "hud_averageguesthappinesstitle": "Ortalama Ziyaretçi Mutluluğu",
    "hud_averagehappiness": "Ortalama Ziyaretçi Mutluluğu",
    "hud_averagehappinessmultiplier": "Ziyaretçi Mutluluğu",
    "hud_backwardscompatibilitylimitdesc": "Bu park için geriye dönük uyumluluk limitini aştınız; Oswald-Eugene Sayacı değerini düşürene kadar park önceki nesil konsolda oynanamaz.",
    "hud_backwardscompatibilitylimittitle": "Geriye Dönük Uyumluluk Limiti",
    "hud_balancebonus": "Park Bakiye Bonusu",
    "hud_blueprintcorrupted": "Taslak bozuk",
    "hud_browsepathextras": "Yol Ekstralarına Göz At",
    "hud_browsepoolextras": "Havuz Ekstralarına Göz At",
    "hud_buttonprompt_hold": "(Basılı Tut)",
    "hud_buttonprompt_toggle": "(Geçiş)",
    "hud_challengemode_pausemenu_difficulty_easy": "ò Azaltılmış Ziyaretçi İhtiyaçları\nò Azaltılmış Güneş Yanığı\nò Personel için Azaltılmış Adil Ücret\nò Azaltılmış Ziyaretçi İadeleri\nò Standart Yıkım İadeleri",
    "hud_challengemode_pausemenu_difficulty_hard": "ò Artırılmış Ziyaretçi İhtiyaçları\nò Artırılmış Güneş Yanığı\nò Personel için Artırılmış Adil Ücret\nò Artırılmış Ziyaretçi İadeleri\nò Azaltılmış Yıkım İadeleri",
    "hud_challengemode_pausemenu_difficulty_medium": "ò Standart Ziyaretçi İhtiyaçları\nò Standart Güneş Yanığı\nò Personel için Standart Adil Ücret\nò Standart Ziyaretçi İadeleri\nò Standart Yıkım İadeleri",
    "hud_challengetitle_advertising": "Reklam",
    "hud_challengetitle_averageridemaintenance": "Ortalama Eğlence Bakımı",
    "hud_challengetitle_buildingfacilities": "Tesis İnşası",
    "hud_challengetitle_buildingpools": "Havuz İnşası",
    "hud_challengetitle_buildingrides": "Eğlence İnşası",
    "hud_challengetitle_dailyparkincome": "Günlük Park Geliri",
    "hud_challengetitle_employstaff": "Personel İstihdam Et",
    "hud_challengetitle_guestsinpark": "Parktaki Ziyaretçiler",
    "hud_challengetitle_overallguestmood": "Genel Ziyaretçi Ruh Hali",
    "hud_challengetitle_overallguestneeds": "Genel Ziyaretçi İhtiyaçları",
    "hud_challengetitle_overalllifeguardcoverage": "Genel Cankurtaran Kapsamı",
    "hud_challengetitle_overallpoolcleanliness": "Genel Havuz Temizliği",
    "hud_challengetitle_parkcleanliness": "Park Temizliği",
    "hud_challengetitle_parkexpansion": "Park Genişlemesi",
    "hud_challengetitle_parkrating": "Park Puanı",
    "hud_challengetitle_parkvalue": "Park Değeri",
    "hud_challengetitle_repayloans": "Kredileri Öde",
    "hud_challengetitle_research": "Araştırma",
    "hud_closeparkdialog_descr": "Bu işlem parkı planlanan saatten önce kapatacak ve tüm ziyaretçiler parktan ayrılacak.\nParkı yarına kadar yeniden açamazsınız.",
    "hud_closeparkdialog_title": "Park Kapanış Onayı",
    "hud_constructioncosts": "İnşaat Maliyetleri",
    "hud_controls_accelerate": "Hızlan",
    "hud_controls_addtobuilding": "Binaya / Dekor Grubuna Ekle",
    "hud_controls_addtrigger": "Tetikleyici Ekle",
    "hud_controls_advancedmove": "Gelişmiş Taşıma/Döndürmeyi Aç/Kapat",
    "hud_controls_advancedmoveselect": "Yerleştir",
    "hud_controls_axislock": "(Basılı Tut) Eksen Kilidi",
    "hud_controls_axislockmousekeyboard": "Eksen Kilidi",
    "hud_controls_back": "Geri",
    "hud_controls_banktrack": "Rayı Yan Eğ",
    "hud_controls_basicselect": "Seç",
    "hud_controls_basicselectshortcut": "Seç<br>(Basılı Tut) Düzenle (Kısayol)",
    "hud_controls_brakereverse": "Fren / Geri",
    "hud_controls_cancel": "İptal",
    "hud_controls_centrecamera": "Kamerayı Ortala",
    "hud_controls_changeangle": "Açıyı Değiştir",
    "hud_controls_changeaxis": "Ekseni Değiştir",
    "hud_controls_changecategory": "Kategoriyi Değiştir",
    "hud_controls_changecolours": "Renkleri Değiştir",
    "hud_controls_changeentrancegatestairheight": "Merdiven Yüksekliğini Değiştir",
    "hud_controls_changeheight": "Yüksekliği Değiştir",
    "hud_controls_changeheightmousekeyboard": "Dikey Hareket",
    "hud_controls_changeselectionsize": "Seçim Boyutu",
    "hud_controls_changesmoothingmode": "Düzleştirme Modunu Değiştir",
    "hud_controls_changetracklength": "Ray Uzunluğunu Artır / Azalt",
    "hud_controls_coasteraddtrack": "Ray Ekle",
    "hud_controls_coasterapplysmoothing": "Düzleştirme Uygula",
    "hud_controls_coasterbasicselect": "Seç",
    "hud_controls_coasterbuildingback": "Seçimi Kaldır",
    "hud_controls_coasterbuildingselect": "Yerleştir",
    "hud_controls_coasteredit_bank": "Yan Eğim Kontrollerini Göster",
    "hud_controls_coasteredit_banklength": "Yan Eğim / Uzunluk Kontrollerini Göster",
    "hud_controls_coasteredit_bankscale": "Yan Eğim / Ölçek Kontrollerini Göster",
    "hud_controls_coasteredit_curve": "Eğri Kontrollerini Göster",
    "hud_controls_coasteredit_curveslope": "Eğri / Eğim Kontrollerini Göster",
    "hud_controls_coasteredit_endmodify": "Seçimi Düzenlemeyi Durdur",
    "hud_controls_coasteredit_length": "Uzunluk Kontrollerini Göster",
    "hud_controls_coasteredit_scale": "Ölçek Kontrollerini Göster",
    "hud_controls_coasteredit_slope": "Eğim Kontrollerini Göster",
    "hud_controls_coasteredit_startmodify": "Seçimi Düzenle",
    "hud_controls_coasteredit_togglesecondary": "Ray Düzenleme Kontrollerini Aç/Kapat",
    "hud_controls_coastereditselect": "Düzleştirme Uygula",
    "hud_controls_coasternewselection": "Yeni Seçim",
    "hud_controls_connecttrack": "Rayı Bağla",
    "hud_controls_copy": "Kopyala",
    "hud_controls_createcustom": "Özel Oluştur",
    "hud_controls_crouch": "Çömel",
    "hud_controls_cycleentrancegatetype": "Sonraki Kapı Türü",
    "hud_controls_decreasebrushsize": "Fırça Boyutunu Küçült",
    "hud_controls_decreasemovementspeed": "Hareket Hızını Azalt",
    "hud_controls_delete": "Sil",
    "hud_controls_deleteopenradial": "Sil<br>(Basılı Tut) Radyal Menü",
    "hud_controls_demolish": "Yık",
    "hud_controls_detach": "Yoldan Ayır",
    "hud_controls_drivingsteer": "Direksiyon",
    "hud_controls_drivingtimecontrols": "Klakson",
    "hud_controls_edittrigger": "(Çift tıkla) Tetikleyiciyi Düzenle",
    "hud_controls_elevate": "Yükselt",
    "hud_controls_entermultiselect": "(Basılı Tut) Çoklu Seçim",
    "hud_controls_favourite": "Favorile",
    "hud_controls_gotostaffmember": "Personel Üyesine Git",
    "hud_controls_gridobjectplacementtimecontrols": "Yükseklik",
    "hud_controls_handbrake": "El Freni",
    "hud_controls_hidedescriptions": "Açıklamaları Gizle",
    "hud_controls_hideui": "Panelleri Gizle",
    "hud_controls_increasebrushsize": "Fırça Boyutunu Büyüt",
    "hud_controls_increasemovementspeed": "Hareket Hızını Artır",
    "hud_controls_interact": "Etkileş",
    "hud_controls_jump": "Zıpla",
    "hud_controls_jumptoheading": "Yöne Atla",
    "hud_controls_lookupdown": "Yukarı / Aşağı Bak",
    "hud_controls_move": "Taşı",
    "hud_controls_movecameraforwards": "Kamerayı Taşı",
    "hud_controls_movecamerasideways": "Kamerayı Taşı",
    "hud_controls_movecursorsideways": "İmleci Yanlara Taşı",
    "hud_controls_movecursorupdown": "İmleci Yukarı / Aşağı Taşı",
    "hud_controls_movepathforwards": "Yolu İleriye Taşı",
    "hud_controls_movepathsideways": "Yolu Yana Taşı",
    "hud_controls_moverotatealongaxis": "Nesneyi Eksen Boyunca Taşı / Döndür",
    "hud_controls_movetracksideways": "Rayı Yana Taşı",
    "hud_controls_movetrackupdown": "Rayı Yukarı / Aşağı Taşı",
    "hud_controls_movetrigger": "Tetikleyiciyi Taşı",
    "hud_controls_movevertical": "(Basılı Tut) Kamerayı Yukarı / Aşağı Taşı",
    "hud_controls_multiselectmode": "Çoklu Seçim Modu",
    "hud_controls_multiselectselect": "Seç",
    "hud_controls_multiselectselectdoubletap": "(Çift dokun) Bina/Hız Trenini Düzenle",
    "hud_controls_multiselectselecthold": "Birden Fazla Seç",
    "hud_controls_multiselecttimecontrols": "Seçimi Onayla",
    "hud_controls_navigatemenu": "Menüde Gezin",
    "hud_controls_nextalignmentoption": "Sonraki Hizalama Seçeneği",
    "hud_controls_nexttab": "Sonraki Sekme",
    "hud_controls_objectplacementrotateheight": "(Basılı Tut) Döndür / Yükseklik",
    "hud_controls_objectplacementselect": "Yerleştir",
    "hud_controls_objectplacementtimecontrols": "Döndür / Yükseklik",
    "hud_controls_openbrowserchangetab": "Tarayıcıyı Aç / Sekme Değiştir",
    "hud_controls_openradial": "(Basılı Tut) Radyal Menü",
    "hud_controls_opentesting": "Test Ekranını Aç",
    "hud_controls_options": "Seçenekler",
    "hud_controls_parkmanagement": "Park Yönetimi<br>Hedefler<br>Uyarılar",
    "hud_controls_patheditheight": "(Basılı Tut) Yüksekliği Değiştir",
    "hud_controls_patheditselect": "Yerleştir",
    "hud_controls_patheditslope": "Eğim",
    "hud_controls_pathedittimecontrols": "Eğim",
    "hud_controls_pause": "Duraklat",
    "hud_controls_pitchcamera": "Kamerayı Eğ",
    "hud_controls_place": "Yerleştir",
    "hud_controls_placeobject": "Yerleştir",
    "hud_controls_playtrigger": "Tetikleyiciyi Çalıştır",
    "hud_controls_previousnexttrigger": "Önceki / Sonraki Tetikleyici",
    "hud_controls_prevtab": "Sekme Değiştir",
    "hud_controls_pull": "Nesneyi Çek",
    "hud_controls_push": "Nesneyi İt",
    "hud_controls_pushpullobject": "Nesneyi Çek / İt",
    "hud_controls_radio": "Radyo",
    "hud_controls_removefrombuilding": "Binadan / Dekor Grubundan Çıkar",
    "hud_controls_removewater": "Suyu Kaldır",
    "hud_controls_resetheight": "Yüksekliği Sıfırla",
    "hud_controls_resetslope": "Eğimi Sıfırla",
    "hud_controls_resettrack": "Rayı Sıfırla",
    "hud_controls_rotate": "Döndür",
    "hud_controls_rotate90degrees": "90 Derece Döndür",
    "hud_controls_rotateanticlockwise": "Saat Yönünün Tersine Döndür",
    "hud_controls_rotatecamera": "Kamerayı Döndür",
    "hud_controls_rotateclockwise": "Saat Yönünde Döndür",
    "hud_controls_rotateincrement": "Adım Adım Döndür",
    "hud_controls_rotateincrementmousekeyboard": "Adım Adım Döndür",
    "hud_controls_rotatemousekeyboard": "90 Derece Döndür",
    "hud_controls_run": "Koş",
    "hud_controls_scale": "Ölçeklendir",
    "hud_controls_select": "Seç",
    "hud_controls_selectgrid": "Izgara Seç",
    "hud_controls_shoot": "Ateş Et",
    "hud_controls_shootinggamefire": "Ateş",
    "hud_controls_showhideobjectives": "Görevleri / Hedefleri Göster / Gizle",
    "hud_controls_siren": "Siren",
    "hud_controls_skip": "Atla",
    "hud_controls_skipdialogue": "Diyaloğu Atla",
    "hud_controls_skipdialogueandpathheight": "Diyaloğu Atla<br>(Basılı Tut) Yol Yüksekliği",
    "hud_controls_skipdialogueandverticalcameramovement": "Dikey Kamera Hareketi",
    "hud_controls_startvisitorcam": "Birinci Şahıs Kamerasını Başlat",
    "hud_controls_terrainbrushintensitymodifier": "Yoğunluğu Artır / Azalt",
    "hud_controls_terrainbrushsizemodifier": "Boyutu Artır / Azalt",
    "hud_controls_terraineditselect": "Araziyi Düzenle",
    "hud_controls_terrainedittimecontrols": "Boyut / Yoğunluk",
    "hud_controls_timecontrols": "(Basılı Tut) Zaman Kontrolleri",
    "hud_controls_togglemoverotate": "Ekseni Değiştir",
    "hud_controls_togglepathjoining": "Yol Birleştirmeyi Aç / Kapat",
    "hud_controls_toolsshortcuts": "Radyal Menü",
    "hud_controls_toolsshortcutsdelete": "Araç Kısayolları / Sil",
    "hud_controls_torch": "El Feneri",
    "hud_controls_trackeditfalloff_centre": "Merkez Azalma",
    "hud_controls_trackeditfalloff_even": "Düzgün Azalma",
    "hud_controls_trackeditmovement_relative": "Göreli Ray Hareketi",
    "hud_controls_trackeditmovement_world": "Dünya Ray Hareketi",
    "hud_controls_trackmodifyingexistingxmodifier": "Rayı Taşı",
    "hud_controls_tracktriggernextisland": "Sonraki Ray Dalına Geç",
    "hud_controls_tracktriggerpreviousisland": "Önceki Ray Dalına Geç",
    "hud_controls_uncrouch": "Doğrul",
    "hud_controls_walk": "Yürü",
    "hud_controls_zoomin": "Yaklaştır",
    "hud_controls_zoomout": "Uzaklaştır",
    "hud_controlsheader_advancedmove": "Gelişmiş Taşıma / Döndürme",
    "hud_controlsheader_basiccontrols": "Temel Kontroller",
    "hud_controlsheader_coasterbuilding": "Hız Treni ve Kaydırak İnşası",
    "hud_controlsheader_coasteredit": "Hız Treni ve Kaydırak Düzenleme",
    "hud_controlsheader_driving": "Sürüş",
    "hud_controlsheader_freecamera": "Serbest Kamera",
    "hud_controlsheader_multiselect": "Çoklu Seçim",
    "hud_controlsheader_objectplacement": "Nesne Taşı / Yerleştir",
    "hud_controlsheader_pathedit": "Yollar ve Havuzlar",
    "hud_controlsheader_ridecam": "Eğlence Kamerası",
    "hud_controlsheader_shootingridefree": "Nişancı Eğlencesi (Serbest Kamera)",
    "hud_controlsheader_shootingridestatic": "Nişancı Eğlencesi (Sabit Kamera)",
    "hud_controlsheader_terrainedit": "Arazi",
    "hud_createnew": "Yeni Oluştur",
    "hud_currentmonth": "Bu Ay",
    "hud_dailysummary_doyouwanttoclosethepark": "Parkı Kapatmak İstiyor Musunuz?",
    "hud_day": "Gün {Value:int}",
    "hud_daytime24": "Gün {Value:int} | {Hour24:int:minDigits=2}:{Minute:int:minDigits=2}",
    "hud_daytimeam": "Gün {Value:int} | {Hour12:int:minDigits=2}:{Minute:int:minDigits=2} ÖÖ",
    "hud_daytimepm": "Gün {Value:int} | {Hour12:int:minDigits=2}:{Minute:int:minDigits=2} ÖS",
    "hud_editheight": "Yüksekliği Düzenle",
    "hud_familygroupmembercount": "Aile Grubu Ziyaretçileri",
    "hud_fanfare_challengecomplete_besttime": "En İyi Süre",
    "hud_fanfare_challengecomplete_desc": "Tebrikler, 5 yıldızlı Park Puanına ulaştınız ve Zorluk Modunu tamamladınız! Bu park için artık yeni zorluk sunulmayacak.",
    "hud_fanfare_challengecomplete_exit": "Ana Menüye Dön",
    "hud_fanfare_challengecomplete_parkrating": "Park Puanı",
    "hud_fanfare_challengecomplete_stayinpark": "Parkta Kal",
    "hud_fanfare_challengecomplete_subtitle": "Maksimum Park Puanına Ulaşıldı",
    "hud_fanfare_challengecomplete_time": "Geçen Süre",
    "hud_fanfare_challengecomplete_title": "Zorluk Modu Tamamlandı",
    "hud_filterapplied": "{Value:int} Filtre Uygulandı",
    "hud_filtersapplied": "{Value:int} Filtre Uygulandı",
    "hud_flexicolour_resetcolours": "Varsayılana Sıfırla",
    "hud_fpovcamera": "Birinci Şahıs Kamerası",
    "hud_freecamera": "Serbest Kamera",
    "hud_freecameraoff": "Serbest Kamera KAPALI",
    "hud_freecameraon": "Serbest Kamera AÇIK",
    "hud_gamespeed1": "Oyun hızı x1",
    "hud_gamespeed2": "Oyun hızı x2",
    "hud_gamespeed3": "Oyun hızı x5",
    "hud_helppopup_blueprintplacement_title": "Taslak Yerleştirme Kontrolleri",
    "hud_helppopup_blueprints_toggleboundingboxplacement": "Sınır Kutusu Hizalamasını Aç/Kapat",
    "hud_helppopup_coasteredit_command_01": "Tutamaçları Kullan",
    "hud_helppopup_coasteredit_command_02": "Ray Parçası Yerleştir",
    "hud_helppopup_coasteredit_command_03": "Ray Parçasını Sil",
    "hud_helppopup_coasteredit_command_04": "Ray Parçasını Seç",
    "hud_helppopup_coasteredit_command_05": "İptal/Kapat",
    "hud_helppopup_coasteredit_command_06": "Açı Yakalama Açık/Kapalı",
    "hud_helppopup_coasteredit_description": "Rayı hassas biçimde düzenlemek için dünya içi düğmeleri kullanın. Sonraki ray parçasını yerleştirmek için hız treninin dışına sol tıklayın.",
    "hud_helppopup_coasteredit_input_onplacedpiece": "Yerleştirilen Parçada {ControlText}",
    "hud_helppopup_coasteredit_title": "Hız Treni Düzenleme Kontrolleri",
    "hud_helppopup_coastertriggers_description": "Hız treni tetikleyicileri, bir vagon rayın belirli bir noktasına ulaştığında animasyonlu nesneleri ve özel efektleri devreye sokmanızı sağlar.",
    "hud_helppopup_coastertriggers_title": "Hız Treni Tetikleyicileri",
    "hud_helppopup_control_hold": "{ControlText} (Basılı Tut)",
    "hud_helppopup_controls": "{ControlText}",
    "hud_helppopup_displaysequencer_description": "Etkinlik sıralayıcı, bir zamanlama ya da tek bir eğlence/hız treni tetikleyicisi aracılığıyla birden fazla nesne ve olayı devreye sokmanızı sağlar.",
    "hud_helppopup_displaysequencer_title": "Etkinlik Sıralayıcı",
    "hud_helppopup_dontshow": "Tüm İpuçlarını Devre Dışı Bırak",
    "hud_helppopup_entranceexit_command_01": "Yerleştirmeyi Onayla",
    "hud_helppopup_entranceexit_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_entranceexit_title": "Yerleştirme Kontrolleri",
    "hud_helppopup_morecontrols": "Daha Fazla Kontrol Göster",
    "hud_helppopup_mouseaxisscroll": "[MouseMiddle] (Kaydır)",
    "hud_helppopup_mouseaxisx": "[MouseMoveH]",
    "hud_helppopup_mouseaxisxy": "[MouseMove]",
    "hud_helppopup_mouseaxisy": "[MouseMoveV]",
    "hud_helppopup_mousebuttonleft": "[MouseLeft]",
    "hud_helppopup_mousebuttonmiddle": "[MouseMiddle]",
    "hud_helppopup_mousebuttonright": "[MouseRight]",
    "hud_helppopup_multiplacement_title": "Yerleştirme Kontrolleri",
    "hud_helppopup_multiselect_command_01": "Seç",
    "hud_helppopup_multiselect_command_02": "İptal/Kapat",
    "hud_helppopup_multiselect_command_03": "Seçime Ekle",
    "hud_helppopup_multiselect_command_03_stop": "Seçime Eklemeyi Durdur",
    "hud_helppopup_multiselect_command_04": "Seçimden Çıkar",
    "hud_helppopup_multiselect_command_04_stop": "Seçimden Çıkarmayı Durdur",
    "hud_helppopup_multiselect_command_05": "Öğe Seçimini Aç/Kapat",
    "hud_helppopup_multiselect_description": "Çoklu Seçim, düzenleme veya taslak oluşturmak için birden fazla öğe seçmenizi sağlar. İstediğiniz öğelerin üzerini sürükleyerek ya da tek tek seçip seçimi kaldırarak kullanabilirsiniz.",
    "hud_helppopup_multiselect_title": "Çoklu Seçim Aracı",
    "hud_helppopup_paths_command_01": "Yol Yerleştir",
    "hud_helppopup_paths_command_02": "Yolu Sil",
    "hud_helppopup_paths_command_03": "Yolu Yükselt/Alçalt",
    "hud_helppopup_paths_command_04": "Yol Aracını Kapat",
    "hud_helppopup_paths_command_05": "Yolu Yükselt (önizleme)",
    "hud_helppopup_paths_command_06": "Yolu Alçalt (önizleme)",
    "hud_helppopup_paths_command_07": "Kavşakları Döndür, Birleşimleri Düzleştir",
    "hud_helppopup_paths_command_08": "Yüksekliği Ayarla",
    "hud_helppopup_paths_command_09": "Yüksekliği Sıfırla",
    "hud_helppopup_paths_command_10": "Yol Birleşimlerini Devre Dışı Bırak",
    "hud_helppopup_paths_command_11": "Açı Yakalama Açık/Kapalı",
    "hud_helppopup_paths_command_12": "Uzunluğu Azalt",
    "hud_helppopup_paths_command_13": "Uzunluğu Artır",
    "hud_helppopup_paths_command_14": "Genişliği Azalt",
    "hud_helppopup_paths_command_15": "Genişliği Artır",
    "hud_helppopup_paths_command_16": "Araziyi Düzleştirmeyi Aç/Kapat",
    "hud_helppopup_paths_command_17": "Yol Silme Açık/Kapalı",
    "hud_helppopup_paths_description": "Ziyaretçilerinizin yürümesi için yollar yerleştirin. Yollar, park girişini eğlencelere ve etraftaki dükkânlara bağlar.",
    "hud_helppopup_paths_title": "Yol Kontrolleri",
    "hud_helppopup_ping": "Kontrol yardımı için buraya tıklayın",
    "hud_helppopup_quickstart": "Temel Tuşlar",
    "hud_helppopup_rideplacement_command_01": "Yerleştirmeyi Onayla",
    "hud_helppopup_rideplacement_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_rideplacement_command_03": "Döndür",
    "hud_helppopup_rideplacement_command_04": "90 Derece Döndür",
    "hud_helppopup_rideplacement_command_05": "Yükselt/Alçalt",
    "hud_helppopup_rideplacement_command_06": "Gelişmiş Taşı/Döndür Geçişi",
    "hud_helppopup_rideplacement_command_07": "Döndürme Yakalama Açık/Kapalı",
    "hud_helppopup_rideplacement_command_08": "Yüksekliği Sıfırla",
    "hud_helppopup_rideplacement_command_09": "Yüzey Eksenlerine Kilitle",
    "hud_helppopup_rideplacement_description": "Nesneleri parka yerleştirmeden önce imleçle konumlandırın. Döndürme ve yükseklik kontrollerini etkinleştirmek için klavyeyi kullanın.",
    "hud_helppopup_rideplacement_title": "Eğlence Yerleştirme Kontrolleri",
    "hud_helppopup_ridetriggers_description": "Eğlence tetikleyicileri, eğlence dizileri başladığında animasyonlu nesneleri ve özel efektleri devreye sokmanızı sağlar.",
    "hud_helppopup_ridetriggers_title": "Eğlence Tetikleyicileri",
    "hud_helppopup_sceneryplacement_advancedmove_command_01": "Yerleştirmeyi Onayla",
    "hud_helppopup_sceneryplacement_advancedmove_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_sceneryplacement_advancedmove_command_03": "Gelişmiş Taşı/Döndür Geçişi",
    "hud_helppopup_sceneryplacement_advancedmove_command_04": "Standart Taşımaya Geç",
    "hud_helppopup_sceneryplacement_advancedmove_description": "Nesneyi hassas biçimde taşımak veya farklı hareket seçenekleri arasında geçiş yapmak için dünya içi düğmeleri kullanın.",
    "hud_helppopup_sceneryplacement_advancedmove_title": "Gelişmiş Taşıma",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_01": "Yerleştirmeyi Onayla",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_03": "Döndür",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_04": "90 Derece Döndür",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_05": "Yükselt/Alçalt",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_06": "Gelişmiş Taşı/Döndür Geçişi",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_07": "Döndürme Yakalama Açık/Kapalı",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_08": "Yüksekliği Sıfırla",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_command_09": "Yüzey Eksenlerine Kilitle",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_description": "Nesneleri parka yerleştirmeden önce imleçle konumlandırın. Döndürme ve yükseklik kontrollerini etkinleştirmek için klavyeyi kullanın.",
    "hud_helppopup_sceneryplacement_gridobjectoffgrid_title": "Yerleştirme Kontrolleri",
    "hud_helppopup_sceneryplacement_gridobjectongrid_command_01": "Yerleştirmeyi Onayla",
    "hud_helppopup_sceneryplacement_gridobjectongrid_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_sceneryplacement_gridobjectongrid_command_03": "90 Derece Döndür",
    "hud_helppopup_sceneryplacement_gridobjectongrid_command_04": "Yükselt/Alçalt",
    "hud_helppopup_sceneryplacement_gridobjectongrid_command_05": "Yüzey Eksenlerine Kilitle",
    "hud_helppopup_sceneryplacement_gridobjectongrid_description": "Bina yapıları oluşturmak için ızgarayı kullanın, ardından dekor öğeleriyle süsleyin. Döndürme ve yükseklik kontrollerini etkinleştirmek için klavyeyi kullanın.",
    "hud_helppopup_sceneryplacement_gridobjectongrid_title": "Izgara Yerleştirme Kontrolleri",
    "hud_helppopup_sceneryplacement_nongridobject_command_01": "Yerleştirmeyi Onayla",
    "hud_helppopup_sceneryplacement_nongridobject_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_sceneryplacement_nongridobject_command_03": "Döndür",
    "hud_helppopup_sceneryplacement_nongridobject_command_04": "90 Derece Döndür",
    "hud_helppopup_sceneryplacement_nongridobject_command_05": "Yükselt/Alçalt",
    "hud_helppopup_sceneryplacement_nongridobject_command_06": "Gelişmiş Taşı/Döndür Geçişi",
    "hud_helppopup_sceneryplacement_nongridobject_command_07": "Döndürme Yakalama Açık/Kapalı",
    "hud_helppopup_sceneryplacement_nongridobject_command_08": "Yüksekliği Sıfırla",
    "hud_helppopup_sceneryplacement_nongridobject_command_09": "Yüzey Eksenlerine Kilitle",
    "hud_helppopup_sceneryplacement_nongridobject_command_10": "Yüzeye Hizala Açık/Kapalı",
    "hud_helppopup_sceneryplacement_nongridobject_command_11": "Tutturma Noktası Konumlandırma Modu",
    "hud_helppopup_sceneryplacement_nongridobject_description": "Nesneleri parka yerleştirmeden önce imleçle konumlandırın. Döndürme ve yükseklik kontrollerini etkinleştirmek için klavyeyi kullanın.",
    "hud_helppopup_sceneryplacement_nongridobject_title": "Yerleştirme Kontrolleri",
    "hud_helppopup_sceneryplacement_pathextra_description": "Yol Ekstraları parkı ziyaretçiler için daha güzel bir yer hâline getirir. Ziyaretçilerin kullanabilmesi için imlecinizle Yol Ekstralarını yolların üzerine veya kenarlarına yerleştirin.",
    "hud_helppopup_sceneryselect_command_01": "Parçayı Seç",
    "hud_helppopup_sceneryselect_command_02": "Çoklu Seçim",
    "hud_helppopup_sceneryselect_command_03": "Seçimi Sil",
    "hud_helppopup_sceneryselect_command_04": "Seçime Ekle",
    "hud_helppopup_sceneryselect_command_05": "Seçimden Çıkar",
    "hud_helppopup_sceneryselect_command_06": "Öğe Seçimini Aç/Kapat",
    "hud_helppopup_sceneryselect_title": "Bina Düzenleme Kontrolleri",
    "hud_helppopup_select_command_01": "Seç",
    "hud_helppopup_select_command_02": "İptal, Kapat, Seçimi Kaldır",
    "hud_helppopup_select_command_03": "Kamerayı Kaydır",
    "hud_helppopup_select_command_04": "Kamerayı Yaklaştır/Uzaklaştır",
    "hud_helppopup_select_command_05": "Kamerayı Döndür",
    "hud_helppopup_select_command_06": "Yardımı Göster/Gizle",
    "hud_helppopup_select_command_07": "Serbest Kamera Açık/Kapalı",
    "hud_helppopup_select_command_08": "Serbest Kamera Hızı",
    "hud_helppopup_select_command_09": "Serbest Kamerayı Yükselt",
    "hud_helppopup_select_command_10": "Serbest Kamerayı Alçalt",
    "hud_helppopup_select_command_11": "Oyun Hızı",
    "hud_helppopup_select_command_12": "Zamanı Duraklat",
    "hud_helppopup_select_command_13": "Geri Al",
    "hud_helppopup_select_command_14": "Yeniden Yap",
    "hud_helppopup_select_command_15": "Parkı Kaydet Menüsü",
    "hud_helppopup_select_command_16": "Kamera Feneri",
    "hud_helppopup_select_description": "Bilgi panelini ve yönetim seçeneklerini görüntülemek için parkta bir öğe seçin. İnşaata başlamak veya daha fazla seçeneğe ulaşmak için ekranın alt kısmındaki menüleri açın.",
    "hud_helppopup_select_title": "Temel Kontroller",
    "hud_helppopup_staffbuilding_description": "Personel binaları, personelin mola vermesini ve enerji toparlamasını sağlar.\nYerleşim kapasitesini artırmak ve ekstra avantajlar edinmek için avantajlar sekmesinden satın alma yapabilirsiniz.",
    "hud_helppopup_staffbuilding_title": "Personel Binası",
    "hud_helppopup_staffplacement_command_01": "Personel Üyesi Yerleştir",
    "hud_helppopup_staffplacement_command_02": "Yerleştirmeyi İptal Et",
    "hud_helppopup_staffplacement_description": "Personeli parka yerleştirmeden önce imleçle konumlandırın.",
    "hud_helppopup_staffplacement_title": "Personel Yerleştirme Kontrolleri",
    "hud_helppopup_terrain_command_01": "Fırçayı Uygula",
    "hud_helppopup_terrain_command_02": "Ters Fırçayı Uygula (İt/Çek)",
    "hud_helppopup_terrain_command_03": "Fırça Yoğunluğu",
    "hud_helppopup_terrain_command_04": "Fırça Boyutu",
    "hud_helppopup_terrain_description": "Bu yaratıcı araçlarla parkınızın manzarasını şekillendirin. Çeşitli Heykel, Boyama ve Su fırçaları arasından seçim yapın, ardından imlecinizin çevresindeki alana uygulayın.",
    "hud_helppopup_terrain_title": "Arazi Düzenleme Kontrolleri",
    "hud_helppopup_transportedit_description": "Ulaşım Eğlenceleri birden fazla istasyon yerleştirmenize olanak tanır; her istasyon ziyaretçilere yeni bir biniş noktası sunar. Rayı hassas biçimde düzenlemek için dünya içi düğmeleri kullanın. Sonraki ray parçasını yerleştirmek için eğlencenin dışına sol tıklayın.",
    "hud_helppopup_transportedit_title": "Ulaşım Eğlencesi Düzenleme Kontrolleri",
    "hud_inputhints_header": "Kontrol İpuçları",
    "hud_insufficientpower": "Yetersiz Güç",
    "hud_lightingoff": "Aydınlatmayı KAPAT",
    "hud_lightingon": "Aydınlatmayı AÇ",
    "hud_mangementmenu_manage": "Park Yönetimi",
    "hud_mangementmenu_parkname": "{Name}",
    "hud_marketingbonus": "Pazarlama Bonusu",
    "hud_month01": "Oca",
    "hud_month02": "Şub",
    "hud_month03": "Mar",
    "hud_month04": "Nis",
    "hud_month05": "May",
    "hud_month06": "Haz",
    "hud_month07": "Tem",
    "hud_month08": "Ağu",
    "hud_month09": "Eyl",
    "hud_month10": "Eki",
    "hud_month11": "Kas",
    "hud_month12": "Ara",
    "hud_monthlyprofit": "Aylık Kâr",
    "hud_months": "Ay",
    "hud_nopower": "Güç Yok",
    "hud_notification_disable_generic_category": "Bu kategoriye ait bazı bildirimler oyun ayarlarından devre dışı bırakılmış.",
    "hud_notification_disableall_generic_category": "Bu kategoriye ait tüm bildirimler devre dışı bırakılmış.",
    "hud_notificationapply": "Uygula",
    "hud_notificationcancel": "İptal",
    "hud_notificationdismiss": "Kapat",
    "hud_notificationrest": "+{Value:int}",
    "hud_notifications": "Bildirimler",
    "hud_notificationsall": "Tümü",
    "hud_notificationsautomarkread": "Bildirimleri otomatik okundu olarak işaretle",
    "hud_notificationsbuildings": "Binalar",
    "hud_notificationsdisablethiscategory": "Bu Kategoriyi Devre Dışı Bırak",
    "hud_notificationsdismissall": "Tümünü Kapat",
    "hud_notificationsettings": "Ayarlar",
    "hud_notificationsfacilities": "Tesisler",
    "hud_notificationsfacilitiesandutilities": "Tesisler ve Altyapı",
    "hud_notificationsfinances": "Finanslar",
    "hud_notificationsgameplay": "Oyun",
    "hud_notificationsguests": "Ziyaretçiler",
    "hud_notificationsimportant": "Önemli",
    "hud_notificationslistandpopup": "Bildirimler ve açılır pencere",
    "hud_notificationslistonly": "Yalnızca bildirimler",
    "hud_notificationsmutethiscategory": "Bu kategoriyi sustur",
    "hud_notificationsnothing": "Bildirim yok",
    "hud_notificationspark": "Park Yönetimi",
    "hud_notificationsparkmanagement": "Park Yönetimi",
    "hud_notificationspath": "Yol",
    "hud_notificationsrides": "Eğlenceler",
    "hud_notificationssecurity": "Güvenlik",
    "hud_notificationssequence": "Diziler",
    "hud_notificationssettings": "Ayarlar",
    "hud_notificationsstaff": "Personel",
    "hud_notificationsstalls": "Dükkanlar",
    "hud_notificationsurgent": "Önemli",
    "hud_notificationswaterparks": "Su Parkları",
    "hud_nowaterfiltration": "Su Filtrasyonu Yok",
    "hud_numberofguests": "Toplam Ziyaretçi Sayısı",
    "hud_objectivespanel_blocked": "Engellendi",
    "hud_objectivespanel_bronzemedal": "Bronz Madalya",
    "hud_objectivespanel_challengescomplete_title": "Tüm Görevler Tamamlandı, Tebrikler!",
    "hud_objectivespanel_challengesdesc": "5 yıldızlı Park Puanına ulaşmak için görevleri tamamla. Uygun olduğunda zaman içinde yeni görevler görünecek.",
    "hud_objectivespanel_challengesheader": "Görevler",
    "hud_objectivespanel_claimreward": "Ödülü Al",
    "hud_objectivespanel_complete": "Tamamlandı",
    "hud_objectivespanel_completionreward": "Tamamlama Ödülü",
    "hud_objectivespanel_deletechallengetooltip": "Bu görevi sil\nBir süre sonra yeni bir görev gelecek",
    "hud_objectivespanel_discardchallenge": "Görevi İptal Et",
    "hud_objectivespanel_emptychallenges_desc": "Yeni görevler birazdan görünecek.",
    "hud_objectivespanel_emptychallenges_title": "Daha Fazla Görev Geliyor!",
    "hud_objectivespanel_focusobjectives": "Odaklan",
    "hud_objectivespanel_goldmedal": "Altın Madalya",
    "hud_objectivespanel_hidechallengetooltip": "Görevi oyunda gizle",
    "hud_objectivespanel_hidedescription": "Açıklamayı gizle",
    "hud_objectivespanel_hideobjectives": "Gizle",
    "hud_objectivespanel_hideobjectivetooltip": "Hedefi oyunda gizle",
    "hud_objectivespanel_hidepaneltooltip": "Hedefleri gizle",
    "hud_objectivespanel_nochallenges": "Aktif görev yok",
    "hud_objectivespanel_noobjectives": "Hedefler Tamamlandı",
    "hud_objectivespanel_objectivesheader": "Hedefler",
    "hud_objectivespanel_pinobjectivespanel": "Hedefler Panelini Sabitle",
    "hud_objectivespanel_platinummedal": "Platin Madalya",
    "hud_objectivespanel_replaydialogue": "Diyaloğu tekrarla",
    "hud_objectivespanel_rewardsavailable": "Ödüller Mevcut",
    "hud_objectivespanel_showchallengetooltip": "Görevi oyunda göster",
    "hud_objectivespanel_showdescription": "Açıklamayı göster",
    "hud_objectivespanel_showobjectivetooltip": "Hedefi oyunda göster",
    "hud_objectivespanel_showpaneltooltip": "Hedefleri göster",
    "hud_objectivespanel_silvermedal": "Gümüş Madalya",
    "hud_objectivespanel_skipdialogue": "Diyaloğu geç",
    "hud_off": "Kapalı",
    "hud_on": "Açık",
    "hud_openparkdialog_descr": "Bu işlem parkı açacak.",
    "hud_openparkdialog_title": "Parkı Aç — Onay",
    "hud_otherrunningcosts": "Park Yönetimi",
    "hud_overview": "Genel Bakış",
    "hud_parkexpansion_buylabel": "Satın Al: {Value:currency}",
    "hud_parkexpansion_completed": "Tamamlandı",
    "hud_parkexpansion_confirmpurchase": "{Location} Satın Alımını Onayla",
    "hud_parkexpansion_confirmpurchasedesc": "Bu işlemle birlikte bu arazi inşaata açılacak.",
    "hud_parkexpansion_confirmpurchasesubtitle": "Bu araziyi satın almak {Value:currency} tutacak",
    "hud_parkexpansion_landacquireddescription": "Parkı genişletmek için bir alan seç.",
    "hud_parkexpansion_landacquiredtitle": "Arazi Satın Alındı",
    "hud_parkexpansion_landstatelocked": "Kilitli",
    "hud_parkexpansion_landstatepurchased": "Sahip Olundu",
    "hud_parkexpansion_noobjectivesheader": "Hedef Gerekmiyor",
    "hud_parkexpansion_norestrictionsheader": "İnşaat Kısıtlaması Yok",
    "hud_parkexpansion_objectivesheader": "Hedef Gerekiyor",
    "hud_parkexpansion_purchaselandheader": "Arazi Satın Al",
    "hud_parkexpansion_restrictionsheader": "İnşaat Kısıtlamaları",
    "hud_parkexpansion_title": "Park Genişletme",
    "hud_parkinfo_finances": "{Value:currency}",
    "hud_parkinfo_parkname": "{Name}",
    "hud_parkinfo_rating": "{Value:float:decimalPlaces=0}",
    "hud_parkinfo_unlimitedfinances": "Sınırsız",
    "hud_parkinfo_visitorscount": "{Value:separatedFloat:decimalPlaces=0}",
    "hud_parkrating": "Park Puanı",
    "hud_parkzones_area": "Alan",
    "hud_parkzones_brushsize": "Fırça Boyutu",
    "hud_parkzones_deletebrush": "Fırçayı Sil",
    "hud_parkzones_editbrush": "Fırçayı Düzenle",
    "hud_parkzones_editparkzones": "Personel Bölgelerini Düzenle",
    "hud_parkzones_editzonelabel": "Bölgeyi Düzenle",
    "hud_parkzones_emptyshops": "Dükkân yok",
    "hud_parkzones_guestpopularity": "Ziyaretçi Popülaritesi",
    "hud_parkzones_guests": "Ziyaretçiler",
    "hud_parkzones_lastmonth": "Geçen Ay",
    "hud_parkzones_maintheme": "Ana Tema",
    "hud_parkzones_previousday": "Önceki Gün",
    "hud_parkzones_previousrides": "Önceki Gündeki Eğlenceler",
    "hud_parkzones_profit": "Gelir",
    "hud_parkzones_properties": "Özellikler",
    "hud_parkzones_rating": "Puan",
    "hud_parkzones_sceneryrating": "Dekor Puanı",
    "hud_parkzones_selecticon": "Simge Seç",
    "hud_parkzones_selectzone": "Bölge Seç",
    "hud_parkzones_title": "Personel Bölgeleri",
    "hud_parkzones_zoneareaheader": "Bölge Alanı",
    "hud_parkzones_zonecolour": "Bölge Rengi",
    "hud_parkzones_zonedetailsheader": "Bölge Detayları",
    "hud_redo": "Yinele",
    "hud_returntobrowser": "Tarayıcıya Dön",
    "hud_rideentrancepicker_entrancesettings": "Giriş ayarları",
    "hud_rideentrancepicker_entrancetype": "Tür",
    "hud_rideentrancepicker_entrancetype_gate": "Kapı",
    "hud_rideentrancepicker_entrancetype_stairs": "Merdiven",
    "hud_rideprofits": "Eğlence Gelirleri",
    "hud_ridequality": "Eğlence Puanı",
    "hud_saving": "Kaydediliyor...",
    "hud_sceneryquality": "Dekor Puanı",
    "hud_settingsmenu_communitytranslation": "{Name} tarafından topluluk çevirisi",
    "hud_settingsmenu_settingstooltip": "Seçenekler",
    "hud_settingsmenu_version": "Sürüm {Version}",
    "hud_shopandfacilityprofits": "Dükkan ve Tesis Gelirleri",
    "hud_shopmenu_blueprints": "Taslaklarım",
    "hud_shopmenu_buildings": "Binalar",
    "hud_shopmenu_coasters": "Hız Trenleri",
    "hud_shopmenu_construction": "İnşaat",
    "hud_shopmenu_create": "Oluştur",
    "hud_shopmenu_edit": "Düzenle",
    "hud_shopmenu_guests": "Ziyaretçiler",
    "hud_shopmenu_path_extras": "Yol Ekstraları",
    "hud_shopmenu_recentblueprints": "Son Taslaklar",
    "hud_shopmenu_rides": "Eğlenceler",
    "hud_shopmenu_scenery": "Dekor",
    "hud_shopmenu_shops": "Tesisler",
    "hud_shopmenu_staff": "Personel",
    "hud_shopmenu_themeparks": "Tema Parkları",
    "hud_shopmenu_trackedrides": "Ray Eğlenceleri",
    "hud_shopmenu_ugc": "  Öğeler",
    "hud_shopmenu_waterparks": "Su Parkları",
    "hud_shopmenu_waterrides": "Su Eğlenceleri",
    "hud_simplecamera": "Basit kamera",
    "hud_standardcamera": "Standart kamera",
    "hud_teengroupmembercount": "Genç Grup Ziyaretçileri",
    "hud_time24": "{Hour24:int:minDigits=2}:{Minute:int:minDigits=2}",
    "hud_time24seconds": "{Hour24}:{Minute}:{Seconds}",
    "hud_timeam": "{Hour12:int:minDigits=2}:{Minute:int:minDigits=2} am",
    "hud_timepanel_title": "Aydınlatmayı ayarla:",
    "hud_timepaused": "Süre duraklatıldı",
    "hud_timepm": "{Hour12:int:minDigits=2}:{Minute:int:minDigits=2} pm",
    "hud_timeunpaused": "Süre devam ediyor",
    "hud_toocomplex": "Karmaşıklık ölçümü çok yüksek. Bazı nesneleri kaldırmayı dene.",
    "hud_tools_copy": "Kopyala",
    "hud_tools_createblueprint": "Taslak Oluştur",
    "hud_tools_demolish": "Yık",
    "hud_tools_elevate": "Yükselt",
    "hud_tools_fences": "Çitler",
    "hud_tools_foliage": "Dekor Fırçası",
    "hud_tools_guestspaths": "Ziyaretçi Yolu",
    "hud_tools_mirror": "Aynala",
    "hud_tools_move": "Taşı",
    "hud_tools_multiselect": "Çoklu Seçim",
    "hud_tools_paint": "Boya",
    "hud_tools_parkexpansion": "Park Genişletme",
    "hud_tools_parkzones": "Personel Bölgeleri",
    "hud_tools_pathextras": "Yol Ekstraları",
    "hud_tools_paths": "Yollar",
    "hud_tools_poolextras": "Havuz Ekstraları",
    "hud_tools_pools": "Havuzlar",
    "hud_tools_power": "Güç",
    "hud_tools_queues": "Sıralar",
    "hud_tools_queuespaths": "Sıra Yolu",
    "hud_tools_rotate": "Döndür",
    "hud_tools_scale": "Ölçekle",
    "hud_tools_staffpaths": "Personel Yolları",
    "hud_tools_staffschedule": "Personel Programı",
    "hud_tools_terrain": "Arazi",
    "hud_tools_waterfiltration": "Su Filtrasyonu",
    "hud_toolsmenu_path": "Yollar",
    "hud_toolsmenu_path_tooltip": "Yol düzenleyiciyi aç",
    "hud_toolsmenu_pools": "Havuzlar",
    "hud_toolsmenu_pools_tooltip": "Havuz düzenleyiciyi aç",
    "hud_toolsmenu_terrain": "Arazi",
    "hud_toolsmenu_terrain_tooltip": "Arazi düzenleyiciyi aç",
    "hud_tooltip_attractionslists": "Aktiviteler Listesi",
    "hud_tooltip_cameraeffects": "Kamera Efektleri",
    "hud_tooltip_challengespopup": "Görevler",
    "hud_tooltip_delete": "Silme Modu (Yakında)",
    "hud_tooltip_freecamera": "Serbest Kamera",
    "hud_tooltip_gamespeed": "Oyun Hızını Değiştir [{#LogicalButton.Editors_AdjustSimulationSpeed#}]",
    "hud_tooltip_helppopup": "Yardım [{#LogicalButton.Editors_ToggleControlHelp#}]",
    "hud_tooltip_lighting": "Aydınlatmayı Ayarla",
    "hud_tooltip_multiselect": "Çoklu Seçim[{#LogicalButton.HUD_TabMultiSelect#}]",
    "hud_tooltip_multiselect_addition": "Seçime eklemek için tıkla veya sürükle",
    "hud_tooltip_multiselect_clear": "Seçimi Temizle",
    "hud_tooltip_multiselect_regular": "Birden fazla öğe seçmek için sürükle\n[{#LogicalButton.Editors_AdditiveGroupSelectModifier#}] seçime eklemek, [{#LogicalButton.Editors_ToggleGroupSelectModifier#}] çıkarmak, [{#LogicalButton.Editors_ToggleGroupSelectModifier#}]+[{#LogicalButton.Editors_AdditiveGroupSelectModifier#}] değiştirmek için.",
    "hud_tooltip_noresearchedentries": "Burada hiç öğen yok, araştırma yapmayı dene!",
    "hud_tooltip_notificationspopup": "Bildirimler",
    "hud_tooltip_objectivespopup": "Hedefler",
    "hud_tooltip_parkmanagement": "Park Yönetimi",
    "hud_tooltip_pause": "Duraklatmayı Aç/Kapat [{#LogicalButton.Editors_ToggleSimulationSpeed#}]",
    "hud_tooltip_redo": "Yinele [{#LogicalButton.Editors_Redo#}]",
    "hud_tooltip_selectmode": "Seçim Modu",
    "hud_tooltip_simplecamera": "Basit kamera",
    "hud_tooltip_standardcamera": "Standart kamera",
    "hud_tooltip_undo": "Geri Al [{#LogicalButton.Editors_Undo#}]",
    "hud_torch": "El Feneri",
    "hud_torchoff": "El Feneri KAPALI",
    "hud_torchon": "El Feneri AÇIK",
    "hud_triggerplacementpanel_confirmplacement": "Yerleşimi Onayla",
    "hud_triggerplacementpanel_description": "Olay Dizisinin başlayacağı raya tetikleyiciler ekle.",
    "hud_triggerplacementpanel_title": "Diziyi Tetikle",
    "hud_triggerspanel_description": "Eğlence rayına tetikleyiciler ekle",
    "hud_triggerspanel_edittrigger": "Düzenle",
    "hud_triggerspanel_placenewtrigger": "Yeni Tetikleyici Yerleştir",
    "hud_triggerspanel_racing_triggeralllaps": "Tüm Turlarda Tetikle",
    "hud_triggerspanel_racing_triggerallplaces": "Tüm Konumlarda Tetikle",
    "hud_triggerspanel_racing_triggeronlap": "{Value:int}. Turda Tetikle",
    "hud_triggerspanel_racing_triggeronposition": "{Value:int}. Konumda Tetikle",
    "hud_triggerspanel_racing_triggeronvictorylap": "Zafer Turunda Tetikle",
    "hud_triggerspanel_title": "Diziyi Tetikle",
    "hud_undo": "Geri Al",
    "hud_unknown_value": "-",
    "hud_untidinessmultiplier": "Dağınıklık Cezası",
    "hud_weather_severeweatherwarning": "Park işleyişini etkileyebilecek sert hava geliyor.",
    "hud_weatherreport_highlowtemperature": "{Value:int}°C / {Target:int}°C",
    "hud_weatherreport_highlowtemperaturef": "{Value:int}°F / {Target:int}°F",
    "hud_weatherreport_hour": "{Value:int}:00",
    "hud_weatherreport_hourlyreporttitle": "Saatlik Rapor",
    "hud_weatherreport_legendclosed": "Park Kapalı",
    "hud_weatherreport_legendnow": "Şu An",
    "hud_weatherreport_legendopen": "Park Açık",
    "hud_weatherreport_overrideweather": "Havayı Geçersiz Kıl",
    "hud_weatherreport_seasonautumn": "Sonbahar",
    "hud_weatherreport_seasonspring": "İlkbahar",
    "hud_weatherreport_seasonsummer": "Yaz",
    "hud_weatherreport_seasonwinter": "Kış",
    "hud_weatherreport_temperaturesingle": "{Value:int}°C",
    "hud_weatherreport_temperaturesinglef": "{Value:int}°F",
    "hud_weatherreport_weatherclear": "Açık",
    "hud_weatherreport_weathercloudy": "Bulutlu",
    "hud_weatherreport_weatherdayafter": "Öbür Gün",
    "hud_weatherreport_weatherheavyrain": "Yoğun Yağmur",
    "hud_weatherreport_weatherlightrain": "Hafif Yağmur",
    "hud_weatherreport_weatheroverriden": "Hava Geçersiz Kılındı",
    "hud_weatherreport_weathersnow": "Kar",
    "hud_weatherreport_weathersunny": "Güneşli",
    "hud_weatherreport_weatherthunderstorm": "Fırtına",
    "hud_weatherreport_weathertoday": "Bugünün Havası",
    "hud_weatherreport_weathertomorrow": "Yarın",
    "hud_weatherreport_weatherwindy": "Rüzgarlı",
    "hud_weathersandbox_nooverride": "Geçersiz Kılma Yok",
    "hud_weathersandbox_overrideweather": "Havayı Geçersiz Kıl",
    "hud_weathersandbox_weatherclear": "Açık",
    "hud_weathersandbox_weatherclearday": "Açık (Gündüz)",
    "hud_weathersandbox_weatherclearnight": "Açık (Gece)",
    "hud_weathersandbox_weathercloudy": "Bulutlu",
    "hud_weathersandbox_weathercloudyday": "Bulutlu (Gündüz)",
    "hud_weathersandbox_weathercloudynight": "Bulutlu (Gece)",
    "hud_weathersandbox_weatherheavyrain": "Yoğun Yağmur",
    "hud_weathersandbox_weatherheavyrainday": "Yoğun Yağmur (Gündüz)",
    "hud_weathersandbox_weatherheavyrainnight": "Yoğun Yağmur (Gece)",
    "hud_weathersandbox_weatherhotsun": "Kavurucu Güneş",
    "hud_weathersandbox_weatherhotsunday": "Kavurucu Güneş (Gündüz)",
    "hud_weathersandbox_weatherhotsunnight": "Kavurucu Güneş (Gece)",
    "hud_weathersandbox_weatherlightrain": "Hafif Yağmur",
    "hud_weathersandbox_weatherlightrainday": "Hafif Yağmur (Gündüz)",
    "hud_weathersandbox_weatherlightrainnight": "Hafif Yağmur (Gece)",
    "hud_weathersandbox_weatheroverridden": "Hava Geçersiz Kılındı",
    "hud_weathersandbox_weatherwindy": "Rüzgarlı",
    "hud_weathersandbox_weatherwindyday": "Rüzgarlı (Gündüz)",
    "hud_weathersandbox_weatherwindynight": "Rüzgarlı (Gece)",
}

tr_json_path = Path("../translations/Content0/tr.json")
data = json.loads(tr_json_path.read_text(encoding="utf-8"))
strings = data["strings"]

updated = 0
for key, translation in TRANSLATIONS.items():
    if key in strings:
        strings[key]["translation"] = translation
        strings[key]["status"] = "translated"
        strings[key]["category"] = "hud"
        updated += 1

tr_json_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"{updated} string güncellendi.")
